Repository metal3-io/baremetal-operator, pull requests merged in 2019-12, with the labels that each got.

#354 Add more privilege to BMO for configmap and secret resources
  deploy/role.yaml
Labels: approved, lgtm, size/XS

#355 Add support for redfish virtual media
  pkg/bmc/access_test.go
  pkg/bmc/redfish.go
Labels: approved, lgtm, size/M

#357 Add ilo5-virtual-media bmc support
  pkg/bmc/access_test.go
  pkg/bmc/redfish.go
Labels: approved, lgtm, size/S

#359 Add idrac redfish virtual media bmc support
  pkg/bmc/access.go
  pkg/bmc/access_test.go
  pkg/bmc/idrac.go
  pkg/bmc/ipmi.go
  pkg/bmc/irmc.go
  pkg/bmc/redfish.go
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/L

#319 Configure RAID Interface for iRMC driver
  pkg/bmc/irmc.go
Labels: approved, lgtm, size/XS

#362 Update unit tests for AccessDetails interface
  pkg/bmc/access_test.go
Labels: approved, lgtm, needs-ok-to-test, size/M

#365 Rename some oc CLI docs to kubectl
  docs/dev-setup.md
  docs/publishing-images.md
Labels: approved, lgtm, size/S

#331 Create an actionResult type to encapsulate the result of a reconcile action
  pkg/controller/baremetalhost/action_result.go
  pkg/controller/baremetalhost/baremetalhost_controller.go
  pkg/controller/baremetalhost/host_state_machine.go
Labels: approved, lgtm, size/L

#366 Update CRD file name in dev guide
  docs/dev-setup.md
Labels: approved, lgtm, ok-to-test, size/XS
