Repository metal3-io/baremetal-operator, pull requests merged in 2019-10, with the labels that each got.

#311 Install gosec and golint in Makefile if needed
  .travis.yml
  Makefile
Labels: size/S

#314 Add OWNERS file.
  OWNERS
Labels: size/XS

#312 Check namespace when matching Secret references
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  pkg/apis/metal3/v1alpha1/baremetalhost_types_test.go
Labels: approved, lgtm, size/S

#309 Update ironic deployment to latest requirements
  Makefile
  deploy/ironic_bmo_configmap.yaml
  deploy/mariadb-password.yaml
  deploy/operator_ironic.yaml
Labels: size/M

#313 Don't publish multiple events on missing Secret
  pkg/controller/baremetalhost/baremetalhost_controller.go
Labels: approved, lgtm, size/S

#308 doc: add more literature to api doc
  docs/api.md
Labels: approved, lgtm, size/L

#322 make the credential tracking fields optional
  deploy/crds/metal3_v1alpha1_baremetalhost_crd.yaml
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
Labels: approved, lgtm, size/XS

#321 Add a set of hack scripts and fix corresponding warnings
  docs/api.md
  docs/baremetalhost-states.md
  docs/dev-setup.md
  docs/publishing-images.md
  docs/testing.md
  hack/gofmt.sh
  hack/gosec.sh
  hack/govet.sh
  hack/markdownlint.sh
  hack/shellcheck.sh
  hack/unit.sh
  pkg/bmc/access.go
  pkg/bmc/access_test.go
  pkg/bmc/idrac.go
  pkg/bmc/redfish.go
  tools/clean_host.sh
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/L

#304 let ironic look up the image checksum value
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
Labels: approved, lgtm, size/M

#296 Use leader election mechanism from controller-runtime library
  cmd/manager/main.go
Labels: approved, lgtm, size/S

#324 Use kustomize for deploying baremetal-operator
  Makefile
  deploy/ironic_bmo_configmap.env
  deploy/ironic_bmo_configmap.yaml
  deploy/kustomization.yaml
  deploy/mariadb-password.yaml
  deploy/namespace.yaml
  deploy/operator_ironic.yaml
Labels: approved, lgtm, size/L

#330 Parameterize container runtime in scripts
  hack/gofmt.sh
  hack/gosec.sh
  hack/govet.sh
  hack/markdownlint.sh
  hack/shellcheck.sh
  hack/unit.sh
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/M

#285 Model Host with a finite state machine
  docs/BaremetalHost_ProvisioningState.dot
  docs/BaremetalHost_ProvisioningState.png
  docs/api.md
  docs/baremetalhost-states.md
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  pkg/controller/baremetalhost/baremetalhost_controller.go
  pkg/controller/baremetalhost/host_state_machine.go
Labels: approved, lgtm, size/XL

#334 bug: Extra double quotes causes local ironic script to fail
  tools/run_local_ironic.sh
Labels: approved, lgtm, ok-to-test, size/S
