Repository metal3-io/baremetal-operator, pull requests merged in 2019-11, with the labels that each got.

#339 BMO+Ironic container local run script fixed
  tools/run_local_ironic.sh
Labels: approved, lgtm, ok-to-test, size/S

#335 Add metal3 metadata for deployment from baremetalhost
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
Labels: approved, lgtm, size/S

#346 Updates BMO depencies and tools
  deploy/kustomization.yaml
Labels: approved, lgtm, size/XS

#347 Add maelk and stbenjam as approvers
  OWNERS
Labels: approved, lgtm, size/XS

#350 Limit BMO access to only BMH in all namespaces
  deploy/role.yaml
  deploy/role_binding.yaml
Labels: approved, lgtm, size/M
