Repository metal3-io/baremetal-operator, pull requests merged in 2020-05, with the labels that each got.

#499 add test for operator-sdk docker file
  Makefile
Labels: approved, lgtm, size/S

#503 symlink role file used by operator-sdk
  deploy/role.yaml
Labels: approved, lgtm, size/XS

#491 make gofmt job strict
  Makefile
  cmd/manager/main.go
  hack/gofmt.sh
  pkg/bmc/access_test.go
  pkg/controller/baremetalhost/action_result.go
  pkg/hardware/profile.go
  pkg/provisioner/ironic/ironic_test.go
Labels: approved, lgtm, priority/important-soon, size/L

#484 Makefile: update operator-sdk command
  Makefile
Labels: approved, lgtm, ok-to-test, size/XS

#506 Postpone inspector start when running out of cluster
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/XS

#508 fix the broken link to vbmc doc
  docs/dev-setup.md
Labels: approved, lgtm, ok-to-test, size/XS

#488 Fix some warning: "redundant type from array, slice, or map composite literal"
  pkg/bmc/access_test.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/ironic_test.go
Labels: approved, lgtm, ok-to-test, size/M

#401 Expand image checksum support
  deploy/crds/metal3.io_baremetalhosts_crd.yaml
  docs/api.md
  go.mod
  go.sum
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  pkg/apis/metal3/v1alpha1/baremetalhost_types_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
Labels: approved, lgtm, ok-to-test, size/L

#511 Run ironic-endpoint-keepalived container outside the cluster
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/S

#510 fix operator-sdk commands in the makefile
  Makefile
Labels: approved, lgtm, size/XS

#515 Add a tool to convert ironic introspection data to HardwareDetails
  Makefile
  cmd/make-introspection/main.go
  pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go
  pkg/provisioner/ironic/hardwaredetails/hardwaredetails_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
Labels: approved, lgtm, size/XL

#520 Rename make-introspection to get-hardware-details
  Makefile
  cmd/get-hardware-details/main.go
Labels: approved, lgtm, size/XS

#516 Requeue after writing status from annotation
  pkg/controller/baremetalhost/baremetalhost_controller.go
Labels: approved, lgtm, size/XS

#523 fix go lint in CI
  .travis.yml
  Makefile
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  pkg/controller/baremetalhost/baremetalhost_controller.go
Labels: approved, lgtm, size/S

#528 Fix version string
  Makefile
Labels: approved, lgtm, ok-to-test, size/XS

#526 Add status annotation documentation
  docs/statusAnnotation.md
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
Labels: approved, lgtm, size/M

#527 clean up Makefile
  .travis.yml
  Makefile
  hack/Dockerfile.golint
  hack/golint.sh
Labels: approved, lgtm, size/M

#518 Fix IP address in ironic_ci.env
  deploy/ironic_ci.env
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/S

#514 Get rid of extra resource write during delete
  pkg/controller/baremetalhost/baremetalhost_controller.go
Labels: approved, lgtm, size/XS

#534 Remove ironic workaround when running locally
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/XS

#532 Register host config data error metric
  pkg/controller/baremetalhost/metrics.go
Labels: approved, lgtm, size/XS

#535 handle missing image in GetImageChecksum
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  pkg/apis/metal3/v1alpha1/baremetalhost_types_test.go
Labels: approved, lgtm, size/S

#538 Unify the image reference in operator deployments
  deploy/operator/no_ironic/operator.yaml
Labels: approved, lgtm, size/XS

#533 Add Image disk format in api and ironic updates
  deploy/crds/metal3.io_baremetalhosts_crd.yaml
  docs/api.md
  go.mod
  hack/unit.sh
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  pkg/apis/metal3/v1alpha1/zz_generated.deepcopy.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
Labels: approved, lgtm, size/M

#531 Add missing delay in ValidateManagementAccess()
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/XS

#539 fix typos in state diagram
  docs/BaremetalHost_ProvisioningState.dot
  docs/BaremetalHost_ProvisioningState.png
Labels: approved, lgtm, size/XS
