Repository metal3-io/baremetal-operator, pull requests merged in 2020-04, with the labels that each got.

#474 Fix make test phony to remove dep-check call
  Makefile
Labels: approved, lgtm, size/S

#473 New kustomize config for BMO standalone, needed with kind when ironic…
  deploy/ironic-outside-config/ironic_bmo_configmap.env
  deploy/ironic-outside-config/kustomization.yaml
  deploy/operator/no_ironic/operator.yaml
  tools/run_local_ironic.sh
Labels: approved, lgtm, ok-to-test, size/M

#478 Default missing variables
  deploy/ironic-keepalived-config/ironic_bmo_configmap.env
Labels: approved, lgtm, size/XS

#480 Fix Ironic fast-track for local BMO deployment
  deploy/ironic_ci.env
Labels: approved, lgtm, size/XS

#448 Implement metadata interface for baremetal operator
  deploy/crds/metal3.io_baremetalhosts_crd.yaml
  docs/api.md
  go.mod
  go.sum
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  pkg/apis/metal3/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/baremetalhost/host_config_data.go
  pkg/controller/baremetalhost/host_config_data_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/provisioner.go
Labels: approved, lgtm, ok-to-test, size/L

#479 Make BMO as part of CAPM3 deployment
  deploy/bmo-capm3/README.md
  deploy/bmo-capm3/ironic_bmo_configmap.env
  deploy/bmo-capm3/kustomization.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S

#486 Add openstack profile
  docs/api.md
  pkg/hardware/profile.go
Labels: approved, lgtm, ok-to-test, size/S

#470 Put BMH status in annotation while reconciliation
  go.mod
  go.sum
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  pkg/controller/baremetalhost/baremetalhost_controller.go
  pkg/controller/baremetalhost/baremetalhost_controller_test.go
Labels: approved, lgtm, size/L

#487 Update operator-sdk
  Makefile
  go.mod
  go.sum
  pkg/apis/metal3/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/XL

#494 remove lint job from travis
  .travis.yml
Labels: approved, lgtm, size/XS

#496 fix kubebuilder validation for vlanid
  deploy/crds/metal3.io_baremetalhosts_crd.yaml
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
Labels: approved, lgtm, size/S

#492 update vendored gosec dependencies
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#489 document openapi-gen dependency
  docs/dev-setup.md
Labels: approved, lgtm, size/XS

#497 set up check to ensure operator-sdk generation is done
  Makefile
  hack/Dockerfile.operator-sdk
  hack/generate.sh
Labels: approved, lgtm, size/M
