Repository metal3-io/baremetal-operator, pull requests merged in 2020-12, with the labels that each got.

#733 Add manifest linting script
  config/basic-auth/default/credentials_patch.yaml
  config/basic-auth/default/kustomization.yaml
  config/basic-auth/tls/credentials_patch.yaml
  config/basic-auth/tls/kustomization.yaml
  config/tls/kustomization.yaml
  config/tls/tls_ca_patch.yaml
  config/webhook/kustomization.yaml
  config/webhook/service_patch.yaml
  docs/deploying.md
  hack/manifestlint.sh
Labels: approved, lgtm, size/M

#732 Make 'get bmh' output concise and column one-word
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
Labels: approved, lgtm, ok-to-test, size/S

#716 Handle re-registration in all states
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  controllers/metal3.io/action_result.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/adopt_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/provision_test.go
  pkg/provisioner/ironic/updatehardwarestate_test.go
  pkg/provisioner/provisioner.go
Labels: approved, lgtm, size/L

#734 Add a Makefile target for running manifest validation
  Makefile
  docs/testing.md
  hack/manifestlint.sh
Labels: approved, lgtm, size/XS

#715 Look up existing nodes by MAC address
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/testserver/ironic.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: approved, lgtm, size/L

#737 Avoid getting stuck in ValidateManagementAccess due to node state
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: approved, lgtm, size/L

#735 Handle cleaning failures during provisioning
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/provision_test.go
Labels: approved, lgtm, size/S

#738 Add kubebuilder validation for ClockSpeed
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#747 Filter out status updates from the reconcile loop
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
Labels: approved, lgtm, size/L

#736 Add console=ttyS0 to kernel params
  docs/dev-setup.md
  ironic-deployment/default/ironic_bmo_configmap.env
  ironic-deployment/keepalived/ironic_bmo_configmap.env
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/S

#751 Bug 1907612: Update kubernetes deps to 1.20
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/L

#752 Fix a typo in doc/dev-setup.md
  docs/dev-setup.md
Labels: approved, lgtm, size/XS
