Repository metal3-io/baremetal-operator, pull requests merged in 2020-07, with the labels that each got.

#567 pkg/bmc: refactor to support all schemes
  pkg/bmc/access.go
  pkg/bmc/access_test.go
  pkg/bmc/ibmc.go
  pkg/bmc/idrac.go
  pkg/bmc/ipmi.go
  pkg/bmc/irmc.go
  pkg/bmc/redfish.go
Labels: approved, lgtm, size/M

#566 Do not set the status annotation
  pkg/controller/baremetalhost/baremetalhost_controller.go
  pkg/controller/baremetalhost/baremetalhost_controller_test.go
Labels: approved, lgtm, size/L

#294 Default to use soft power off instead of hard power off
  pkg/provisioner/ironic/errors.go
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/L

#411 add ilo5-redfish alias
  docs/api.md
  pkg/bmc/redfish.go
Labels: approved, lgtm, size/XS

#571 define the Unmanaged state
  docs/baremetalhost-states.md
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
Labels: approved, lgtm, size/S

#579 Set Online to false when rendering BMH CRs
  cmd/make-bm-worker/templates/templates.go
  cmd/make-bm-worker/templates/templates_test.go
  cmd/make-virt-host/main.go
Labels: approved, lgtm, size/S

#572 Replace provisioning interface var
  deploy/ironic_ci.env
Labels: approved, lgtm, size/XS

#577 Update testing documentation with tool installation directions
  docs/testing.md
Labels: approved, lgtm, ok-to-test, size/M

#576 clean up makefile and CI scripts
  Makefile
  hack/gofmt.sh
  hack/gosec.sh
  hack/govet.sh
  hack/unit.sh
  version/version.go
Labels: approved, lgtm, size/M

#569 Implement an Unmanaged (discovered) state (2)
  docs/BaremetalHost_ProvisioningState.dot
  docs/BaremetalHost_ProvisioningState.png
  docs/api.md
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  pkg/controller/baremetalhost/baremetalhost_controller.go
  pkg/controller/baremetalhost/baremetalhost_controller_test.go
  pkg/controller/baremetalhost/host_state_machine.go
  pkg/controller/baremetalhost/metrics.go
Labels: approved, lgtm, size/L

#588 Fix error handling reading status annotation
  pkg/controller/baremetalhost/baremetalhost_controller.go
Labels: approved, lgtm, size/S

#589 do not log for paused hosts
  pkg/controller/baremetalhost/baremetalhost_controller.go
Labels: approved, lgtm, size/XS

#590 add explicit boot mode field to baremetal host
  deploy/crds/metal3.io_baremetalhosts_crd.yaml
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
Labels: approved, lgtm, size/M

#585 Use actionContinueNoWrite when power State == desired
  pkg/controller/baremetalhost/baremetalhost_controller.go
Labels: approved, lgtm, size/XS

#592 Avoid extra requeues when credentials missing
  pkg/controller/baremetalhost/baremetalhost_controller.go
Labels: approved, lgtm, size/S

#591 stop reconciling paused hosts
  pkg/controller/baremetalhost/baremetalhost_controller.go
  pkg/controller/baremetalhost/baremetalhost_controller_test.go
Labels: approved, lgtm, size/S

#599 refactor redfish driver hierarchy
  pkg/bmc/idrac_virtualmedia.go
  pkg/bmc/redfish.go
  pkg/bmc/redfish_virtualmedia.go
Labels: approved, lgtm, size/L

#603 dep: cve: bump go-openapi/spec to v0.19.9
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#605 add -boot-mode argument to make-bm-worker
  cmd/make-bm-worker/main.go
  cmd/make-bm-worker/templates/templates.go
Labels: approved, lgtm, size/S

#597 Switch CRD version to apiextensions.k8s.io/v1
  Makefile
  deploy/crds/metal3.io_baremetalhosts_crd.yaml
Labels: approved, lgtm, size/XXL

#606 Add support for build variables
  Makefile
Labels: approved, lgtm, ok-to-test, size/XS

#602 implement explicit boot mode api field
  deploy/crds/metal3.io_baremetalhosts_crd.yaml
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  pkg/controller/baremetalhost/baremetalhost_controller.go
  pkg/controller/baremetalhost/baremetalhost_controller_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
Labels: approved, lgtm, size/L

#574 Check provisioner ready status when applying reconcile logic
  pkg/controller/baremetalhost/baremetalhost_controller.go
  pkg/controller/baremetalhost/baremetalhost_controller_test.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/dependencies.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
  pkg/provisioner/provisioner.go
Labels: approved, lgtm, ok-to-test, size/L

#611 ensure boot mode is set before introspection begins
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  pkg/apis/metal3/v1alpha1/baremetalhost_types_test.go
  pkg/controller/baremetalhost/baremetalhost_controller.go
  pkg/controller/baremetalhost/baremetalhost_controller_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
Labels: approved, lgtm, size/L
