Repository metal3-io/baremetal-operator, pull requests merged in 2020-10, with the labels that each got.

#662 Add basic golangci-lint target to replace "make lint"
  .golangci.yml
  Makefile
  cmd/get-hardware-details/main.go
  cmd/make-bm-worker/main.go
  controllers/metal3.io/baremetalhost_controller_test.go
  pkg/provisioner/ironic/capabilities_test.go
  pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ready_test.go
  pkg/provisioner/ironic/testserver/server.go
  pkg/provisioner/ironic/updateopts_test.go
Labels: approved, lgtm, ok-to-test, size/M

#664 always install our desired version of controller-gen
  Makefile
  hack/install-controller-gen.sh
Labels: approved, lgtm, size/M

#644 Split Ironic API and Conductor containers in run_local_ironic.sh
  ironic-deployment/ironic/ironic.yaml
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/M

#663 Remove operator-sdk leftovers
  .travis.yml
  Makefile
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  docs/dev-setup.md
  hack/markdownlint.sh
  hack/shellcheck.sh
Labels: approved, lgtm, size/S

#659 Bug 1859999: Expand API documentation
  docs/api.md
Labels: approved, lgtm, ok-to-test, size/XS

#668 Move from /deploy to /config
  config/basic-auth/default/credentials.yaml
  config/basic-auth/default/kustomization.yaml
  config/basic-auth/tls/credentials.yaml
  config/basic-auth/tls/kustomization.yaml
  config/tls/kustomization.yaml
  config/tls/tls_ca.yaml
  docs/deploying.md
  docs/dev-setup.md
  hack/ironic_ci.env
  tools/deploy.sh
Labels: approved, lgtm, size/L

#669 restore WATCH_NAMESPACE variable
  main.go
Labels: approved, lgtm, size/XS

#672 Render BMO deployment
  Makefile
  config/manager/manager.yaml
  config/render/deployment.yaml
Labels: approved, lgtm, size/XL

#674 Add capm3 specific configurations in config/ dir
  Makefile
  config/kustomization.yaml
  config/manager/manager.yaml
  config/namespace/kustomization.yaml
  config/namespace/namespace.yaml
  config/render/capm3.yaml
Labels: approved, lgtm, size/M

#675 Add missing ironic bmo configmap in config/default
  config/default/ironic.env
  config/default/kustomization.yaml
  config/manager/manager.yaml
  config/render/capm3.yaml
Labels: approved, size/M

#671 Fix tls certificate fetch path
  config/basic-auth/default/credentials.yaml
  config/basic-auth/default/kustomization.yaml
  config/basic-auth/tls/credentials.yaml
  config/basic-auth/tls/kustomization.yaml
  config/tls/kustomization.yaml
  config/tls/tls_ca.yaml
  tools/deploy.sh
Labels: size/S

#676 Fix kustomization path
  config/basic-auth/default/kustomization.yaml
  config/tls/kustomization.yaml
  tools/deploy.sh
Labels: approved, size/XS

#677 Fix tls kustomization path
  config/basic-auth/default/kustomization.yaml
  config/tls/kustomization.yaml
Labels: approved, size/XS

#679 Fix image name in manager + other small nits
  Makefile
  Tiltfile
  config/manager/manager.yaml
  config/render/capm3.yaml
  ironic-deployment/keepalived/kustomization.yaml
Labels: approved, size/S

#680 Add missing RBAC for secrets and events
  config/rbac/role.yaml
  config/render/capm3.yaml
  controllers/metal3.io/baremetalhost_controller.go
Labels: approved, lgtm, size/M

#649 start adding unit tests for Ironic.InspectHardware
  pkg/provisioner/ironic/inspecthardware_test.go
  pkg/provisioner/ironic/ironic_test.go
  pkg/provisioner/ironic/testserver/inspector.go
  pkg/provisioner/ironic/testserver/ironic.go
  pkg/provisioner/ironic/testserver/server.go
Labels: approved, lgtm, size/L

#678 Remove old deploy directory
  deploy/basic-auth/default/credentials.yaml
  deploy/basic-auth/default/kustomization.yaml
  deploy/basic-auth/tls/credentials.yaml
  deploy/basic-auth/tls/kustomization.yaml
  deploy/crds/kustomization.yaml
  deploy/crds/metal3.io_baremetalhosts_crd.yaml
  deploy/default/ironic_bmo_configmap.env
  deploy/default/kustomization.yaml
  deploy/default/kustomizeconfig.yaml
  deploy/ironic_ci.env
  deploy/namespace/kustomization.yaml
  deploy/namespace/namespace.yaml
  deploy/operator/bmo.yaml
  deploy/operator/kustomization.yaml
  deploy/rbac/kustomization.yaml
  deploy/rbac/role.yaml
  deploy/rbac/role_binding.yaml
  deploy/rbac/service_account.yaml
  deploy/role.yaml
  deploy/tls/kustomization.yaml
  deploy/tls/tls_ca.yaml
Labels: approved, lgtm, size/XXL

#657 Correct the description of HardwareDetails fields
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
Labels: approved, lgtm, size/M

#683 remove test dependency from docker build
  Makefile
Labels: approved, lgtm, size/XS

#682 📖 Update deploying document to reflect recent changes
  docs/deploying.md
Labels: approved, lgtm, size/M

#687 Fix path in install kustomize
  tools/install_kustomize.sh
Labels: approved, lgtm, size/XS

#686 Update golang to latest to match version across all repos
  .travis.yml
  Dockerfile
  Tiltfile
  go.mod
  hack/Dockerfile.golint
  hack/generate.sh
  hack/gofmt.sh
  hack/gomod.sh
  hack/govet.sh
  hack/unit.sh
Labels: approved, lgtm, size/S

#647 start adding unit tests for ironic.ValidateManagementAccess
  pkg/bmc/access.go
  pkg/bmc/ibmc.go
  pkg/bmc/idrac.go
  pkg/bmc/idrac_virtualmedia.go
  pkg/bmc/ilo4.go
  pkg/bmc/ilo5.go
  pkg/bmc/ipmi.go
  pkg/bmc/irmc.go
  pkg/bmc/redfish.go
  pkg/bmc/redfish_virtualmedia.go
  pkg/provisioner/ironic/findhost_test.go
  pkg/provisioner/ironic/ironic_test.go
  pkg/provisioner/ironic/testbmc/testbmc.go
  pkg/provisioner/ironic/testserver/ironic.go
  pkg/provisioner/ironic/updateopts_test.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: approved, lgtm, size/L

#684 Re-enable FAST_TRACK and set Online to true when rendering BMH CRs
  cmd/make-bm-worker/templates/templates.go
  cmd/make-bm-worker/templates/templates_test.go
  cmd/make-virt-host/main.go
  config/default/ironic.env
  config/render/capm3.yaml
  docs/dev-setup.md
  hack/ironic_ci.env
  ironic-deployment/default/ironic_bmo_configmap.env
  ironic-deployment/keepalived/ironic_bmo_configmap.env
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/S

#688 Add contoller-gen to go.mod
  config/crd/bases/metal3.io_baremetalhosts.yaml
  go.mod
  go.sum
  hack/install-controller-gen.sh
  tools.go
Labels: approved, lgtm, size/L

#691 Add kustomize tool to go.mod
  Makefile
  config/render/capm3.yaml
  go.mod
  go.sum
  tools.go
  tools/install_kustomize.sh
Labels: approved, lgtm, size/L

#653 Unit tests for ironic.{Adopt,PowerOn,PowerOff,Provision,Deprovision}
  controllers/metal3.io/host_config_data.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/adopt_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/power_test.go
  pkg/provisioner/ironic/provision_test.go
  pkg/provisioner/ironic/testserver/ironic.go
Labels: approved, lgtm, ok-to-test, size/XL

#685 make logger names more consistent
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/demo_test.go
  controllers/metal3.io/host_config_data_test.go
  controllers/metal3.io/host_state_machine_test.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/M

#693 Change kustomize path from tools/bin/ to bin/
  Tiltfile
  tools/deploy.sh
Labels: approved, lgtm, size/S

#694 Disable unnecessary Travis tests
  .travis.yml
Labels: approved, lgtm, size/XS

#673 start adding unit tests for Ironic.UpdateHardwareState
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/testserver/ironic.go
  pkg/provisioner/ironic/updatehardwarestate_test.go
Labels: approved, lgtm, size/L

#696 Add golangci-lint to go.mod
  Makefile
  go.mod
  go.sum
  hack/install-golangci-lint.sh
  tools.go
Labels: approved, lgtm, size/L

#695 add health check endpoint
  config/manager/manager.yaml
  config/render/capm3.yaml
  main.go
Labels: approved, lgtm, size/S

#388 Handle registration independently of provisioning state
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  docs/BaremetalHost_ProvisioningState.dot
  docs/BaremetalHost_ProvisioningState.png
  docs/api.md
Labels: approved, lgtm, size/L

#702 Add info about 'config/render/capm3.yaml in README
  README.md
Labels: approved, lgtm, size/S

#699 Remove main.go path in tilt-provider.json file
  tilt-provider.json
Labels: approved, lgtm, size/XS

#701 Add furkatgofurov7 in reviewers list
  OWNERS
Labels: approved, lgtm, size/XS

#704 Remove limits and requests from manager manifest
  config/manager/manager.yaml
  config/render/capm3.yaml
Labels: approved, lgtm, size/S

#706 Update local ironic documentation with TLS information
  docs/dev-setup.md
Labels: approved, lgtm, size/S

#700 Fix livenessProve for BMO
  config/manager/manager.yaml
  config/render/capm3.yaml
  main.go
Labels: approved, lgtm, size/M
