Repository metal3-io/baremetal-operator, pull requests merged in 2020-11, with the labels that each got.

#705 Handle different responses by method on MockServer
  pkg/provisioner/ironic/adopt_test.go
  pkg/provisioner/ironic/inspecthardware_test.go
  pkg/provisioner/ironic/power_test.go
  pkg/provisioner/ironic/provision_test.go
  pkg/provisioner/ironic/testserver/ironic.go
  pkg/provisioner/ironic/testserver/server.go
Labels: approved, lgtm, size/L

#712 cache the ironic api clients
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/M

#711 start adding unit tests for Ironic.Delete
  pkg/provisioner/ironic/delete_test.go
  pkg/provisioner/ironic/testserver/ironic.go
Labels: approved, lgtm, size/L

#689 Enable TLS between Ironic and MariaDB
  docs/deploying.md
  ironic-deployment/tls/default/kustomization.yaml
  ironic-deployment/tls/default/tls.yaml
  ironic-deployment/tls/keepalived/kustomization.yaml
  ironic-deployment/tls/keepalived/tls.yaml
  tools/deploy.sh
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/L

#719 Add log watch entry points
  ironic-deployment/ironic/ironic.yaml
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/M

#661 Remove provisioning CIDR from ironicendpoint VIP
  docs/deploying.md
  docs/dev-setup.md
  docs/ironic-endpoint-keepalived-configuration.md
  hack/ironic_ci.env
  ironic-deployment/keepalived/ironic_bmo_configmap.env
  resources/keepalived-docker/manage-keepalived.sh
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/XS

#729 Add remove local ironic script
  tools/remove_local_ironic.sh
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/S
