Repository metal3-io/baremetal-operator, pull requests merged in 2020-09, with the labels that each got.

#620 Change base image to distroless
  build/Dockerfile
Labels: approved, lgtm, size/S

#621 docs/dev-setup: fix error link
  docs/dev-setup.md
Labels: approved, lgtm, ok-to-test, size/XS

#622 reformat api documentation to make linking to field definitions easier
  docs/api.md
Labels: approved, lgtm, size/XL

#627 Add Tilt provider file for integration with CAPM3 Tilt setup
  .gitignore
  docs/dev-setup.md
  tilt-provider.json
Labels: approved, lgtm, size/S

#630 Update go dependencies
  deploy/crds/metal3.io_baremetalhosts_crd.yaml
  go.mod
  go.sum
  pkg/controller/baremetalhost/baremetalhost_controller_test.go
Labels: approved, lgtm, size/XL

#430 Re-enable Ironic Fast Track
  deploy/default/ironic_bmo_configmap.env
  deploy/ironic_ci.env
  ironic-deployment/default/ironic_bmo_configmap.env
  ironic-deployment/keepalived/ironic_bmo_configmap.env
Labels: approved, lgtm, size/XS

#397 Rename NeedsDeprovisioning() method
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  pkg/apis/metal3/v1alpha1/baremetalhost_types_test.go
  pkg/controller/baremetalhost/host_state_machine.go
  pkg/controller/baremetalhost/host_state_machine_test.go
Labels: approved, lgtm, size/L, ¯\_(ツ)_/¯

#619 allow mock ironic/inspector service to run without specifying a port
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
Labels: approved, lgtm, size/L

#632 Disable Ironic fasttrack
  deploy/default/ironic_bmo_configmap.env
  deploy/ironic_ci.env
  ironic-deployment/default/ironic_bmo_configmap.env
  ironic-deployment/keepalived/ironic_bmo_configmap.env
Labels: approved, lgtm, size/XS

#629 Make ironic environment variables configurable
  docs/dev-setup.md
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/M

#636 Handle StateAvailable when we see it
  pkg/controller/baremetalhost/host_state_machine.go
Labels: approved, lgtm, size/XS

#610 Always retry provisioning operations on failure (continue)
  deploy/crds/metal3.io_baremetalhosts_crd.yaml
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  pkg/apis/metal3/v1alpha1/baremetalhost_types_test.go
  pkg/controller/baremetalhost/action_result.go
  pkg/controller/baremetalhost/action_result_test.go
  pkg/controller/baremetalhost/baremetalhost_controller.go
  pkg/controller/baremetalhost/host_state_machine_test.go
Labels: approved, lgtm, size/L

#628 Add Tilt setup
  Makefile
  Tiltfile
  docs/dev-setup.md
  hack/kind_with_registry.sh
  tools/install_kustomize.sh
Labels: approved, lgtm, size/L

#595 Adding support for hardware type iLO
  docs/api.md
  pkg/bmc/access_test.go
  pkg/bmc/ilo4.go
  pkg/bmc/ilo5.go
Labels: approved, lgtm, ok-to-test, size/L

#641 Fix environment variables in Makefile
  Makefile
Labels: approved, lgtm, size/S

#623 more unit test work for ironic provisioner
  pkg/provisioner/ironic/capabilities_test.go
  pkg/provisioner/ironic/findhost_test.go
  pkg/provisioner/ironic/ironic_test.go
  pkg/provisioner/ironic/ready_test.go
  pkg/provisioner/ironic/testserver/inspector.go
  pkg/provisioner/ironic/testserver/ironic.go
  pkg/provisioner/ironic/testserver/server.go
  pkg/provisioner/ironic/updateopts_test.go
Labels: approved, lgtm, size/XXL

#645 ensure the boot mode is set in ironic before starting inspection
  pkg/controller/baremetalhost/host_state_machine.go
  pkg/controller/baremetalhost/host_state_machine_test.go
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/L

#646 Bring back missing dependencies
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#648 Add gomod script
  hack/gomod.sh
Labels: approved, lgtm, size/M
