Repository metal3-io/baremetal-operator, pull requests merged in 2020-08, with the labels that each got.

#601 Add support for http_basic auth for ironic and inspector
  cmd/get-hardware-details/main.go
  docs/ironic-authentication.md
  go.mod
  go.sum
  pkg/provisioner/ironic/clients/auth.go
  pkg/provisioner/ironic/clients/auth_test.go
  pkg/provisioner/ironic/clients/client.go
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/L

#615 Fix Keepalived container to stop cleanly
  resources/keepalived-docker/Dockerfile
  resources/keepalived-docker/manage-keepalived.sh
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/S

#616 Added encoding of credentials using base64
  docs/api.md
Labels: approved, lgtm, ok-to-test, size/S

#614 Always delete found host from Ironic on deletion
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/XS

#612 keep boot mode updated
  pkg/controller/baremetalhost/baremetalhost_controller.go
  pkg/controller/baremetalhost/host_state_machine.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
Labels: approved, lgtm, size/L
