Repository metal3-io/baremetal-operator, pull requests merged in 2020-06, with the labels that each got.

#495 root device hints
  deploy/crds/metal3.io_baremetalhosts_crd.yaml
  docs/api.md
  go.mod
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
  pkg/apis/metal3/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/baremetalhost/baremetalhost_controller.go
  pkg/controller/baremetalhost/baremetalhost_controller_test.go
  pkg/hardware/profile.go
  pkg/provisioner/ironic/devicehints/devicehints.go
  pkg/provisioner/ironic/devicehints/devicehints_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
Labels: approved, lgtm, size/XL

#544 add minimum validation for root device hint size
  deploy/crds/metal3.io_baremetalhosts_crd.yaml
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
Labels: approved, lgtm, size/XS

#546 remove infinite reconcile loop when fetching status annotation
  cmd/get-hardware-details/main.go
  pkg/controller/baremetalhost/baremetalhost_controller.go
  pkg/controller/baremetalhost/baremetalhost_controller_test.go
Labels: approved, lgtm, size/M

#548 🏃 Add kustomizeconfig for namespace
  deploy/default/kustomization.yaml
  deploy/default/kustomizeconfig.yaml
Labels: approved, lgtm, size/S

#549 support older ironic checksum expectations
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/M

#542 Update doc link and operator-sdk command
  docs/dev-setup.md
Labels: approved, lgtm, ok-to-test, size/XS, tide/merge-method-squash

#550 New BMH unhealthy annotation
  docs/api.md
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
Labels: approved, lgtm, size/S

#541 📖 Add deployment documentation for BMO and Ironic
  deploy/default/kustomization.yaml
  docs/configuration.md
  docs/deploying.md
Labels: approved, lgtm, size/L

#551 🏃 Change configMapGenerator behavior in kustomization and typo fixes
  deploy/default/kustomization.yaml
  docs/deploying.md
Labels: approved, lgtm, size/S

#536 Add tryChangeNodeProvisionState() method in ironic provisioner
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/S

#543 initialize reviewers list
  OWNERS
Labels: approved, lgtm, size/XS

#556 Add Dmitry Ukov to reviewers list
  OWNERS
Labels: do-not-merge/hold, needs-ok-to-test, size/XS

#557 Upgrade module to Golang 1.14, and tidy modules
  build/Dockerfile
  go.mod
  go.sum
  hack/Dockerfile.golint
  hack/Dockerfile.operator-sdk
Labels: approved, lgtm, size/S

#555 🏃 Add small changes to BMO and Ironic deployment documentation
  docs/deploying.md
Labels: approved, lgtm, size/S

#560 Fix: Delete ironic-endpoint-keepalived container also while deleting other ironic containers
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/XS

#561 Add kashifest in the reviewers list
  OWNERS
Labels: approved, lgtm, size/XS

#558 Round clock frequency to integer when setting HW details
  pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go
Labels: approved, lgtm, size/XS

#540 ⚠️ Remove old BMO & Ironic deployments
  deploy/bmo-capm3/README.md
  deploy/bmo-capm3/ironic_bmo_configmap.env
  deploy/bmo-capm3/kustomization.yaml
  deploy/ironic-keepalived-config/image_patch.yaml
  deploy/ironic-keepalived-config/ironic_bmo_configmap.env
  deploy/ironic-keepalived-config/kustomization.yaml
  deploy/ironic-outside-config/ironic_bmo_configmap.env
  deploy/ironic-outside-config/kustomization.yaml
  deploy/operator/ironic/kustomization.yaml
  deploy/operator/ironic/operator_ironic.yaml
  deploy/operator/ironic_keepalived/kustomization.yaml
  deploy/operator/ironic_keepalived/operator_ironic_keepalived.yaml
  deploy/operator/no_ironic/kustomization.yaml
  deploy/operator/no_ironic/operator.yaml
Labels: approved, lgtm, size/L

#559 Update Ironic Keepalived container documentation
  docs/ironic-endpoint-keepalived-configuration.md
Labels: approved, lgtm, size/M

#565 Fix SaveHostStatus infinite loop on update conflicts
  pkg/controller/baremetalhost/baremetalhost_controller.go
Labels: approved, lgtm, size/M

#553 Remove Unhealthy annotation changes
  docs/api.md
  pkg/apis/metal3/v1alpha1/baremetalhost_types.go
Labels: approved, lgtm, size/S
