Repository metal3-io/baremetal-operator, pull requests merged in 2021-12, with the labels that each got.

#1041 Support ilo4 virtual media
  docs/api.md
  pkg/ironic/bmc/access_test.go
  pkg/ironic/bmc/ilo4.go
Labels: size/M, lgtm, approved

#1028 Add UT for stringlist
  pkg/utils/stringlist_test.go
Labels: size/M, lgtm, approved, ok-to-test

#1033 irmc: change the return value of NeedsMAC() to true
  pkg/hardwareutils/bmc/access_test.go
  pkg/hardwareutils/bmc/irmc.go
Labels: size/XS, lgtm, approved, ok-to-test

#1048 Uplift to go1.17
  Dockerfile
  Tiltfile
  apis/go.mod
  apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  cmd/make-virt-host/main.go
  controllers/metal3.io/action_result.go
  go.mod
  hack/Dockerfile.golint
  hack/generate.sh
  hack/gofmt.sh
  hack/gomod.sh
  hack/tools/go.mod
  hack/tools/tools.go
  hack/unit.sh
  pkg/hardwareutils/go.mod
Labels: lgtm, approved, size/L

#1046 Fix kustomize binary path in Tiltfile
  Tiltfile
Labels: size/XS, lgtm, approved

#995 Change hfs controller to be level-triggered when handling bmh updates
  apis/metal3.io/v1alpha1/firmwareschema_types.go
  apis/metal3.io/v1alpha1/hostfirmwaresettings_types.go
  apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/metal3.io_hostfirmwaresettings.yaml
  config/render/capm3.yaml
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/hostfirmwaresettings_controller.go
  controllers/metal3.io/hostfirmwaresettings_test.go
  pkg/provisioner/ironic/ironic.go
Labels: lgtm, approved, size/L

#1044 Uplift mongo-driver@v1.5.1 & ulikunitz/xz@v0.5.8
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/M, lgtm, approved

#1047 Add an interface for the image builder to report a failure
  controllers/metal3.io/preprovisioningimage_controller.go
  pkg/imageprovider/default.go
  pkg/imageprovider/invalid.go
Labels: size/S, lgtm, approved

#1050 Remove BIOS config password related settings from schema
  controllers/metal3.io/hostfirmwaresettings_controller.go
Labels: size/XS, lgtm, approved

#991 Add validations for bmo resource name
  apis/go.mod
  apis/metal3.io/v1alpha1/baremetalhost_validation.go
  apis/metal3.io/v1alpha1/baremetalhost_validation_test.go
Labels: size/M, lgtm, approved

#1051 Handle HostFirmwareSettings non-numeric string set for Integer type
  apis/metal3.io/v1alpha1/firmwareschema_types.go
  controllers/metal3.io/hostfirmwaresettings_test.go
Labels: size/S, lgtm, approved

#1049 Remove reset_required from FirmwareSchema
  apis/metal3.io/v1alpha1/firmwareschema_types.go
  apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/metal3.io_firmwareschemas.yaml
  config/render/capm3.yaml
  pkg/provisioner/ironic/bios_test.go
  pkg/provisioner/ironic/ironic.go
Labels: size/S, lgtm, approved

#1054 Do not add secret finalizer while deleting a host
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
Labels: size/M, lgtm, approved

#1052 Use a separate mariadb-image instead of one in ironic-image
  ironic-deployment/ironic/ironic.yaml
  tools/run_local_ironic.sh
Labels: size/S, lgtm, approved

#1014 Add BMC subscription CRD and reconciler
  PROJECT
  apis/go.mod
  apis/metal3.io/v1alpha1/bmceventsubscription_types.go
  apis/metal3.io/v1alpha1/bmceventsubscription_validation.go
  apis/metal3.io/v1alpha1/bmceventsubscription_validation_test.go
  apis/metal3.io/v1alpha1/bmceventsubscription_webhook.go
  apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/metal3.io_bmceventsubscriptions.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_bmceventsubscriptions.yaml
  config/crd/patches/webhook_in_bmceventsubscriptions.yaml
  config/rbac/bmceventsubscription_editor_role.yaml
  config/rbac/bmceventsubscription_viewer_role.yaml
  config/rbac/role.yaml
  config/render/capm3.yaml
  config/webhook/manifests.yaml
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/bmceventsubscription_controller.go
  controllers/metal3.io/host_state_machine_test.go
  controllers/metal3.io/hostfirmwaresettings_test.go
  go.mod
  go.sum
  main.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
  pkg/provisioner/provisioner.go
Labels: size/XXL, lgtm, approved

#1015 Doc changes for HostFirmwareSettings and FirmwareSchema resources
  docs/api.md
Labels: lgtm, approved, size/L

#1032 update provisioning state info
  docs/api.md
Labels: size/XS, lgtm, approved, ok-to-test

#1039 make-bm-worker: add some options and fix some issues
  cmd/make-bm-worker/main.go
  cmd/make-bm-worker/templates/templates.go
  cmd/make-bm-worker/templates/templates_test.go
Labels: lgtm, approved, size/L, ok-to-test

#1056 Uplift ulikunitz/xz v0.5.8 [CVE-2020-16845]
  config/render/capm3.yaml
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, approved, size/L
