Repository metal3-io/baremetal-operator, pull requests merged in 2021-03, with the labels that each got.

#799 Bump the Golang version to 1.16
  .travis.yml
  Dockerfile
  Tiltfile
  go.mod
  go.sum
  hack/Dockerfile.golint
  hack/generate.sh
  hack/gofmt.sh
  hack/gomod.sh
  hack/govet.sh
  hack/unit.sh
Labels: approved, lgtm, size/M

#803 Make BMH HardwareDetails fields optional
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
Labels: approved, lgtm, size/L

#292 Support RAID configuration for baremetal server
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/prepare_test.go
  pkg/provisioner/ironic/raid.go
  pkg/provisioner/ironic/raid_test.go
  pkg/provisioner/ironic/testserver/ironic.go
Labels: approved, lgtm, size/XXL

#800 Development: account for unset GOPATH
  hack/install-controller-gen.sh
  hack/install-golangci-lint.sh
  tools/install_kustomize.sh
Labels: approved, lgtm, size/S

#796 Add inspect.metal3.io/hardwaredetails annotation
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  docs/inspectAnnotation.md
  docs/statusAnnotation.md
Labels: approved, lgtm, size/L

#806 update controller-runtime to v0.7
  config/rbac/leader_election_role.yaml
  config/render/capm3.yaml
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/controller_test.go
  controllers/metal3.io/demo_test.go
  go.mod
  go.sum
  main.go
  pkg/bmc/access_test.go
  pkg/bmc/credentials_test.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/empty/empty.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
Labels: approved, lgtm, ok-to-test, size/L

#812 Add fmuyassarov in the reviewers list
  OWNERS
Labels: approved, lgtm, size/XS

#815 add dmitry tantsur as approver
  OWNERS
Labels: approved, lgtm, size/XS

#805 Upgrade CRD & Webhook to v1
  config/certmanager/certificate.yaml
  config/crd/patches/cainjection_in_baremetalhosts.yaml
  config/crd/patches/webhook_in_baremetalhosts.yaml
  config/default/kustomization.yaml
  config/default/webhookcainjection_patch.yaml
Labels: approved, lgtm, size/S

#794 Use separate methods for setting update node options.
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, ok-to-test, size/L

#808 upgrade k8s/api to v0.2.1
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#633 Add idrac-redfish url type (continue)
  docs/api.md
  pkg/bmc/access_test.go
  pkg/bmc/redfish.go
Labels: approved, lgtm, size/M

#813 Use the correct version of tools (from go.mod)
  Makefile
  hack/install-controller-gen.sh
  hack/install-golangci-lint.sh
  tools/deploy.sh
  tools/install_kustomize.sh
Labels: approved, lgtm, size/L

#728 Apache webserver handles TLS on Ironic
  ironic-deployment/default/ironic_bmo_configmap.env
  ironic-deployment/ironic/ironic.yaml
  tools/deploy.sh
  tools/remove_local_ironic.sh
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/M

#822 Bug: fix missing Inspecting state
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/XS

#824 Decouple Unmanaged state from externallyProvisioned
  main.go
Labels: approved, lgtm, size/XS

#823 Fix some lint errors
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/testserver/ironic.go
Labels: approved, lgtm, size/S

#757 Review registration log traces for Provisioner
  controllers/metal3.io/baremetalhost_controller.go
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/S

#829 Change default of RAIDInterface
  pkg/bmc/access_test.go
  pkg/bmc/ibmc.go
  pkg/bmc/idrac.go
  pkg/bmc/ilo4.go
  pkg/bmc/ipmi.go
  pkg/bmc/redfish.go
  pkg/bmc/redfish_virtualmedia.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/testbmc/testbmc.go
Labels: approved, lgtm, size/M

#831 Add a unit test for unsupported secure boot
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: approved, lgtm, size/S

#820 Eliminate need for "empty" provisioner
  controllers/metal3.io/baremetalhost_controller.go
  main.go
  pkg/provisioner/empty/empty.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: approved, lgtm, size/L

#833 Pass go tests flags via env.
  Makefile
  hack/unit.sh
Labels: approved, lgtm, size/S

#797 Prepend the namespace to ironic nodenames to avoid conflicts
  config/manager/manager.yaml
  config/render/capm3.yaml
  main.go
  pkg/provisioner/ironic/delete_test.go
  pkg/provisioner/ironic/findhost_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/provisioncapacity_test.go
  pkg/provisioner/ironic/updatehardwarestate_test.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: approved, lgtm, ok-to-test, size/L

#830 Fix the bug that the inspector reverse proxy still runs even when Ironic TLS is disabled
  ironic-deployment/default/ironic_bmo_configmap.env
  ironic-deployment/ironic/ironic.yaml
  ironic-deployment/tls/default/tls.yaml
  ironic-deployment/tls/keepalived/tls.yaml
  tools/deploy.sh
Labels: approved, lgtm, size/M

#840 Don't immediately retry on Inspect fail
  pkg/provisioner/ironic/inspecthardware_test.go
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/M
