Repository metal3-io/baremetal-operator, pull requests merged in 2021-05, with the labels that each got.

#869 Revert "Add unit and lint test in travis"
  .travis.yml
  tools/deploy.sh
Labels: approved, lgtm, size/XS

#866 Fix some typos
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  pkg/provisioner/ironic/testserver/server.go
  pkg/provisioner/ironic/updatehardwarestate_test.go
Labels: approved, lgtm

#851 Define command for ironic-inspector run
  ironic-deployment/ironic/ironic.yaml
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/XS

#861 Point ironic-inspector to the ironic image in quay
  config/basic-auth/default/credentials_patch.yaml
  config/basic-auth/tls/credentials_patch.yaml
  ironic-deployment/ironic/ironic.yaml
  ironic-deployment/tls/default/tls.yaml
  ironic-deployment/tls/keepalived/tls.yaml
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/S

#864 Enable Client certificate authorization for Ironic TLS client.
  docs/configuration.md
  pkg/provisioner/ironic/clients/client.go
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/M

#817 Allocate Ironic port when node exists and has no port allocated.
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, ok-to-test, size/L

#858 Adding RAID Parameters in api.md
  docs/api.md
Labels: approved, lgtm, ok-to-test, size/M

#873 Revert: Point ironic-inspector to the ironic image in quay
  ironic-deployment/ironic/ironic.yaml
  ironic-deployment/tls/default/tls.yaml
  ironic-deployment/tls/keepalived/tls.yaml
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/S

#871 Run apis/ tests in make unit
  Makefile
Labels: approved, lgtm, ok-to-test, size/XS

#881 strip whitespace after decoding secret values
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  docs/api.md
Labels: approved, lgtm, size/M

#880 Fix error: missing the following IPMI credentials in node's driver_info: ['ipmi_address']
  pkg/bmc/access_test.go
  pkg/bmc/irmc.go
Labels: approved, lgtm, ok-to-test, size/S

#882 Do automated cleaning in Prepare state
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/prepare_test.go
Labels: approved, lgtm, size/L

#870 Document parameter to set boot iso source
  docs/dev-setup.md
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/XS

#889 Fix bug with re-inspection due to Node in "available" state
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/host_state_machine_test.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/inspecthardware_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/provisioner.go
Labels: approved, lgtm, size/M

#888 Correctly run controller-gen for new apis module
  Makefile
Labels: approved, lgtm, size/S

#854 Restart Ironic containers when certificates are changed
  ironic-deployment/ironic/ironic.yaml
  tools/deploy.sh
Labels: approved, lgtm, size/S

#894 fix comment
  apis/metal3.io/v1alpha1/baremetalhost_types.go
Labels: approved, lgtm, ok-to-test, size/XS

#859 Add cert-manager setup for TLS in ironic deployment.
  ironic-deployment/basic-auth/default/auth.yaml
  ironic-deployment/basic-auth/default/kustomization.yaml
  ironic-deployment/basic-auth/keepalived/auth.yaml
  ironic-deployment/basic-auth/keepalived/kustomization.yaml
  ironic-deployment/basic-auth/tls/default/auth.yaml
  ironic-deployment/basic-auth/tls/default/kustomization.yaml
  ironic-deployment/basic-auth/tls/keepalived/auth.yaml
  ironic-deployment/basic-auth/tls/keepalived/kustomization.yaml
  ironic-deployment/certmanager/certificate.yaml
  ironic-deployment/certmanager/kustomization.yaml
  ironic-deployment/default/kustomization.yaml
  ironic-deployment/ironic/ironic.yaml
  ironic-deployment/keepalived/keepalived_patch.yaml
  ironic-deployment/keepalived/kustomization.yaml
  ironic-deployment/tls/default/kustomization.yaml
  ironic-deployment/tls/default/tls.yaml
  ironic-deployment/tls/keepalived/kustomization.yaml
  ironic-deployment/tls/keepalived/tls.yaml
  pkg/provisioner/ironic/ironic.go
  tools/deploy.sh
  tools/run_local_ironic.sh
Labels: size/L

#886 Point ironic-inspector to the ironic image in quay
  ironic-deployment/ironic/ironic.yaml
  ironic-deployment/tls/default/tls.yaml
  ironic-deployment/tls/keepalived/tls.yaml
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/M
