Repository metal3-io/baremetal-operator, pull requests merged in 2021-02, with the labels that each got.

#782 Add "NET_RAW" to ironic-endpoint-keepalived
  ironic-deployment/keepalived/keepalived_patch.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#773 Add BuildTime to manager binary.
  Makefile
  main.go
  pkg/version/version.go
Labels: approved, lgtm, ok-to-test, size/S

#763 Add Preparing state to do manual clean
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/demo_test.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  docs/BaremetalHost_ProvisioningState.dot
  docs/BaremetalHost_ProvisioningState.png
  docs/baremetalhost-states.md
  pkg/provisioner/demo/demo.go
  pkg/provisioner/empty/empty.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/prepare_test.go
  pkg/provisioner/provisioner.go
Labels: approved, lgtm, ok-to-test, size/L

#777 Make operationHistory none-required field
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#783 Refactor capabilities parsing
  pkg/provisioner/ironic/capabilities_test.go
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/M

#785 Wait for inspection completion
  pkg/provisioner/ironic/inspecthardware_test.go
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/M

#788 Fix the CPU clock rate unit in the API description
  docs/api.md
Labels: approved, lgtm, ok-to-test, size/XS

#787 Add inspect.metal3.io=disabled annotation
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
Labels: approved, lgtm, size/M

#766 Bump controller-tools to v0.4.1
  Makefile
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
  go.mod
  go.sum
  hack/install-controller-gen.sh
Labels: approved, lgtm, ok-to-test, size/S

#786 Automatic setting of UEFI secure boot
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
  pkg/bmc/access.go
  pkg/bmc/ibmc.go
  pkg/bmc/idrac.go
  pkg/bmc/idrac_virtualmedia.go
  pkg/bmc/ilo4.go
  pkg/bmc/ilo5.go
  pkg/bmc/ipmi.go
  pkg/bmc/irmc.go
  pkg/bmc/redfish.go
  pkg/bmc/redfish_virtualmedia.go
  pkg/provisioner/ironic/capabilities_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/testbmc/testbmc.go
  pkg/provisioner/ironic/updateopts_test.go
Labels: approved, lgtm, size/L

#801 docs: clarifies power management for externally managed hosts
  docs/api.md
Labels: approved, lgtm, ok-to-test, size/XS

#795 Implement explicit reboot mode options
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/host_state_machine_test.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/empty/empty.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/power_test.go
  pkg/provisioner/provisioner.go
Labels: approved, lgtm, ok-to-test, size/L
