Repository metal3-io/baremetal-operator, pull requests merged in 2021-10, with the labels that each got.

#987 Fix non-existing fmt target usage
  Makefile
  hack/gofmt.sh
Labels: size/XS, lgtm, approved

#993 Add cert-manager installation in the dev-setup doc
  docs/dev-setup.md
Labels: size/S, lgtm, approved

#998 Rename ironic go module to correct path for go get can find
  cmd/get-hardware-details/main.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/host_state_machine_test.go
  go.mod
  pkg/ironic/LICENSE
  pkg/ironic/go.mod
  pkg/ironic/raid.go
  pkg/ironic/testbmc/testbmc.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/adopt_test.go
  pkg/provisioner/ironic/bios_test.go
  pkg/provisioner/ironic/configdrive_test.go
  pkg/provisioner/ironic/delete_test.go
  pkg/provisioner/ironic/factory.go
  pkg/provisioner/ironic/findhost_test.go
  pkg/provisioner/ironic/inspecthardware_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
  pkg/provisioner/ironic/power_test.go
  pkg/provisioner/ironic/prepare_test.go
  pkg/provisioner/ironic/provision_test.go
  pkg/provisioner/ironic/provisioncapacity_test.go
  pkg/provisioner/ironic/raid.go
  pkg/provisioner/ironic/ready_test.go
  pkg/provisioner/ironic/updatehardwarestate_test.go
  pkg/provisioner/ironic/updateopts_test.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
  pkg/provisioner/provisioner.go
Labels: lgtm, approved, size/L

#936 Add PreprovisioningImage API and integration
  PROJECT
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/preprovisioningimage_types.go
  apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/crd/bases/metal3.io_preprovisioningimages.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_preprovisioningimages.yaml
  config/crd/patches/webhook_in_preprovisioningimages.yaml
  config/rbac/preprovisioningimage_editor_role.yaml
  config/rbac/preprovisioningimage_viewer_role.yaml
  config/rbac/role.yaml
  config/render/capm3.yaml
  config/samples/metal3.io_v1alpha1_preprovisioningimage.yaml
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/host_config_data.go
  controllers/metal3.io/host_config_data_test.go
  controllers/metal3.io/host_state_machine_test.go
  controllers/metal3.io/hostfirmwaresettings_test.go
  controllers/metal3.io/metrics.go
  controllers/metal3.io/preprovisioningimage_controller.go
  main.go
  pkg/ironic/bmc/access.go
  pkg/ironic/bmc/ibmc.go
  pkg/ironic/bmc/idrac.go
  pkg/ironic/bmc/idrac_virtualmedia.go
  pkg/ironic/bmc/ilo4.go
  pkg/ironic/bmc/ilo5.go
  pkg/ironic/bmc/ipmi.go
  pkg/ironic/bmc/irmc.go
  pkg/ironic/bmc/redfish.go
  pkg/ironic/bmc/redfish_virtualmedia.go
  pkg/ironic/testbmc/testbmc.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/factory.go
  pkg/provisioner/ironic/factory_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/prepare_test.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
  pkg/provisioner/provisioner.go
Labels: size/XXL, lgtm, approved

#340 Rename Ready state to Available
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/demo_test.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  docs/BaremetalHost_ProvisioningState.dot
  docs/BaremetalHost_ProvisioningState.png
  docs/api.md
  docs/baremetalhost-states.md
  examples/demo-hosts.yaml
  pkg/provisioner/demo/demo.go
Labels: lgtm, approved, size/L, ok-to-test

#1004 gitignore: Get rid of rules not associated with the project
  .gitignore
Labels: size/M, lgtm, approved
