Repository metal3-io/baremetal-operator, pull requests merged in 2021-01, with the labels that each got.

#748 Allow BMC details to be omitted for Hosts in Unmanaged state
  main.go
  pkg/provisioner/empty/empty.go
Labels: approved, lgtm, ok-to-test, size/L

#756 Fix manager namespace in docs
  docs/dev-setup.md
Labels: approved, lgtm, size/XS

#741 remove convenience methods from BareMetalHost
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/baremetalhost_types_test.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/demo_test.go
  controllers/metal3.io/host_state_machine.go
Labels: approved, lgtm, size/L

#749 Do retries with backoff in ValidateManagementAccess, Inspect, and Deprovision
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/empty/empty.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/inspecthardware_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/provision_test.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
  pkg/provisioner/provisioner.go
Labels: approved, lgtm, size/L

#750 ironic provisioner de-duplicate image options
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/L

#764 Add andfasano to reviewers list
  OWNERS
Labels: approved, lgtm, size/XS

#761 Improve communications between controller and provisioner
  controllers/metal3.io/action_result.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  main.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/empty/empty.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/delete_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
  pkg/provisioner/ironic/power_test.go
  pkg/provisioner/ironic/provision_test.go
  pkg/provisioner/ironic/result.go
  pkg/provisioner/ironic/updatehardwarestate_test.go
  pkg/provisioner/ironic/updateopts_test.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
  pkg/provisioner/provisioner.go
Labels: approved, lgtm, size/XL

#768 Get correct image checksum in getImageUpdateOptsForNode()
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/XS

#771 Remove root_gb workaround
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/updateopts_test.go
Labels: approved, lgtm, size/M

#745 Fix issues with deprovisioning after an error/failover
  controllers/metal3.io/baremetalhost_controller.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/provision_test.go
Labels: approved, lgtm, size/M

#727 A typo in the comment for WithNodeStatesProvisionUpdate
  pkg/provisioner/ironic/testserver/ironic.go
Labels: approved, lgtm, ok-to-test, size/XS

#759 Add live-iso support
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
  docs/api.md
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
  pkg/provisioner/ironic/provision_test.go
  pkg/provisioner/ironic/updateopts_test.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: approved, lgtm, size/XL

#762 Force retry when adoption fails
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/host_state_machine_test.go
Labels: approved, lgtm, size/M

#770 Add test coverage of Spec vs Status Image
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: approved, lgtm, size/M

#774 Use errorType intead of errorMessage
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
Labels: approved, lgtm, size/S

#778 Add missing newline in console log
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, ok-to-test, size/XS

#772 Ironic: Don't adopt after clean failure during deprovisioning
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/provision_test.go
Labels: approved, lgtm, size/M

#776 Ask Ironic to include NodeUUID when querying ports
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/testserver/ironic.go
Labels: approved, lgtm, size/XS

#780 Fail registration when boot MAC conflicts
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: approved, lgtm, ok-to-test, size/S

#725 Limit the number of hosts simultaneously provisioned
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
  controllers/metal3.io/action_result.go
  controllers/metal3.io/action_result_test.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  controllers/metal3.io/metrics.go
  docs/configuration.md
  pkg/provisioner/demo/demo.go
  pkg/provisioner/empty/empty.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/provisioncapacity_test.go
  pkg/provisioner/ironic/testserver/ironic.go
  pkg/provisioner/ironic/testserver/server.go
  pkg/provisioner/provisioner.go
Labels: approved, lgtm, size/XL
