Repository metal3-io/baremetal-operator, pull requests merged in 2021-07, with the labels that each got.

#927 remove dhellmann from owners
  OWNERS
Labels: approved, lgtm, size/XS

#914 Eliminate global variables in ironic provisioner
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/demo_test.go
  controllers/metal3.io/host_state_machine_test.go
  main.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/clients/client.go
  pkg/provisioner/ironic/dependencies.go
  pkg/provisioner/ironic/factory.go
  pkg/provisioner/ironic/factory_test.go
  pkg/provisioner/ironic/init_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
  pkg/provisioner/ironic/provisioncapacity_test.go
  pkg/provisioner/ironic/updateopts_test.go
  pkg/provisioner/provisioner.go
Labels: approved, lgtm, size/XL

#902 Correctly deprovision nodes in DeployWait and Deploying
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/XS

#884 Custom deploy procedure
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  docs/configuration.md
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/clients/client.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
  pkg/provisioner/ironic/updateopts_test.go
  pkg/provisioner/provisioner.go
Labels: approved, lgtm, size/XL

#924 Add TLS check before generating the secret for ironic-cacert secret.
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/XS

#932 Custom deploy: fix insufficient condition
  controllers/metal3.io/host_state_machine.go
Labels: approved, lgtm, size/XS

#903 Cache only required secrets
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/host_config_data.go
  controllers/metal3.io/host_config_data_test.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/XXL

#928 BIOS Configurations for iDRAC
  docs/api.md
  pkg/bmc/idrac.go
Labels: approved, lgtm, ok-to-test, size/M, tide/merge-method-squash

#841 Better handling of power management errors
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/host_state_machine_test.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/errors.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/power_test.go
  pkg/provisioner/provisioner.go
Labels: approved, lgtm, size/L

#901 Add new CRDs for BIOS configuration
  PROJECT
  apis/go.sum
  apis/metal3.io/v1alpha1/firmwareschema_types.go
  apis/metal3.io/v1alpha1/hostfirmwaresettings_types.go
  apis/metal3.io/v1alpha1/hostfirmwaresettings_types_test.go
  apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/metal3.io_firmwareschemas.yaml
  config/crd/bases/metal3.io_hostfirmwaresettings.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_firmwareschemas.yaml
  config/crd/patches/cainjection_in_hostfirmwaresettings.yaml
  config/crd/patches/webhook_in_firmwareschemas.yaml
  config/crd/patches/webhook_in_hostfirmwaresettings.yaml
  config/rbac/firmwareschema_editor_role.yaml
  config/rbac/firmwareschema_viewer_role.yaml
  config/rbac/hostfirmwaresettings_editor_role.yaml
  config/rbac/hostfirmwaresettings_viewer_role.yaml
  config/render/capm3.yaml
  config/samples/metal3.io_v1alpha1_firmwareschema.yaml
  config/samples/metal3.io_v1alpha1_hostfirmwaresettings.yaml
Labels: approved, lgtm, ok-to-test, size/XXL

#939 Remove duplicate if statement
  pkg/bmc/irmc.go
Labels: approved, lgtm, size/XS

#934 Modify namespace prefix in ironic deployment to support TLS
  config/tls/kustomization.yaml
  ironic-deployment/basic-auth/default/auth.yaml
  ironic-deployment/basic-auth/default/kustomization.yaml
  ironic-deployment/basic-auth/keepalived/auth.yaml
  ironic-deployment/basic-auth/keepalived/kustomization.yaml
  ironic-deployment/basic-auth/tls/default/auth.yaml
  ironic-deployment/basic-auth/tls/default/kustomization.yaml
  ironic-deployment/basic-auth/tls/keepalived/auth.yaml
  ironic-deployment/basic-auth/tls/keepalived/kustomization.yaml
  ironic-deployment/certmanager/certificate.yaml
  ironic-deployment/default/kustomization.yaml
  ironic-deployment/ironic/ironic.yaml
  ironic-deployment/keepalived/keepalived_patch.yaml
  ironic-deployment/keepalived/kustomization.yaml
  ironic-deployment/tls/default/kustomization.yaml
  ironic-deployment/tls/default/tls.yaml
  ironic-deployment/tls/keepalived/kustomization.yaml
  ironic-deployment/tls/keepalived/tls.yaml
  tools/deploy.sh
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/M

#908 Avoid always do delete_configuration clean step
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/host_state_machine_test.go
  docs/api.md
  pkg/bmc/irmc.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/prepare_test.go
  pkg/provisioner/ironic/raid.go
  pkg/provisioner/ironic/raid_test.go
  pkg/provisioner/provisioner.go
Labels: approved, lgtm, size/XL

#917 upgrade k8s/api to v0.21.1 (in apis/go.mod) and controller-tools to v0.6.0
  Makefile
  apis/go.mod
  apis/go.sum
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/crd/bases/metal3.io_firmwareschemas.yaml
  config/crd/bases/metal3.io_hostfirmwaresettings.yaml
  config/render/capm3.yaml
  go.mod
  go.sum
Labels: approved, lgtm, size/XL
