Repository metal3-io/baremetal-operator, pull requests merged in 2021-04, with the labels that each got.

#784 Allow disable automated cleaning
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
  docs/api.md
  go.mod
  go.sum
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: approved, lgtm, size/L

#826 Handle hardwaredetails annotation value error
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
Labels: approved, lgtm, size/S

#842 Set bmh 'name' in metadata as hostname
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/XS

#607 Inspection API implementation
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  docs/BaremetalHost_ProvisioningState.dot
  docs/BaremetalHost_ProvisioningState.png
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/inspecthardware_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/provisioner.go
Labels: approved, lgtm, size/M

#821 Define vlan interfaces to be included in introspection report
  docs/dev-setup.md
  ironic-deployment/default/ironic_bmo_configmap.env
  tools/run_local_ironic.sh
Labels: approved, lgtm, ok-to-test, size/XS

#837 Stop passing entire BareMetalHost to Provisioner
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/baremetalhost_types_test.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/adopt_test.go
  pkg/provisioner/ironic/delete_test.go
  pkg/provisioner/ironic/errors.go
  pkg/provisioner/ironic/findhost_test.go
  pkg/provisioner/ironic/inspecthardware_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
  pkg/provisioner/ironic/power_test.go
  pkg/provisioner/ironic/prepare_test.go
  pkg/provisioner/ironic/provision_test.go
  pkg/provisioner/ironic/raid.go
  pkg/provisioner/ironic/updatehardwarestate_test.go
  pkg/provisioner/ironic/updateopts_test.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
  pkg/provisioner/provisioner.go
Labels: approved, lgtm, size/XXL

#846 dev env setup steps missed metal3 ns creation
  docs/dev-setup.md
Labels: approved, lgtm, ok-to-test, size/XS

#845 Always update image details
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/S

#847 Extend RAID configuration for iDRAC BMC type
  pkg/bmc/idrac.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#838 Fix error reporting when creating an host with invalid BMC url
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: approved, lgtm, size/M

#827 Add support for detached annotation
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  docs/api.md
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/delete_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/provisioner.go
Labels: approved, lgtm, size/L

#807 Use PROVISIONING_LIMIT also for deprovisioning.
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  controllers/metal3.io/metrics.go
  docs/configuration.md
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/provisioncapacity_test.go
  pkg/provisioner/provisioner.go
Labels: approved, lgtm, ok-to-test, size/L

#849 Fix adoption in ExternallyProvisioned state
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
Labels: lgtm, size/S

#825 Enable golint with golangci-lint
  .golangci.yml
  Makefile
  controllers/metal3.io/action_result.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/provisioner.go
Labels: approved, lgtm, size/S

#848 modify power_interface for irmc
  pkg/bmc/irmc.go
Labels: approved, lgtm, ok-to-test, size/XS

#857 Add go.mod for BMH api
  Dockerfile
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
Labels: approved, lgtm, size/XL

#852 Always lazily update Node options in Ironic
  pkg/provisioner/ironic/capabilities_test.go
  pkg/provisioner/ironic/delete_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/update_opts.go
  pkg/provisioner/ironic/updateopts_test.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: approved, lgtm, size/XXL

#862 Add unit and lint test in travis
  .travis.yml
Labels: approved, lgtm, size/XS

#860 Propagate IPA_BASEURI env var to local ironic containers
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/XS

#863 Fix travis lint test
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/update_opts.go
  pkg/provisioner/ironic/updateopts_test.go
Labels: size/S

#856 Remove govet script and test
  Makefile
  hack/govet.sh
Labels: approved, lgtm, size/S
