Repository metal3-io/baremetal-operator, pull requests merged in 2021-06, with the labels that each got.

#890 Document re-inspection API
  docs/inspectAnnotation.md
Labels: approved, lgtm, size/S

#850 Add disk type field to BMH HardwareDetails
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
  pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go
Labels: approved, lgtm, size/M

#891 Uplift kube-rbac-proxy to v0.8.0
  config/default/manager_auth_proxy_patch.yaml
  config/render/capm3.yaml
Labels: approved, lgtm, size/XS

#302 Extend BaremetalHost CRD to support BIOS configuration in baremetal server
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
  controllers/metal3.io/baremetalhost_controller.go
  pkg/bmc/access.go
  pkg/bmc/access_test.go
  pkg/bmc/ibmc.go
  pkg/bmc/idrac.go
  pkg/bmc/idrac_virtualmedia.go
  pkg/bmc/ilo4.go
  pkg/bmc/ilo5.go
  pkg/bmc/ipmi.go
  pkg/bmc/irmc.go
  pkg/bmc/redfish.go
  pkg/bmc/redfish_virtualmedia.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/testbmc/testbmc.go
  pkg/provisioner/provisioner.go
Labels: approved, lgtm, size/XL

#906 Increase the default $BMO_CONCURRENCY for scale
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/host_state_machine.go
  docs/configuration.md
Labels: approved, lgtm, size/S

#911 Disable raid feature for iRMC server
  pkg/bmc/irmc.go
  pkg/provisioner/ironic/prepare_test.go
Labels: approved, lgtm, size/XS

#885 Unify `kubectl apply -f` format
  docs/ironic-endpoint-keepalived-configuration.md
Labels: approved, lgtm, ok-to-test, size/XS

#892 Also run controller-gen on the controller directory to get rbac
  Makefile
Labels: approved, lgtm, size/XS

#907 Support deploy_iso in addition to deploy_kernel/ramdisk
  docs/configuration.md
  pkg/provisioner/ironic/init_test.go
  pkg/provisioner/ironic/ironic.go
  tools/run_local_ironic.sh
Labels: approved, lgtm, size/L

#913 Extend docs for "baremetalhost.metal3.io/detached" annotation
  docs/api.md
Labels: approved, lgtm, ok-to-test, size/XS

#916 Don't deprovision provisioned host due to error
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
Labels: approved, lgtm, size/M

#900 Fix configdrive handling
  pkg/provisioner/ironic/configdrive_test.go
  pkg/provisioner/ironic/ironic.go
Labels: approved, lgtm, size/L

#920 Adding BIOS Parameters in api.md
  docs/api.md
Labels: approved, lgtm, size/S

#922 Fix some typos in comments
  controllers/metal3.io/baremetalhost_controller.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/provisioner.go
Labels: approved, lgtm, ok-to-test, size/S

#853 baremetal: Add privLevel to bmc data
  docs/api.md
  pkg/bmc/access_test.go
  pkg/bmc/ipmi.go
Labels: approved, lgtm, size/M

#921 Use mock BMC for testing RAID
  pkg/provisioner/ironic/prepare_test.go
Labels: approved, lgtm, size/S

#918 Use recreate strategy for ironic deployment
  ironic-deployment/ironic/ironic.yaml
Labels: approved, lgtm, size/XS
