Repository metal3-io/baremetal-operator, pull requests merged in 2021-09, with the labels that each got.

#963 Add kashifest and fmuyassarov as approvers
  config/OWNERS
  ironic-deployment/OWNERS
  resources/keepalived-docker/OWNERS
  tools/OWNERS
Labels: size/S, lgtm, approved

#965 Enable detach annotation for ready nodes
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
Labels: size/S, lgtm, approved

#966 Allow writing 'null' for HardwareRAIDVolumes and SoftwareRAIDVolumes.
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
Labels: size/S, lgtm, approved, ok-to-test

#967 Fix comment for detached annotation and add StateAvailable
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  docs/api.md
Labels: size/S, lgtm, approved

#969 🌱 Remove deprecated ioutil usage
  pkg/provisioner/ironic/clients/auth.go
  pkg/provisioner/ironic/testserver/ironic.go
  pkg/provisioner/ironic/testserver/server.go
Labels: size/S, lgtm, approved

#972 📖 Update docs and add more context concerning new deployment folders
  docs/deploying.md
  docs/ironic-endpoint-keepalived-configuration.md
Labels: lgtm, approved, size/L

#970 🌱 Uplift go modules (under root/apis/hack folders)
  apis/go.mod
  apis/go.sum
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/crd/bases/metal3.io_firmwareschemas.yaml
  config/crd/bases/metal3.io_hostfirmwaresettings.yaml
  config/render/capm3.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, approved, size/L

#971 📖 Update CI status badges in Readme
  README.md
Labels: size/S, lgtm, approved

#968 Stop relying on -modfile to allow vendorization
  Makefile
  tools/deploy.sh
Labels: size/M, lgtm, approved

#935 Create a SecretManager type to manage Secrets
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/errors.go
  controllers/metal3.io/host_config_data.go
  controllers/metal3.io/host_config_data_test.go
  main.go
  pkg/secretutils/label.go
  pkg/secretutils/secret_manager.go
Labels: lgtm, approved, size/L

#933 Do not disable iDRAC Redfish vendor interfaces
  pkg/bmc/access_test.go
  pkg/bmc/idrac_virtualmedia.go
  pkg/bmc/redfish.go
Labels: size/S, lgtm, approved

#974 Add more context to node lookup logging
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: size/S, lgtm, approved

#986 Add @andfasano and @fmuyassarov as approvers
  OWNERS
Labels: size/XS, lgtm, approved

#982 Remove travis ci config file
  .travis.yml
Labels: lgtm, approved

#981 Avoid logging BMC password when creds change
  pkg/provisioner/ironic/update_opts.go
  pkg/provisioner/ironic/updateopts_test.go
Labels: size/M, lgtm, approved

#953 Honor DefaultDeployInterface value from Ironic config
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/updateopts_test.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: size/S, lgtm, approved

#944 Create namespace for ironic and ignore any errors
  tools/deploy.sh
Labels: size/XS, lgtm, approved, ok-to-test

#973 Add AGE column to BMH CRDs
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
Labels: size/XS, lgtm, approved

#945 Drop the duplicating logwatch
  ironic-deployment/ironic/ironic.yaml
  tools/run_local_ironic.sh
Labels: size/S, lgtm, approved

#985 Fix fallback for ironic drivers that don't support soft power off
  pkg/provisioner/ironic/errors.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/power_test.go
Labels: lgtm, approved, size/L

#988 Remove ironic-inspector-log-watch
  tools/remove_local_ironic.sh
Labels: size/XS, lgtm, approved
