Repository metal3-io/baremetal-operator, pull requests merged in 2021-08, with the labels that each got.

#942 Fix missing case of BuildRAIDCleanSteps
  pkg/provisioner/ironic/raid.go
  pkg/provisioner/ironic/raid_test.go
Labels: approved, lgtm, size/S

#937 Move tools modules under hack/tools
  Dockerfile
  Makefile
  go.mod
  go.sum
  hack/golint.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  tools/deploy.sh
Labels: approved, lgtm, size/XXL

#948 Don't use soon removed APIs
  config/crd/patches/cainjection_in_firmwareschemas.yaml
  config/crd/patches/cainjection_in_hostfirmwaresettings.yaml
  config/crd/patches/webhook_in_firmwareschemas.yaml
  config/crd/patches/webhook_in_hostfirmwaresettings.yaml
Labels: approved, lgtm, size/XS

#909 Always build a configdrive except for live ISO
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  pkg/provisioner/ironic/configdrive_test.go
  pkg/provisioner/ironic/ironic.go
Labels: size/M, lgtm, approved

#951 Add CommonName to Ironic and Mariadb certificates
  ironic-deployment/certmanager/certificate.yaml
Labels: size/XS, lgtm, approved

#955 Update rbac api version to v1
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/render/capm3.yaml
Labels: size/S, lgtm, approved

#946 Explicitly set node bios_interface
  go.mod
  go.sum
  pkg/bmc/access.go
  pkg/bmc/access_test.go
  pkg/bmc/ibmc.go
  pkg/bmc/idrac.go
  pkg/bmc/idrac_virtualmedia.go
  pkg/bmc/ilo4.go
  pkg/bmc/ilo5.go
  pkg/bmc/ipmi.go
  pkg/bmc/irmc.go
  pkg/bmc/redfish.go
  pkg/bmc/redfish_virtualmedia.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/prepare_test.go
  pkg/provisioner/ironic/testbmc/testbmc.go
Labels: size/M, lgtm, approved

#723 unittests: Add a mechanism for simulating a lost ironic db
  pkg/provisioner/ironic/testserver/ironic.go
  pkg/provisioner/ironic/testserver/ironic_test.go
Labels: lgtm, approved, size/L
