Repository metal3-io/baremetal-operator, pull requests merged in 2021-11, with the labels that each got.

#994 Add RequiresProvisioningNetwork check into AccessDetails
  pkg/ironic/bmc/access.go
  pkg/ironic/bmc/ibmc.go
  pkg/ironic/bmc/idrac.go
  pkg/ironic/bmc/idrac_virtualmedia.go
  pkg/ironic/bmc/ilo4.go
  pkg/ironic/bmc/ilo5.go
  pkg/ironic/bmc/ipmi.go
  pkg/ironic/bmc/irmc.go
  pkg/ironic/bmc/redfish.go
  pkg/ironic/bmc/redfish_virtualmedia.go
  pkg/ironic/testbmc/testbmc.go
  pkg/provisioner/ironic/prepare_test.go
Labels: size/M, lgtm, approved

#1007 Remove bmc package dependency on API
  pkg/ironic/bmc/access.go
  pkg/ironic/bmc/access_test.go
  pkg/ironic/bmc/credentials_test.go
  pkg/ironic/bmc/ibmc.go
  pkg/ironic/bmc/idrac.go
  pkg/ironic/bmc/idrac_virtualmedia.go
  pkg/ironic/bmc/ilo4.go
  pkg/ironic/bmc/ilo5.go
  pkg/ironic/bmc/ipmi.go
  pkg/ironic/bmc/irmc.go
  pkg/ironic/bmc/redfish.go
  pkg/ironic/bmc/redfish_virtualmedia.go
  pkg/ironic/go.mod
  pkg/ironic/testbmc/testbmc.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/prepare_test.go
Labels: size/M, lgtm, approved

#1020 📖 Update old branch name mention in docs
  docs/dev-setup.md
Labels: size/XS, lgtm, approved, ok-to-test

#1008 Use finalizer for BMC secret.
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/preprovisioningimage_controller.go
  pkg/secretutils/secret_manager.go
Labels: size/M, lgtm, approved

#975 Add readiness and liveness probes
  config/manager/manager.yaml
  config/render/capm3.yaml
  ironic-deployment/ironic/ironic.yaml
Labels: size/M, lgtm, approved

#1023 Fix outdated URL in run_local_ironic
  tools/run_local_ironic.sh
Labels: size/XS, lgtm, approved, ok-to-test

#1018 Add ironic package to mod Makefile target
  Makefile
Labels: size/XS, lgtm, approved

#1019 Use PreprovisioningImage to build PXE images
  apis/metal3.io/v1alpha1/preprovisioningimage_types.go
  apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/metal3.io_preprovisioningimages.yaml
  config/render/capm3.yaml
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/preprovisioningimage_controller.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: lgtm, approved, size/L

#1011 Uplift to kubebuilder v3
  .dockerignore
  PROJECT
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/groupversion_info.go
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_baremetalhosts.yaml
  config/crd/patches/webhook_in_baremetalhosts.yaml
  config/crd/patches/webhook_in_firmwareschemas.yaml
  config/crd/patches/webhook_in_hostfirmwaresettings.yaml
  config/crd/patches/webhook_in_preprovisioningimages.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/manager/controller_manager_config.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/render/capm3.yaml
  hack/manifestlint.sh
  hack/unit.sh
  main.go
Labels: lgtm, approved, size/L

#1030 :bug: Remove provisioning IP from ironic-dnsmasq checks
  ironic-deployment/ironic/ironic.yaml
Labels: size/XS, lgtm, approved

#1042 Add ardaguclu and bfournie to reviewers
  OWNERS
Labels: size/XS, lgtm, approved

#1037 Fixes CentOS build failure on CentOS master
  config/manager/manager.yaml
  config/render/capm3.yaml
  ironic-deployment/ironic/ironic.yaml
Labels: size/M, lgtm, approved

#990 Replace deprecated linter & fix lint issues
  .golangci.yml
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/hostfirmwaresettings_test.go
  pkg/ironic/bmc/access_test.go
  pkg/ironic/raid_test.go
  pkg/provisioner/ironic/provision_test.go
Labels: size/S, lgtm, approved

#1036 Make PreprovisioningImage controller more generic
  apis/metal3.io/v1alpha1/preprovisioningimage_types.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/preprovisioningimage_controller.go
  main.go
  pkg/imageprovider/default.go
  pkg/imageprovider/imageprovider.go
Labels: lgtm, approved, size/L

#1035 Remove stbenjam from OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#1031 Fix golint issue
  pkg/ironic/hardwaredetails/.hardwaredetails.go.swp
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
Labels: size/XS, lgtm, approved, ok-to-test
