Repository metal3-io/baremetal-operator, pull requests merged in 2022-11, with the labels that each got.

#1179 :seedling: Add SECURITY_CONTACTS file
  SECURITY_CONTACTS
Labels: size/S, lgtm, approved

#1178 Add Kashif Khan as approver
  OWNERS
Labels: size/XS, lgtm, approved

#1183 Run make fmt to fix issues
  apis/metal3.io/v1alpha1/groupversion_info.go
  pkg/provisioner/ironic/testserver/ironic.go
Labels: size/S, lgtm, approved

#1186 🌱 Dockerfile: use apt-get instead of apt
  resources/keepalived-docker/Dockerfile
Labels: size/S, lgtm, approved

#1172 🌱 Ironic-deployment: Use kustomize components
  .gitignore
  Makefile
  docs/deploying.md
  ironic-deployment/README.md
  ironic-deployment/base/ironic.yaml
  ironic-deployment/base/kustomization.yaml
  ironic-deployment/basic-auth/default/auth.yaml
  ironic-deployment/basic-auth/ironic-rpc-auth-config-tpl
  ironic-deployment/basic-auth/keepalived/auth.yaml
  ironic-deployment/basic-auth/keepalived/kustomization.yaml
  ironic-deployment/basic-auth/tls/default/kustomization.yaml
  ironic-deployment/basic-auth/tls/keepalived/auth.yaml
  ironic-deployment/basic-auth/tls/keepalived/kustomization.yaml
  ironic-deployment/certmanager/kustomization.yaml
  ironic-deployment/components/basic-auth/auth.yaml
  ironic-deployment/components/basic-auth/ironic-auth-config-tpl
  ironic-deployment/components/basic-auth/ironic-inspector-auth-config-tpl
  ironic-deployment/components/basic-auth/kustomization.yaml
  ironic-deployment/components/keepalived/ironic_bmo_configmap.env
  ironic-deployment/components/keepalived/keepalived_patch.yaml
  ironic-deployment/components/keepalived/kustomization.yaml
  ironic-deployment/components/tls/certificate.yaml
  ironic-deployment/components/tls/kustomization.yaml
  ironic-deployment/components/tls/kustomizeconfig.yaml
  ironic-deployment/components/tls/tls.yaml
  ironic-deployment/default/kustomization.yaml
  ironic-deployment/keepalived/kustomization.yaml
  ironic-deployment/overlays/basic-auth_tls/basic-auth_tls.yaml
  ironic-deployment/overlays/basic-auth_tls/kustomization.yaml
  ironic-deployment/overlays/basic-auth_tls_keepalived/kustomization.yaml
  ironic-deployment/tls/default/kustomization.yaml
  ironic-deployment/tls/keepalived/kustomization.yaml
  ironic-deployment/tls/keepalived/tls.yaml
  tools/deploy.sh
  tools/run_local_ironic.sh
Labels: size/XL, lgtm, approved
