Repository metal3-io/baremetal-operator, pull requests merged in 2022-05, with the labels that each got.

#1117 Uplift go modules to latest release and controller tools to v0.8.0
  Makefile
  apis/go.mod
  apis/go.sum
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/crd/bases/metal3.io_bmceventsubscriptions.yaml
  config/crd/bases/metal3.io_firmwareschemas.yaml
  config/crd/bases/metal3.io_hostfirmwaresettings.yaml
  config/crd/bases/metal3.io_preprovisioningimages.yaml
  config/rbac/role.yaml
  config/render/capm3.yaml
  config/webhook/manifests.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/provisioner/ironic/update_opts.go
  pkg/provisioner/ironic/updateopts_test.go
Labels: size/XXL, lgtm, approved

#1118 Uplift kustomize to v4 to remove go-getter dependency
  Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: lgtm, approved, size/L

#1068 Check if bmc hostname follows DNS Standard
  pkg/hardwareutils/bmc/access.go
  pkg/hardwareutils/bmc/access_test.go
Labels: size/M, lgtm, approved

#1099 HardwareData custom resource for host inspection data
  PROJECT
  apis/metal3.io/v1alpha1/hardwaredata_types.go
  apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/metal3.io_hardwaredata.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_hardwaredata.yaml
  config/crd/patches/webhook_in_hardwaredata.yaml
  config/rbac/hardwaredata_editor_role.yaml
  config/rbac/hardwaredata_viewer_role.yaml
  config/rbac/role.yaml
  config/render/capm3.yaml
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/host_state_machine_test.go
Labels: size/XL, lgtm, approved
