Repository metal3-io/baremetal-operator, pull requests merged in 2022-06, with the labels that each got.

#1103 Add kubesec to BMO
  .github/workflows/kubesec.yml
  template/sarif.tpl
Labels: lgtm, approved, size/L

#1127 Get rid of a separate state for profile matching
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  docs/BaremetalHost_ProvisioningState.dot
  docs/BaremetalHost_ProvisioningState.png
  docs/baremetalhost-states.md
Labels: size/M, lgtm, approved

#1125 📖 Update outdated BaremetaHost state diagram
  docs/BaremetalHost_ProvisioningState.dot
  docs/BaremetalHost_ProvisioningState.png
Labels: size/XS, lgtm, approved

#1123 Uplift to gopkg.in/yaml to v3.0.0
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/S, lgtm, approved

#1126 Get rid of envsubst for nameprefix
  ironic-deployment/basic-auth/default/auth.yaml
  ironic-deployment/basic-auth/default/kustomization.yaml
  ironic-deployment/basic-auth/keepalived/auth.yaml
  ironic-deployment/basic-auth/keepalived/kustomization.yaml
  ironic-deployment/basic-auth/tls/default/auth.yaml
  ironic-deployment/basic-auth/tls/default/kustomization.yaml
  ironic-deployment/basic-auth/tls/keepalived/auth.yaml
  ironic-deployment/basic-auth/tls/keepalived/kustomization.yaml
  ironic-deployment/certmanager/certificate.yaml
  ironic-deployment/default/kustomization.yaml
  ironic-deployment/ironic/ironic.yaml
  ironic-deployment/keepalived/keepalived_patch.yaml
  ironic-deployment/keepalived/kustomization.yaml
  ironic-deployment/tls/default/kustomization.yaml
  ironic-deployment/tls/default/tls.yaml
  ironic-deployment/tls/keepalived/kustomization.yaml
  ironic-deployment/tls/keepalived/tls.yaml
  tools/deploy.sh
Labels: size/M, lgtm, approved

#1135 Stop treating missing network as fatal error
  controllers/metal3.io/host_config_data.go
Labels: size/S, lgtm, approved

#1138 Add zhouhao3 to reviewers
  OWNERS
Labels: size/XS, lgtm, approved

#1139 Don't require pre-provisioning image for live ISO provisioning
  pkg/provisioner/ironic/ironic.go
Labels: size/S, lgtm, approved
