Repository metal3-io/baremetal-operator, pull requests merged in 2022-03, with the labels that each got.

#1083 Use deep copy/equal for host root device hints
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
Labels: lgtm, approved, size/L

#1092 Copy labels from BaremetalHost to PreprovisioningImage
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
Labels: size/S, lgtm, approved

#1091 Switch the deployment to use a single ironic process
  docs/deploying.md
  ironic-deployment/basic-auth/default/auth.yaml
  ironic-deployment/basic-auth/default/kustomization.yaml
  ironic-deployment/basic-auth/keepalived/auth.yaml
  ironic-deployment/basic-auth/keepalived/kustomization.yaml
  ironic-deployment/basic-auth/tls/default/auth.yaml
  ironic-deployment/basic-auth/tls/default/kustomization.yaml
  ironic-deployment/basic-auth/tls/keepalived/auth.yaml
  ironic-deployment/basic-auth/tls/keepalived/kustomization.yaml
  ironic-deployment/default/ironic_bmo_configmap.env
  ironic-deployment/ironic/ironic.yaml
  ironic-deployment/keepalived/ironic_bmo_configmap.env
  ironic-deployment/tls/default/tls.yaml
  ironic-deployment/tls/keepalived/tls.yaml
  tools/deploy.sh
  tools/run_local_ironic.sh
Labels: lgtm, approved, size/L

#1089 imageprovider: an explicit state when an image is not ready
  controllers/metal3.io/preprovisioningimage_controller.go
  pkg/imageprovider/invalid.go
Labels: size/S, lgtm, approved

#1080 Only update the HFS status on changes
  controllers/metal3.io/hostfirmwaresettings_controller.go
  controllers/metal3.io/hostfirmwaresettings_test.go
Labels: lgtm, approved, size/L

#1094 Expose CheckRAIDInterface from the RAID module
  pkg/hardwareutils/bmc/access_test.go
  pkg/provisioner/ironic/raid.go
  pkg/provisioner/ironic/raid_test.go
Labels: size/M, lgtm, approved

#1088 Set maintenance reason when turning maintenance on
  pkg/provisioner/ironic/ironic.go
Labels: size/S, lgtm, approved

#1093 Clarify documentation on BMC formats
  docs/api.md
  hack/markdownlint.sh
Labels: size/M, lgtm, approved

#1097 Remove amd64 and linux to ensure multiarch container build
  Dockerfile
  Tiltfile
Labels: size/XS, lgtm, approved, ok-to-test

#1096 Fix NAMEPREFIX default value
  tools/deploy.sh
Labels: size/XS, lgtm, approved
