Repository metal3-io/baremetal-operator, pull requests merged in 2022-10, with the labels that each got.

#1169 run_local_ironic.sh: add proxy setting
  tools/run_local_ironic.sh
Labels: size/XS, lgtm, approved

#1173 Exclude hosts with virtual media from PROVISIONING_LIMIT
  docs/configuration.md
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/provisioncapacity_test.go
Labels: size/M, lgtm, approved

#1174 🌱 Bump golang to v1.18
  .github/workflows/release.yaml
  Dockerfile
  Tiltfile
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/Dockerfile.golint
  hack/generate.sh
  hack/gofmt.sh
  hack/gomod.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/unit.sh
  pkg/hardwareutils/go.mod
Labels: lgtm, approved, size/L
