Repository metal3-io/baremetal-operator, pull requests merged in 2022-09, with the labels that each got.

#1165 🌱 Update versioning to match new package release versions
  apis/go.mod
  go.mod
Labels: size/XS, lgtm, approved, ok-to-test

#1162 Set external_http_url on the node when BMC is IPv6
  docs/configuration.md
  pkg/provisioner/ironic/factory.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: lgtm, approved, size/L

#1149 🌱 Uplift go modules: k8s.io/* to v0.24.2, CRT to v0.12.3, controller tools to v0.9.1 and golangci-lint to v1.47.1
  apis/go.mod
  apis/go.sum
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/crd/bases/metal3.io_bmceventsubscriptions.yaml
  config/crd/bases/metal3.io_firmwareschemas.yaml
  config/crd/bases/metal3.io_hardwaredata.yaml
  config/crd/bases/metal3.io_hostfirmwaresettings.yaml
  config/crd/bases/metal3.io_preprovisioningimages.yaml
  config/render/capm3.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/XL, lgtm, approved

#1166 📖 Add issue and PR templates to the repository
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  hack/markdownlint.sh
Labels: size/M, lgtm, approved

#1168 run_local_ironic.sh: make HTTP_PORT customizable
  tools/run_local_ironic.sh
Labels: size/XS, lgtm, approved, ok-to-test

#1164 Delete controller flag for baremetalhost for secret
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/preprovisioningimage_controller.go
  pkg/secretutils/secret_manager.go
Labels: size/M, lgtm, approved
