Repository metal3-io/baremetal-operator, pull requests merged in 2022-04, with the labels that each got.

#1102 Fix make target for setting Ironic image
  Makefile
Labels: size/XS, lgtm, approved

#1100 Check for empty HFS status settings
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/hostfirmwaresettings_controller.go
Labels: size/M, lgtm, approved, ok-to-test

#1104 Add NET_RAW capability for dnsmasq
  ironic-deployment/ironic/ironic.yaml
Labels: size/XS, lgtm, approved

#1108 docs/api: Add iRMC default port info
  docs/api.md
Labels: size/XS, lgtm, approved

#1115 Add Riccardo to reviewers
  OWNERS
Labels: size/XS, lgtm, approved

#1116 Revert "Set maintenance reason when turning maintenance on"
  pkg/provisioner/ironic/ironic.go
Labels: size/S, lgtm, approved

#1109 Allow image provider to override kernel and add kernel params
  apis/metal3.io/v1alpha1/preprovisioningimage_types.go
  config/crd/bases/metal3.io_preprovisioningimages.yaml
  config/render/capm3.yaml
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/preprovisioningimage_controller.go
  pkg/imageprovider/default.go
  pkg/imageprovider/imageprovider.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
  pkg/provisioner/provisioner.go
Labels: lgtm, approved, size/L

#1106 Set minReadySeconds for BMO and Ironic
  config/manager/manager.yaml
  config/render/capm3.yaml
  ironic-deployment/ironic/ironic.yaml
Labels: size/XS, lgtm, approved
