Repository metal3-io/baremetal-operator, pull requests merged in 2022-12, with the labels that each got.

#1189 🐛 Uplift to go.etcd.io/etcd/v3
  go.mod
  go.sum
  pkg/provisioner/ironic/clients/client.go
Labels: size/S, lgtm, approved

#1188 🌱 Fix mac address for demo and fixture provisioners
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
Labels: size/XS, lgtm, approved

#1192 🌱markdown: pin mdl to 0.12 and fix complaints
  docs/api.md
  hack/markdownlint.sh
Labels: lgtm, approved, size/L

#1191 🐛 Fix endless requeue of HostFirmwareSettings
  controllers/metal3.io/hostfirmwaresettings_controller.go
Labels: size/XS, lgtm, approved

#1171 🌱 Bump golang to v1.19 and other go module dependencies and fix golint test
  Dockerfile
  Tiltfile
  apis/go.mod
  apis/go.sum
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/crd/bases/metal3.io_bmceventsubscriptions.yaml
  config/crd/bases/metal3.io_firmwareschemas.yaml
  config/crd/bases/metal3.io_hardwaredata.yaml
  config/crd/bases/metal3.io_hostfirmwaresettings.yaml
  config/crd/bases/metal3.io_preprovisioningimages.yaml
  config/render/capm3.yaml
  go.mod
  go.sum
  hack/Dockerfile.golint
  hack/generate.sh
  hack/gofmt.sh
  hack/golint.sh
  hack/gomod.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/unit.sh
  pkg/hardwareutils/go.mod
Labels: size/XXL, lgtm, approved

#1170 📖 Add detail guidelines for contributing guide including release and versioning process
  CONTRIBUTING.md
Labels: lgtm, approved, size/L

#1193 🌱 Bump golang 1.19 in release.yml
  .github/workflows/release.yaml
Labels: size/XS, lgtm, approved

#1194 🌱 Add Lennart Jern as a reviewer
  OWNERS
Labels: size/XS, lgtm, approved

#1195 🌱 shellcheck: pin to 0.9.0
  hack/shellcheck.sh
Labels: size/XS, lgtm, approved

#1197 🐛 uplift x/net to 0.4.0
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/M, lgtm, approved

#1198 :bug: docs: Remove erroneous state transition
  docs/BaremetalHost_ProvisioningState.dot
  docs/BaremetalHost_ProvisioningState.png
Labels: size/XS, lgtm, approved
