Repository metal3-io/baremetal-operator, pull requests merged in 2023-05, with the labels that each got.

#1267 🌱 pin distroless to static:nonroot with sha digest
  Dockerfile
Labels: size/XS, lgtm, approved

#1268 ✨ Add flags for configuring rate limits
  .gitignore
  main.go
Labels: size/S, lgtm, approved

#1266 📖 update releasing.md with links to main process
  docs/releasing.md
Labels: size/S, lgtm, approved

#1264 :sparkles: Support /dev/disk/by-path root device hints
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/baremetalhost_validation.go
  apis/metal3.io/v1alpha1/baremetalhost_validation_test.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
  pkg/provisioner/ironic/devicehints/devicehints.go
  pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go
Labels: lgtm, approved, size/L

#1272 :seedling: bump golang image from 1.19.6 to 1.19.9
  Dockerfile
Labels: size/XS, lgtm, approved

#1271 🐛 Do not try to update images for nodes in transient states
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: size/S, lgtm, approved

#1259 :bug: Don't check for ironic capacity in 'deleting' state
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
Labels: size/S, lgtm, approved

#1275 🌱 Reduce the preprovisioning image retry delay
  controllers/metal3.io/baremetalhost_controller.go
Labels: size/XS, lgtm, approved

#1280 Revert "🌱 Reduce the preprovisioning image retry delay"
  controllers/metal3.io/baremetalhost_controller.go
Labels: size/XS, lgtm, approved

#1279 Simplify dependencies of the apis module
  apis/go.mod
  apis/go.sum
  apis/metal3.io/v1alpha1/baremetalhost_webhook.go
  apis/metal3.io/v1alpha1/bmceventsubscription_webhook.go
  main.go
Labels: size/XL, lgtm, approved

#1278 Move hardware profile code to the api module
  apis/metal3.io/v1alpha1/profile/profile.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/host_state_machine_test.go
  pkg/provisioner/ironic/updateopts_test.go
  pkg/provisioner/provisioner.go
Labels: size/M, lgtm, approved
