Repository metal3-io/baremetal-operator, pull requests merged in 2023-03, with the labels that each got.

#1232 🌱 remove old unnecessary OWNERS files
  config/OWNERS
  ironic-deployment/OWNERS
  resources/keepalived-docker/OWNERS
  tools/OWNERS
Labels: size/S, lgtm, approved

#1230 :seedling: Delay deprovision/delete when multiple finalizers exist
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
Labels: size/M, lgtm, approved, ok-to-test

#1234 🐛 Do not reconcile HostFirmwareSettings for detached hosts
  controllers/metal3.io/hostfirmwaresettings_controller.go
Labels: size/S, lgtm, approved

#1231 :warning: run BMO ironic deployment as non-root
  ironic-deployment/base/ironic.yaml
  ironic-deployment/components/keepalived/keepalived_patch.yaml
  resources/keepalived-docker/Dockerfile
  resources/keepalived-docker/configure-nonroot.sh
  resources/keepalived-docker/manage-keepalived.sh
Labels: lgtm, approved, size/L

#1239 🐛 Revert "run BMO deployment as non-root"
  ironic-deployment/base/ironic.yaml
  ironic-deployment/components/keepalived/keepalived_patch.yaml
  resources/keepalived-docker/Dockerfile
  resources/keepalived-docker/configure-nonroot.sh
  resources/keepalived-docker/manage-keepalived.sh
Labels: lgtm, approved, size/L

#1236 :sparkles: Delay delete of detached hosts based on annotation metadata
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  controllers/metal3.io/metrics.go
Labels: lgtm, approved, size/L, ok-to-test
