Repository metal3-io/baremetal-operator, pull requests merged in 2023-06, with the labels that each got.

#1281 🌱 Remove explicit version when importing v1alpha1
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/bmceventsubscription_controller.go
  controllers/metal3.io/controller_test.go
  controllers/metal3.io/demo_test.go
  controllers/metal3.io/host_config_data.go
  controllers/metal3.io/host_config_data_test.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  controllers/metal3.io/hostfirmwaresettings_controller.go
  controllers/metal3.io/hostfirmwaresettings_test.go
  controllers/metal3.io/metrics.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/bios_test.go
  pkg/provisioner/ironic/capabilities_test.go
  pkg/provisioner/ironic/devicehints/devicehints.go
  pkg/provisioner/ironic/devicehints/devicehints_test.go
  pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go
  pkg/provisioner/ironic/hardwaredetails/hardwaredetails_test.go
  pkg/provisioner/ironic/inspecthardware_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
  pkg/provisioner/ironic/power_test.go
  pkg/provisioner/ironic/prepare_test.go
  pkg/provisioner/ironic/raid.go
  pkg/provisioner/ironic/raid_test.go
  pkg/provisioner/ironic/updateopts_test.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
  pkg/provisioner/provisioner.go
  pkg/secretutils/secret_manager.go
Labels: size/XXL, lgtm, approved

#1285 🌱 update kubeconform to v0.6.2
  hack/manifestlint.sh
Labels: size/XS, lgtm, approved

#1276 ⚠️ bump core kubernetes libraries
  apis/go.mod
  apis/go.sum
  apis/metal3.io/v1alpha1/baremetalhost_webhook.go
  apis/metal3.io/v1alpha1/baremetalhost_webhook_test.go
  apis/metal3.io/v1alpha1/bmceventsubscription_webhook.go
  apis/metal3.io/v1alpha1/bmceventsubscription_webhook_test.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/bmceventsubscription_controller.go
  controllers/metal3.io/demo_test.go
  controllers/metal3.io/host_state_machine_test.go
  controllers/metal3.io/hostfirmwaresettings_test.go
  go.mod
  go.sum
  main.go
  pkg/secretutils/label.go
Labels: size/XL, lgtm, approved, ok-to-test

#1286 🐛 fix distroless:nonroot pinning
  Dockerfile
Labels: size/XS, lgtm, approved

#1287 🌱 Add dependabot workflow and configuration
  .github/dependabot.yml
  .github/workflows/dependabot.yml
  Makefile
Labels: lgtm, approved, size/L

#1299 Revert ":seedling: Bump github.com/golangci/golangci-lint in /hack/tools"
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, approved, size/L

#1297 🌱 Stop using Extra when building hardware inventory
  go.mod
  go.sum
  pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go
  pkg/provisioner/ironic/hardwaredetails/hardwaredetails_test.go
Labels: lgtm, approved, size/L

#1298 📖 update releasing.md with release branches
  CONTRIBUTING.md
  docs/releasing.md
Labels: lgtm, approved, size/L

#1305 ⚠️ Change iBMC to use iPXE instead of PXE
  pkg/hardwareutils/bmc/access_test.go
  pkg/hardwareutils/bmc/ibmc.go
Labels: size/XS, lgtm, approved
