Repository metal3-io/baremetal-operator, pull requests merged in 2023-10, with the labels that each got.

#1388 📖 Add test trigger description for diffrerent branches in README
  README.md
Labels: size/S, lgtm, approved

#1396 🌱 bump x/net to 0.17.0
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/M, lgtm, approved

#1382 🌱 Add e2e external inspection test
  .gitignore
  hack/ci-e2e.sh
  hack/clean-e2e.sh
  test/e2e/common.go
  test/e2e/config/fixture.yaml
  test/e2e/config/ironic.yaml
  test/e2e/external_inspection_test.go
  test/e2e/inspection_test.go
  test/go.mod
  test/go.sum
Labels: lgtm, approved, size/L

#1381 ⚠️ Add "empty" profile and officially deprecate hardware profiles
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/profile/profile.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
Labels: size/S, lgtm, approved

#1398 🌱 Bump golang version to v1.20.10 on release-0.4
  Dockerfile
  Makefile
Labels: size/XS, lgtm, approved

#1356 :bug: Prevent hosts from getting into infinite power-off loops
  controllers/metal3.io/host_state_machine.go
  docs/BaremetalHost_ProvisioningState.dot
  docs/BaremetalHost_ProvisioningState.png
Labels: size/S, lgtm, approved

#1380 :sparkles: Pass preprovisioningNetworkData to Ironic
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/host_config_data.go
  controllers/metal3.io/host_config_data_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/provisioner.go
Labels: lgtm, approved, size/L

#1404 🌱 Adding go work files in gitignore
  .gitignore
Labels: size/XS, lgtm, approved

#1405 🌱 Fixing ensure-go script to allow go versions greater than MINIMUM_GO_VERSION
  hack/e2e/ensure_go.sh
Labels: size/XS, lgtm, approved

#1403 🌱 Implement BMH provisioning E2E test
  .gitignore
  Makefile
  hack/ci-e2e.sh
  hack/clean-e2e.sh
  test/e2e/basic_provisioning_test.go
  test/e2e/config/fixture.yaml
  test/e2e/config/ironic.yaml
Labels: lgtm, approved, size/L

#1408 🌱 bump CAPI to v1.5.3
  test/go.mod
  test/go.sum
Labels: size/S, lgtm, approved

#1407 🌱 add verify-release.sh
  hack/verify-release.sh
Labels: size/XL, lgtm, approved
