Repository metal3-io/baremetal-operator, pull requests merged in 2023-01, with the labels that each got.

#1200 🌱 manifestlint: move from kubeval to kubeconform
  hack/manifestlint.sh
Labels: size/M, lgtm, approved

#1175 🌱 Refine ironic provisioner log data format
  go.mod
  main.go
  pkg/provisioner/ironic/factory.go
Labels: size/S, lgtm, approved, ok-to-test

#1201 🐛 .github: secure github actions
  .github/workflows/kubesec.yml
  .github/workflows/release.yaml
Labels: size/S, lgtm, approved

#1202 🌱 pin golang:1.19.4 with digest
  Dockerfile
Labels: size/XS, lgtm, approved

#1203 🌱 use docker.io consistently, and pin more checks
  hack/generate.sh
  hack/gofmt.sh
  hack/golint.sh
  hack/gomod.sh
  hack/gosec.sh
  hack/markdownlint.sh
  hack/unit.sh
Labels: size/S, lgtm, approved

#1204 ✨ add explicit securitycontexts to controller
  Tiltfile
  config/manager/manager.yaml
  config/render/capm3.yaml
Labels: lgtm, approved, size/L

#1206 🌱 owners: add tuminoid to reviewers
  OWNERS
Labels: size/XS, lgtm, approved
