Repository metal3-io/baremetal-operator, pull requests merged in 2023-04, with the labels that each got.

#1215 Replace package "text" with "google/safetext"
  cmd/make-bm-worker/templates/templates.go
  cmd/make-virt-host/main.go
  go.mod
  go.sum
Labels: size/S, lgtm, approved, ok-to-test

#1243 🐛 Create nodes with namespace already prepended
  pkg/provisioner/ironic/ironic.go
Labels: size/XS, lgtm, approved

#1242 ⚠️ run BMO deployment as non-root (v2)
  ironic-deployment/base/ironic.yaml
  ironic-deployment/components/keepalived/keepalived_patch.yaml
  ironic-deployment/components/mariadb/mariadb_patch.yaml
  resources/keepalived-docker/Dockerfile
  resources/keepalived-docker/configure-nonroot.sh
  resources/keepalived-docker/manage-keepalived.sh
Labels: lgtm, approved, size/L

#1241 ⚠️ Store htpasswd files in Secrets instead of ConfigMaps
  ironic-deployment/components/basic-auth/auth.yaml
  ironic-deployment/components/basic-auth/kustomization.yaml
  ironic-deployment/overlays/basic-auth_tls/basic-auth_tls.yaml
Labels: size/S, lgtm, approved

#1250 :bug: Revert live-iso validation as it is blocking pxe boot when non-virtualmedia drivers are used
  apis/metal3.io/v1alpha1/baremetalhost_validation.go
  apis/metal3.io/v1alpha1/baremetalhost_validation_test.go
Labels: size/S, lgtm, approved

#1246 🌱 Disable scheduled workflows from running in forks
  .github/workflows/kubesec.yml
  .github/workflows/release.yaml
Labels: size/XS, lgtm, approved

#1255 📖 fix broken links in markdown files
  docs/dev-setup.md
Labels: size/XS, lgtm, approved

#1237 ✨ Supported forced reboot of preprovisioning images
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/host_state_machine_test.go
  controllers/metal3.io/hostfirmwaresettings_test.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/inspecthardware_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/provision_test.go
  pkg/provisioner/ironic/testserver/ironic.go
  pkg/provisioner/provisioner.go
Labels: size/XL, lgtm, approved

#1240 🐛 Fix ironic Provision() unit tests
  pkg/provisioner/ironic/provision_test.go
  pkg/provisioner/ironic/testserver/ironic.go
Labels: size/M, lgtm

#1249 Use same settings for provisioner and controller logs
  main.go
  pkg/provisioner/ironic/factory.go
Labels: size/S, lgtm, approved

#1244 📖 update releasing.md
  docs/releasing.md
Labels: lgtm, approved, size/L

#1256 Add missing rbac rules for BaremetalHost Controller
  config/rbac/role.yaml
  config/render/capm3.yaml
  controllers/metal3.io/baremetalhost_controller.go
Labels: size/S, lgtm, approved, ok-to-test

#1257 🌱 Bump go module dependencies
  apis/go.mod
  apis/go.sum
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/crd/bases/metal3.io_bmceventsubscriptions.yaml
  config/crd/bases/metal3.io_firmwareschemas.yaml
  config/crd/bases/metal3.io_hardwaredata.yaml
  config/crd/bases/metal3.io_hostfirmwaresettings.yaml
  config/crd/bases/metal3.io_preprovisioningimages.yaml
  config/render/capm3.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/XL, lgtm, approved
