Repository metal3-io/baremetal-operator, pull requests merged in 2023-11, with the labels that each got.

#1419 🌱 bump x/net to v0.17.0
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/M, lgtm, approved

#1418 🌱 fix various issues with go modules
  Makefile
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, approved, size/L

#1402 🌱 Re-inspection by annotation test added
  .gitignore
  test/e2e/config/fixture.yaml
  test/e2e/config/ironic.yaml
  test/e2e/re_inspection_test.go
Labels: lgtm, approved, size/L

#1421 📖 Add release-0.3 branch test triggers in README
  README.md
Labels: size/S, lgtm, approved

#1426 🌱 Adding PR title verifier
  .github/workflows/pr-verifier.yaml
Labels: size/S, lgtm, approved

#1420 🐛 Log node updates with a normal logger
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/raid.go
  pkg/provisioner/ironic/update_opts.go
Labels: size/M, lgtm, approved

#1410 🌱 Integrate sushy-tools and Redfish into e2e testing
  hack/ci-e2e.sh
  hack/clean-e2e.sh
  test/e2e/config/ironic.yaml
  test/e2e/sushy-tools/sushy-emulator.conf
Labels: lgtm, approved, size/L

#1427 🌱 Clean up logging and error handling in the webhooks
  apis/go.mod
  apis/metal3.io/v1alpha1/baremetalhost_validation.go
  apis/metal3.io/v1alpha1/baremetalhost_validation_test.go
  apis/metal3.io/v1alpha1/baremetalhost_webhook.go
  apis/metal3.io/v1alpha1/bmceventsubscription_validation.go
  apis/metal3.io/v1alpha1/bmceventsubscription_validation_test.go
  apis/metal3.io/v1alpha1/bmceventsubscription_webhook.go
Labels: lgtm, approved, size/L

#1428 🐛 Do not update instance_info and deploy_interface for active nodes
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: size/M, lgtm, approved

#1439 :bug: Don't munge timestamp in structured logs, again
  main.go
Labels: size/XS, lgtm, approved

#1434 🌱 Implement Detached/Status Annotation E2E Test
  test/e2e/basic_provisioning_test.go
  test/e2e/config/fixture.yaml
  test/e2e/config/ironic.yaml
Labels: lgtm, approved, size/L

#1440 ✨ Replace uses of kubectl and cmctl binaries in e2e
  hack/ci-e2e.sh
  hack/e2e/ensure_cmctl.sh
  test/e2e/cert_manager.go
  test/e2e/common.go
  test/e2e/config/fixture.yaml
  test/e2e/config/ironic.yaml
  test/e2e/e2e_suite_test.go
  test/go.mod
  test/go.sum
Labels: lgtm, approved, size/L

#1445 📖 Commit signing off update.
  CONTRIBUTING.md
Labels: size/S, lgtm, approved

#1437 🌱 Add github workflow for e2e fixture tests
  .github/workflows/e2e-fixture-test.yml
  test/e2e/basic_ops_test.go
  test/e2e/basic_provisioning_test.go
  test/e2e/config/ironic.yaml
  test/e2e/external_inspection_test.go
  test/e2e/inspection_test.go
  test/e2e/re_inspection_test.go
Labels: size/M, lgtm, approved

#1393 🌱 Add CI support and branch maintenance section
  CONTRIBUTING.md
  hack/markdownlint.sh
Labels: size/M, lgtm, approved

#1435 ✨ Implement API version negotiation
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/bmceventsubscription_controller.go
  controllers/metal3.io/host_state_machine_test.go
  controllers/metal3.io/hostfirmwaresettings_controller.go
  go.mod
  go.sum
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/adopt_test.go
  pkg/provisioner/ironic/clients/client.go
  pkg/provisioner/ironic/clients/features.go
  pkg/provisioner/ironic/configdrive_test.go
  pkg/provisioner/ironic/delete_test.go
  pkg/provisioner/ironic/dependencies.go
  pkg/provisioner/ironic/inspecthardware_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/power_test.go
  pkg/provisioner/ironic/provision_test.go
  pkg/provisioner/ironic/ready_test.go
  pkg/provisioner/ironic/testserver/ironic.go
  pkg/provisioner/ironic/updatehardwarestate_test.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
  pkg/provisioner/provisioner.go
Labels: lgtm, approved, size/L

#1433 🌱 Refactor handling the provisioner's ready status
  pkg/provisioner/ironic/adopt_test.go
  pkg/provisioner/ironic/configdrive_test.go
  pkg/provisioner/ironic/delete_test.go
  pkg/provisioner/ironic/dependencies.go
  pkg/provisioner/ironic/inspecthardware_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/power_test.go
  pkg/provisioner/ironic/provision_test.go
  pkg/provisioner/ironic/ready_test.go
  pkg/provisioner/ironic/testserver/ironic.go
  pkg/provisioner/ironic/updatehardwarestate_test.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: lgtm, approved, size/L

#1447 🌱 Remove traces of IRONIC_INSPECTOR_ENDPOINT in BMO
  Makefile
  config/default/ironic.env
  config/overlays/e2e/ironic.env
  config/render/capm3.yaml
  docs/configuration.md
  docs/dev-setup.md
  hack/generate.sh
  hack/ironic_ci.env
  hack/unit.sh
  ironic-deployment/components/keepalived/ironic_bmo_configmap.env
  ironic-deployment/default/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e/ironic_bmo_configmap.env
  tools/run_local_ironic.sh
Labels: size/S, lgtm, approved

#1452 🌱 Enable the Redfish RAID interfaces
  pkg/hardwareutils/bmc/redfish.go
  pkg/hardwareutils/bmc/redfish_virtualmedia.go
Labels: size/XS, lgtm, approved

#1448 🌱 Implement Helper Functions for E2E Tests
  test/e2e/basic_ops_test.go
  test/e2e/basic_provisioning_test.go
  test/e2e/common.go
  test/e2e/config/fixture.yaml
  test/e2e/external_inspection_test.go
  test/e2e/inspection_test.go
  test/e2e/re_inspection_test.go
Labels: lgtm, approved, size/L

#1441 ✨ Expose FirmwareInterface in Node/BMC
  go.mod
  go.sum
  pkg/hardwareutils/bmc/access.go
  pkg/hardwareutils/bmc/access_test.go
  pkg/hardwareutils/bmc/ibmc.go
  pkg/hardwareutils/bmc/idrac.go
  pkg/hardwareutils/bmc/idrac_virtualmedia.go
  pkg/hardwareutils/bmc/ilo4.go
  pkg/hardwareutils/bmc/ilo5.go
  pkg/hardwareutils/bmc/ipmi.go
  pkg/hardwareutils/bmc/irmc.go
  pkg/hardwareutils/bmc/redfish.go
  pkg/hardwareutils/bmc/redfish_virtualmedia.go
  pkg/provisioner/ironic/clients/features.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/prepare_test.go
  pkg/provisioner/ironic/testbmc/testbmc.go
Labels: lgtm, approved, size/L

#1446 ✨ Detect which inspection implementation to use for new nodes
  go.mod
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/testserver/ironic.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: size/M, lgtm, approved

#1455 🌱Bump golang version to 1.20.11
  Dockerfile
  Makefile
Labels: size/XS, lgtm, approved

#1454 🌱Bump golang version to 1.20.11
  Dockerfile
  Makefile
  hack/e2e/ensure_go.sh
Labels: size/XS, lgtm, approved

#1463 🌱 Delete "ok-to-test" label from dependabot PRs
  .github/dependabot.yml
Labels: size/S, lgtm, approved

#1467 🌱 bump markdownlint to 0.13.0
  hack/markdownlint.sh
Labels: size/M, lgtm, approved
