Repository metal3-io/baremetal-operator, pull requests merged in 2023-09, with the labels that each got.

#1349 🌱 fix issue with git directory ownership in golint
  hack/golint.sh
Labels: size/XS, lgtm, approved

#1348 📖 improve release notes tool
  .gitignore
  hack/tools/release_notes.go
Labels: size/S, lgtm, approved

#1352 📖 update releasing.md
  docs/releasing.md
Labels: size/M, lgtm, approved

#1353 ⚠️ adopt manifests for kustomize v5
  config/basic-auth/default/kustomization.yaml
  config/basic-auth/tls/kustomization.yaml
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/kustomization.yaml
  config/tls/kustomization.yaml
  ironic-deployment/components/basic-auth/kustomization.yaml
  ironic-deployment/components/keepalived/kustomization.yaml
  ironic-deployment/components/mariadb/kustomization.yaml
  ironic-deployment/components/tls/kustomization.yaml
  ironic-deployment/overlays/basic-auth_tls/kustomization.yaml
Labels: lgtm, approved, size/L, ok-to-test

#1312 :bug: Proceed to power off after deprovisioning
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  docs/BaremetalHost_ProvisioningState.dot
  docs/BaremetalHost_ProvisioningState.png
Labels: size/M, lgtm, approved

#1260 🌱 Stop using Inspector API for inspection status
  pkg/provisioner/ironic/inspecthardware_test.go
  pkg/provisioner/ironic/ironic.go
Labels: lgtm, approved, size/L

#1359 :seedling: run dependabot less often
  .github/dependabot.yml
Labels: size/XS, lgtm, approved

#1269 :sparkles: Add a list of alternate disk names to HardwareDetails
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/crd/bases/metal3.io_hardwaredata.yaml
  config/render/capm3.yaml
  pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go
Labels: size/M, lgtm, approved

#1362 🌱 Gosec: Run submodules separately
  hack/gosec.sh
Labels: size/XS, lgtm, approved

#1363 📖 fix typo in releasing.md
  docs/releasing.md
Labels: size/XS, lgtm, approved

#1247 🌱 Enable concurrency in BMO controllers through cmdLine flags
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/bmceventsubscription_controller.go
  controllers/metal3.io/hostfirmwaresettings_controller.go
  controllers/metal3.io/preprovisioningimage_controller.go
  main.go
Labels: size/M, lgtm, approved

#1365 📖 fix releasing.md on annotated tags
  docs/releasing.md
Labels: size/XS, lgtm, approved

#1366 :book: clarify tag usage in releasing.md
  docs/releasing.md
Labels: size/S, lgtm, approved

#1355 ⚠️ Use ironic inventory API instead of calling ironic-inspector
  cmd/get-hardware-details/main.go
  docs/configuration.md
  go.mod
  go.sum
  pkg/provisioner/ironic/adopt_test.go
  pkg/provisioner/ironic/bios_test.go
  pkg/provisioner/ironic/clients/auth.go
  pkg/provisioner/ironic/clients/client.go
  pkg/provisioner/ironic/configdrive_test.go
  pkg/provisioner/ironic/delete_test.go
  pkg/provisioner/ironic/dependencies.go
  pkg/provisioner/ironic/factory.go
  pkg/provisioner/ironic/factory_test.go
  pkg/provisioner/ironic/findhost_test.go
  pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go
  pkg/provisioner/ironic/hardwaredetails/hardwaredetails_test.go
  pkg/provisioner/ironic/inspecthardware_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
  pkg/provisioner/ironic/power_test.go
  pkg/provisioner/ironic/prepare_test.go
  pkg/provisioner/ironic/provision_test.go
  pkg/provisioner/ironic/provisioncapacity_test.go
  pkg/provisioner/ironic/ready_test.go
  pkg/provisioner/ironic/testserver/inspector.go
  pkg/provisioner/ironic/testserver/ironic.go
  pkg/provisioner/ironic/updatehardwarestate_test.go
  pkg/provisioner/ironic/updateopts_test.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: size/XL, lgtm, approved

#1303 ✨ Add e2e tests
  .gitignore
  .golangci.yml
  Makefile
  config/overlays/e2e/ironic.env
  config/overlays/e2e/kustomization.yaml
  config/overlays/fixture/kustomization.yaml
  docs/releasing.md
  hack/ci-e2e.sh
  hack/clean-e2e.sh
  hack/e2e/ensure_cmctl.sh
  hack/e2e/ensure_go.sh
  hack/e2e/ensure_kubectl.sh
  hack/e2e/ensure_minikube.sh
  hack/e2e/net.xml
  hack/gosec.sh
  ironic-deployment/overlays/e2e/ironic-patch.yaml
  ironic-deployment/overlays/e2e/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e/kustomization.yaml
  test/e2e/README.md
  test/e2e/common.go
  test/e2e/config/fixture.yaml
  test/e2e/config/ironic.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/inspection_test.go
  test/go.mod
  test/go.sum
Labels: size/XXL, lgtm, approved
