Repository metal3-io/baremetal-operator, pull requests merged in 2023-08, with the labels that each got.

#1282 :sparkles: Add TLS configuration flags for BMO
  go.mod
  go.sum
  main.go
  main_test.go
Labels: lgtm, approved, size/L

#1322 :bug: Trigger reconcile on Secret change
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/preprovisioningimage_controller.go
Labels: size/XS, lgtm, approved

#1327 :seedling: Fix code quality issues in BMO TLS configuration code
  main.go
Labels: size/S, lgtm, approved

#1328 ✨ Add an explicit Architecture field (closes #1270)
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/profile/profile.go
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/updateopts_test.go
  pkg/provisioner/provisioner.go
Labels: size/M, lgtm, approved

#1333 🌱 Bump golangci-lint to v1.54.1 and fix lint issues
  cmd/make-bm-worker/main.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/bmceventsubscription_controller.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  controllers/metal3.io/hostfirmwaresettings_test.go
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/imageprovider/default.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/factory_test.go
  pkg/provisioner/ironic/ironic_test.go
  pkg/provisioner/ironic/prepare_test.go
  pkg/provisioner/ironic/testserver/server.go
Labels: size/XL, lgtm, approved

#1337 🌱 Bump golangci-lint to v1.54.2
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/host_state_machine_test.go
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/provisioner/ironic/capabilities_test.go
  pkg/provisioner/ironic/configdrive_test.go
  pkg/provisioner/ironic/devicehints/devicehints_test.go
  pkg/provisioner/ironic/provision_test.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: lgtm, approved, size/L

#1340 :seedling: bump x/net to v0.14.0
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
Labels: size/M, lgtm, approved

#1341 🌱 Bump controller-tools to v0.12.1
  config/crd/bases/metal3.io_baremetalhosts.yaml
  config/crd/bases/metal3.io_bmceventsubscriptions.yaml
  config/crd/bases/metal3.io_firmwareschemas.yaml
  config/crd/bases/metal3.io_hardwaredata.yaml
  config/crd/bases/metal3.io_hostfirmwaresettings.yaml
  config/crd/bases/metal3.io_preprovisioningimages.yaml
  config/rbac/role.yaml
  config/render/capm3.yaml
  config/webhook/manifests.yaml
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, approved, size/L

#1342 🌱 Bump controller-runtime to v0.15.2
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
Labels: size/S, lgtm, approved
