Repository metal3-io/baremetal-operator, pull requests merged in 2023-12, with the labels that each got.

#1453 🌱E2e live iso ssh implementation
  hack/ci-e2e.sh
  hack/clean-e2e.sh
  hack/e2e/net.xml
  test/e2e/common.go
  test/e2e/config/fixture.yaml
  test/e2e/config/ironic.yaml
  test/e2e/external_inspection_test.go
  test/e2e/live_iso_test.go
  test/e2e/re_inspection_test.go
  test/go.mod
Labels: lgtm, approved, size/L

#1475 🌱 bump gosec to 2.18.2
  hack/gosec.sh
Labels: size/S, lgtm, approved

#1474 🌱 bump gosec to 2.18.2
  hack/gosec.sh
Labels: size/XS, lgtm, approved

#1476 🌱 bump gosec to 2.18.2
  hack/gosec.sh
Labels: size/S, lgtm, approved

#1470 🌱 e2e: Enhanced Serial Log Checking Functionality
  hack/ci-e2e.sh
Labels: size/S, lgtm, approved

#1486 🐛 Fix htpasswd command not found
  hack/ci-e2e.sh
  hack/e2e/ensure_htpasswd.sh
Labels: size/S, lgtm, approved

#1492 🌱 add clomonitor badge to README
  README.md
Labels: size/XS, lgtm, approved

#1480 ✨ Add an explicit way to auto-detect ChecksumType
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/baremetalhost_types_test.go
  cmd/make-bm-worker/main.go
  config/base/crds/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
  docs/api.md
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/provision_test.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
  test/e2e/basic_provisioning_test.go
Labels: lgtm, approved, size/L

#1491 🌱 E2e Add SSH Key-Based Authentication
  hack/ci-e2e.sh
  test/e2e/basic_ops_test.go
  test/e2e/basic_provisioning_test.go
  test/e2e/common.go
  test/e2e/config/ironic.yaml
  test/e2e/external_inspection_test.go
  test/e2e/inspection_test.go
  test/e2e/live_iso_test.go
  test/e2e/re_inspection_test.go
Labels: lgtm, approved, size/L

#1497 🌱 bump x/crypto to 0.17.0
  test/go.mod
  test/go.sum
Labels: size/S, lgtm, approved
