Repository metal3-io/baremetal-operator, pull requests merged in 2024-01, with the labels that each got.

#1499 🌱 add OpenSSF Scorecard badge to README
  README.md
Labels: size/XS, lgtm, approved

#1493 🌱 E2e: Change the filename of basic_provisioning_test.go to provisioning_and_annotation_test.go.
  test/e2e/provisioning_and_annotation_test.go
Labels: size/XS, lgtm, approved

#1490 🌱 E2e: Name artifacts based on emulator
  hack/ci-e2e.sh
  test/e2e/config/ironic.yaml
Labels: size/XS, lgtm, approved

#1494 🌱 E2E: Have a common function to install BMO and Ironic
  test/e2e/common.go
  test/e2e/e2e_suite_test.go
Labels: lgtm, approved, size/L

#1507 🌱 bump go modules in /test to sync
  test/go.mod
  test/go.sum
Labels: size/M, lgtm, approved

#1511 📖 fix previous release detection in make release-notes
  Makefile
Labels: size/XS, lgtm, approved

#1510 🌱 bump golang to 1.20.12
  Dockerfile
  Makefile
  hack/e2e/ensure_go.sh
Labels: size/XS, lgtm, approved

#1514 🌱 bump golang to 1.20.12
  Dockerfile
Labels: size/XS, lgtm, approved

#1456 🌱 Add github action to trigger container images build
  .github/workflows/build-images-action.yml
Labels: size/M, lgtm, approved

#1519 📖 update releasing.md
  docs/releasing.md
Labels: size/XS, lgtm, approved

#1518 📖 update build badges
  README.md
Labels: size/S, lgtm, approved

#1517 📖 add release-0.5 to README.md
  README.md
Labels: size/XS, lgtm, approved

#1509 🌱 reduce github actions permissions
  .github/workflows/build-images-action.yml
  .github/workflows/dependabot.yml
  .github/workflows/e2e-fixture-test.yml
  .github/workflows/kubesec.yml
  .github/workflows/lint-docs.yaml
  .github/workflows/pr-verifier.yaml
  .github/workflows/release.yaml
Labels: lgtm, approved, size/L

#1515 🌱 Bump controller-runtime, k8s/*, CAPM3/test and other related go modules
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  main.go
  test/go.mod
  test/go.sum
Labels: size/XL, lgtm, approved

#1394 🌱 Add golangci-lint github workflow
  .github/workflows/golangci-lint.yml
  .golangci.yaml
  .golangci.yml
  cmd/get-hardware-details/main.go
  cmd/make-bm-worker/main.go
  cmd/make-bm-worker/templates/templates_test.go
  cmd/make-virt-host/main.go
  controllers/metal3.io/action_result.go
  controllers/metal3.io/action_result_test.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/bmceventsubscription_controller.go
  controllers/metal3.io/demo_test.go
  controllers/metal3.io/errors.go
  controllers/metal3.io/host_config_data.go
  controllers/metal3.io/host_config_data_test.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  controllers/metal3.io/hostfirmwaresettings_controller.go
  controllers/metal3.io/hostfirmwaresettings_test.go
  controllers/metal3.io/preprovisioningimage_controller.go
  main.go
  pkg/imageprovider/default.go
  pkg/imageprovider/imageprovider.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/adopt_test.go
  pkg/provisioner/ironic/bios_test.go
  pkg/provisioner/ironic/clients/auth.go
  pkg/provisioner/ironic/clients/client.go
  pkg/provisioner/ironic/configdrive_test.go
  pkg/provisioner/ironic/delete_test.go
  pkg/provisioner/ironic/factory.go
  pkg/provisioner/ironic/factory_test.go
  pkg/provisioner/ironic/hardwaredetails/hardwaredetails_test.go
  pkg/provisioner/ironic/inspecthardware_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/power_test.go
  pkg/provisioner/ironic/provision_test.go
  pkg/provisioner/ironic/provisioncapacity_test.go
  pkg/provisioner/ironic/raid.go
  pkg/provisioner/ironic/ready_test.go
  pkg/provisioner/ironic/testbmc/testbmc.go
  pkg/provisioner/ironic/testserver/ironic.go
  pkg/provisioner/ironic/testserver/ironic_test.go
  pkg/provisioner/ironic/testserver/server.go
  pkg/provisioner/ironic/updatehardwarestate_test.go
  pkg/provisioner/ironic/updateopts_test.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
  pkg/provisioner/provisioner.go
  pkg/secretutils/secret_manager.go
  pkg/utils/stringlist_test.go
Labels: size/XXL, lgtm, approved

#1522 🌱 Install golangci-lint directly instead of building it using go-modules
  .github/workflows/golangci-lint.yml
  Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: size/XXL, lgtm, approved

#1451 🌱 Add BMO e2e upgrade test
  .github/workflows/e2e-fixture-test.yml
  .gitignore
  Makefile
  config/overlays/e2e-release-0.4/ironic.env
  config/overlays/e2e-release-0.4/kustomization.yaml
  config/overlays/fixture-release-0.4/kustomization.yaml
  hack/ci-e2e.sh
  test/e2e/README.md
  test/e2e/common.go
  test/e2e/config/fixture.yaml
  test/e2e/config/ironic.yaml
  test/e2e/upgrade_test.go
Labels: size/XL, lgtm, approved

#1524 🐛 Fix ginkgo version mismatch between cli and import package in e2e
  Makefile
Labels: size/XS, lgtm, approved

#1521 :book: switch markdownlint container to markdownlint-cli2
  .markdownlint-cli2.yaml
  CONTRIBUTING.md
  docs/api.md
  docs/configuration.md
  docs/deploying.md
  docs/dev-setup.md
  hack/markdownlint.sh
  ironic-deployment/README.md
  test/e2e/README.md
Labels: lgtm, approved, size/L

#1530 🌱 Set USE_IRONIC_INSPECTOR explicitly (to true for now)
  ironic-deployment/default/ironic_bmo_configmap.env
Labels: size/XS, lgtm, approved

#1525 📖 Add trigger phrases and status badge for e2e tests
  README.md
  test/e2e/README.md
Labels: size/M, lgtm, approved

#1527 🌱 Enable parallel testing in E2E
  Makefile
  hack/ci-e2e.sh
  hack/clean-e2e.sh
  hack/create_bmcs.sh
  hack/e2e/ensure_yq.sh
  hack/e2e/net.xml
  test/e2e/README.md
  test/e2e/basic_ops_test.go
  test/e2e/bmc.go
  test/e2e/common.go
  test/e2e/config/bmcs-fixture.yaml
  test/e2e/config/bmcs-sushy-tools.yaml
  test/e2e/config/bmcs-vbmc.yaml
  test/e2e/config/fixture.yaml
  test/e2e/config/ironic.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/external_inspection_test.go
  test/e2e/inspection_test.go
  test/e2e/live_iso_test.go
  test/e2e/provisioning_and_annotation_test.go
  test/e2e/re_inspection_test.go
  test/e2e/upgrade_test.go
Labels: lgtm, approved, size/L

#1501 ✨ Add new CRD for FirmwareComponents Update
  PROJECT
  apis/metal3.io/v1alpha1/hostfirmwarecomponents_types.go
  apis/metal3.io/v1alpha1/hostfirmwarecomponents_types_test.go
  apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  config/base/crds/bases/metal3.io_hostfirmwarecomponents.yaml
  config/base/rbac/hostfirmwarecomponents_editor_role.yaml
  config/base/rbac/hostfirmwarecomponents_viewer_role.yaml
  config/samples/metal3.io_v1alpha1_hostfirmwarecomponents.yaml
Labels: size/XL, lgtm, approved
