Repository metal3-io/baremetal-operator, pull requests merged in 2024-07, with the labels that each got.

#1797 🌱 Optimize the dependabot configuration and add release branch configurations
  .github/dependabot.yml
Labels: lgtm, approved, size/L

#1805 🌱 bump golang to 1.22.5
  Dockerfile
  Makefile
  hack/e2e/ensure_go.sh
Labels: size/XS, lgtm, approved

#1795 :seedling: Use basic-checks image in generate and gomod tests
  hack/generate.sh
  hack/gomod.sh
Labels: size/XS, lgtm, approved

#1806 :seedling: E2E: Remove gomega in LoadBMCConfig()
  test/e2e/bmc.go
  test/e2e/e2e_suite_test.go
Labels: size/S, lgtm, approved

#1816 🌱 schedule dependabot on certain day, and add ok-to-test automatically
  .github/dependabot.yml
Labels: size/M, lgtm, approved

#1793 🐛 Fix HFC to execute updates
  apis/metal3.io/v1alpha1/hostfirmwarecomponents_types.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/hostfirmwarecomponents_controller.go
  controllers/metal3.io/hostfirmwarecomponents_test.go
  main.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/provision_test.go
Labels: lgtm, approved, size/L

#1767 :seedling: Add new go library to create new bmc and bmh
  .github/workflows/e2e-fixture-test.yml
  .github/workflows/e2e-test.yml
  .github/workflows/golangci-lint.yml
  clean_bmcs.sh
  hack/ci-e2e.sh
  hack/clean-e2e.sh
  hack/create_bmcs.sh
  test/createVM/main.go
  test/createVM/templates/VM.xml.tpl
  test/createVM/templates/pool.xml.tpl
  test/createVM/templates/volume.xml.tpl
  test/go.mod
  test/go.sum
  tools/bmh_test/clean_local_bmh_test_setup.sh
Labels: size/XL, lgtm, approved

#1821 🌱 Use OwnerReference for HostFirmwareComponents
  controllers/metal3.io/baremetalhost_controller.go
Labels: size/XS, lgtm, approved

#1825 🐛 Fix HFC Status
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/hostfirmwarecomponents_controller.go
Labels: size/S, lgtm, approved

#1827 🌱 Bump golang to 1.22
  .github/workflows/release.yaml
  .golangci.yaml
  Dockerfile
  Tiltfile
  hack/e2e/ensure_go.sh
  hack/generate.sh
  hack/gofmt.sh
  hack/golint.sh
  hack/gomod.sh
  hack/unit.sh
Labels: size/S, lgtm, approved
