Repository metal3-io/baremetal-operator, pull requests merged in 2024-11, with the labels that each got.

#2028 :seedling: Fetch Ironic node list after each e2e test
  hack/ci-e2e.sh
  test/e2e/basic_ops_test.go
  test/e2e/common.go
  test/e2e/config/fixture.yaml
  test/e2e/config/ironic.yaml
  test/e2e/e2e_config.go
  test/e2e/e2e_suite_test.go
  test/e2e/external_inspection_test.go
  test/e2e/inspection_test.go
  test/e2e/live_iso_test.go
  test/e2e/provisioning_and_annotation_test.go
  test/e2e/re_inspection_test.go
  test/e2e/upgrade_test.go
Labels: lgtm, approved, size/L

#2043 🌱 Introduce inspection delay for the fixture provisioner
  pkg/provisioner/fixture/fixture.go
Labels: size/M, lgtm, approved

#2013 🌱 Improve test coverage
  controllers/metal3.io/preprovisioningimage_controller.go
  controllers/metal3.io/preprovisioningimage_controller_test.go
  pkg/provisioner/ironic/factory_test.go
Labels: lgtm, approved, size/L

#1966 🌱 Adding ipxe builder to init container
  ironic-deployment/components/ipxe-tls/certificate.yaml
  ironic-deployment/components/ipxe-tls/kustomization.yaml
  ironic-deployment/components/ipxe-tls/kustomizeconfig.yaml
  ironic-deployment/components/ipxe-tls/tls.yaml
  ironic-deployment/overlays/with-ipxe-builder-tls/ipxe-configmap.env
  ironic-deployment/overlays/with-ipxe-builder-tls/kustomization.yaml
  ironic-deployment/overlays/with-ipxe-builder/ipxe-builder-patch.yaml
  ironic-deployment/overlays/with-ipxe-builder/ipxe-configmap.env
  ironic-deployment/overlays/with-ipxe-builder/kustomization.yaml
Labels: lgtm, approved, size/L

#2042 🌱 E2E: Add build tags
  .golangci.yaml
  Makefile
  hack/ci-e2e.sh
  test/e2e/basic_ops_test.go
  test/e2e/bmc.go
  test/e2e/cert_manager.go
  test/e2e/common.go
  test/e2e/e2e_config.go
  test/e2e/e2e_suite_test.go
  test/e2e/external_inspection_test.go
  test/e2e/inspection_test.go
  test/e2e/live_iso_test.go
  test/e2e/provisioning_and_annotation_test.go
  test/e2e/re_inspection_test.go
  test/e2e/upgrade_test.go
  test/vbmctl/main.go
  test/vbmctl/templates/VM.xml.tpl
  test/vbmctl/templates/pool.xml.tpl
  test/vbmctl/templates/volume.xml.tpl
Labels: size/M, lgtm, approved

#2046 🌱 Adjust test and linter timings
  .golangci.yaml
  pkg/provisioner/fixture/fixture.go
  test/e2e/config/fixture.yaml
Labels: size/XS, lgtm, approved

#2041 ✨ Add reference to HostUpdatePolicy in Servicing with HFS Support
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  config/base/crds/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/host_state_machine_test.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/clients/features.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/servicing.go
  pkg/provisioner/ironic/servicing_test.go
  pkg/provisioner/ironic/testserver/ironic.go
  pkg/provisioner/provisioner.go
Labels: size/XL, lgtm, approved

#2057 :seedling: add scheduled osv-scanner workflow
  .github/workflows/osv-scanner-scan.yml
Labels: size/M, lgtm, approved

#2058 :seedling: simplify go version handling in verify-release.sh
  hack/verify-release.sh
Labels: size/M, lgtm, approved

#2063 :seedling: use uuidgen to generate random username/password
  tools/deploy.sh
Labels: size/XS, lgtm, approved

#2064 :book: Add e2e status badge to readme
  README.md
Labels: size/XS, lgtm, approved

#2066 📖 Add e2e status badge to readme
  README.md
Labels: size/XS, lgtm, approved

#2065 📖 Add e2e status badge to readme
  README.md
Labels: size/XS, lgtm, approved

#2048 :bug: Make custom deploy equivalent to image deploy
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  controllers/metal3.io/baremetalhost_controller.go
  pkg/provisioner/ironic/ironic.go
Labels: size/S, lgtm, approved

#2070 :seedling: Bump Go to 1.23.3 and golangci-lint to 1.60.3
  .github/workflows/golangci-lint.yml
  .golangci.yaml
  Dockerfile
  Makefile
  Tiltfile
  cmd/make-bm-worker/templates/templates_test.go
  hack/e2e/ensure_go.sh
  pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go
Labels: size/M, lgtm, approved

#2060 🐛 Update HFC Status when handling error in actionPreparing
  controllers/metal3.io/baremetalhost_controller.go
Labels: size/XS, lgtm, approved, ok-to-test

#1974 :bug: Remove dataImage finalizer if BMH is missing
  controllers/metal3.io/dataimage_controller.go
Labels: size/S, lgtm, approved
