Repository metal3-io/baremetal-operator, pull requests merged in 2024-05, with the labels that each got.

#1642 🌱 Enabled last batch of linters
  .golangci.yaml
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  cmd/make-virt-host/main.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/bmceventsubscription_controller.go
  controllers/metal3.io/bmceventsubscription_controller_test.go
  controllers/metal3.io/controller_test.go
  controllers/metal3.io/demo_test.go
  controllers/metal3.io/host_config_data_test.go
  controllers/metal3.io/host_state_machine.go
  controllers/metal3.io/host_state_machine_test.go
  controllers/metal3.io/hostfirmwarecomponents_test.go
  controllers/metal3.io/hostfirmwaresettings_test.go
  main_test.go
  pkg/hardwareutils/bmc/ilo4.go
  pkg/hardwareutils/bmc/ilo5.go
  pkg/hardwareutils/bmc/irmc.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/dependencies.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/raid.go
  pkg/provisioner/ironic/testbmc/testbmc.go
  pkg/provisioner/ironic/testserver/ironic.go
  test/e2e/cert_manager.go
  test/e2e/common.go
  test/e2e/e2e_suite_test.go
  test/e2e/upgrade_test.go
Labels: lgtm, approved, size/L, ok-to-test

#1708 🌱 Refactoring: introduce capabilities.go
  pkg/provisioner/ironic/capabilities.go
  pkg/provisioner/ironic/ironic.go
Labels: lgtm, approved, size/L, ok-to-test

#1701 🌱 chore(deps): bump kube-rbac-proxy to v0.16.0
  config/base/manager_auth_proxy_patch.yaml
  config/render/capm3.yaml
Labels: size/XS, lgtm, approved, ok-to-test

#1692 :seedling: E2E Upgrade: Add new tests for new BMO and Ironic releases
  config/overlays/e2e-release-0.6/ironic.env
  config/overlays/e2e-release-0.6/kustomization.yaml
  config/overlays/fixture-release-0.6/kustomization.yaml
  hack/ci-e2e.sh
  ironic-deployment/overlays/e2e-release-24.1/ironic-patch.yaml
  ironic-deployment/overlays/e2e-release-24.1/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-24.1/kustomization.yaml
  test/e2e/config/fixture.yaml
  test/e2e/config/ironic.yaml
Labels: lgtm, approved, size/L

#1707 🐛 Pinning ironic image release-24.1 where it was missed
  ironic-deployment/base/ironic.yaml
Labels: size/XS, lgtm, approved

#1720 🌱 bump gophercloud to v2.0.0-beta.5
  go.mod
  go.sum
Labels: size/XS, lgtm, approved

#1721 🌱 set webhook min TLS version to 1.3
  main.go
Labels: size/XS, lgtm, approved

#1726 :seedling: Add mquhuy as a reviewer
  OWNERS
Labels: size/XS, lgtm, approved

#1716 🌱 Refactoring: introduce inspecthardware.go
  pkg/provisioner/ironic/inspecthardware.go
  pkg/provisioner/ironic/ironic.go
Labels: lgtm, approved, size/L, ok-to-test

#1724 🌱 E2E: Increase timeouts to stabilize CI
  config/overlays/e2e-release-0.4/kustomization.yaml
  config/overlays/e2e-release-0.5/kustomization.yaml
  config/overlays/e2e-release-0.6/kustomization.yaml
  ironic-deployment/overlays/e2e-release-24.0-with-inspector/kustomization.yaml
  ironic-deployment/overlays/e2e-release-24.1/kustomization.yaml
  ironic-deployment/overlays/e2e-with-inspector/kustomization.yaml
  test/e2e/common.go
  test/e2e/config/ironic.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/upgrade_test.go
Labels: lgtm, approved, size/L

#1725 :seedling: Add more ctrl options flags
  main.go
Labels: size/M, lgtm, approved

#1730 🌱 add OWNERS_ALIASES support
  OWNERS
  OWNERS_ALIASES
Labels: size/M, lgtm, approved

#1738 :seedling: Export BuildKustomizeManifest and GetKubeconfigPath functions in E2E
  test/e2e/common.go
  test/e2e/e2e_suite_test.go
  test/e2e/upgrade_test.go
Labels: size/S, lgtm, approved

#1740 🌱 Link to the user guide for supported hardware
  docs/api.md
Labels: size/S, lgtm, approved

#1737 🌱 refactor TLS config
  main.go
  main_test.go
Labels: size/M, lgtm, approved

#1744 🌱 Add issue templates for flaky/failing tests
  .github/ISSUE_TEMPLATE/failing-test.yaml
  .github/ISSUE_TEMPLATE/flaking-test.yaml
Labels: size/M, lgtm, approved

#1745 :seedling: explicitly drop pr approver workflow permissions
  .github/workflows/pr-gh-workflow-approve.yaml
Labels: size/XS, lgtm, approved

#1606 :seedling: Add unit test on pkg/provisioner/ironic/client.go
  pkg/provisioner/ironic/clients/client_test.go
Labels: lgtm, approved, size/L, ok-to-test

#1747 🌱 remove kubesec workflow
  .github/workflows/kubesec.yml
Labels: size/M, lgtm, approved

#1746 🌱 Upload artifacts from fixture tests
  .github/workflows/e2e-fixture-test.yml
Labels: size/XS, lgtm, approved

#1748 🌱 added make lint-fix
  Makefile
Labels: size/S, lgtm, approved, ok-to-test

#1754 🌱 shellcheck only files
  hack/shellcheck.sh
Labels: size/XS, lgtm, approved
