Repository metal3-io/baremetal-operator, pull requests merged in 2024-02, with the labels that each got.

#1537 🐛 Fix VM selection in clean-e2e.sh
  hack/clean-e2e.sh
  tools/bmh_test/clean_local_bmh_test_setup.sh
Labels: size/S, lgtm, approved

#1326 :seedling: add iPXE TLS support to local ironic deployment
  tools/run_local_ironic.sh
Labels: size/M, lgtm, approved

#1546 🌱 E2E: Increase some intervals
  test/e2e/config/ironic.yaml
Labels: size/XS, lgtm, approved

#1548 🐛 Fix an indentation error in kustomization file regarding ironic configmap generator
  config/default/kustomization.yaml
Labels: size/XS, lgtm, approved

#1536 🌱 Enabled more golangci linters
  .golangci.yaml
  Makefile
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/baremetalhost_types_test.go
  apis/metal3.io/v1alpha1/baremetalhost_validation.go
  apis/metal3.io/v1alpha1/baremetalhost_webhook.go
  apis/metal3.io/v1alpha1/bmceventsubscription_types.go
  apis/metal3.io/v1alpha1/bmceventsubscription_validation.go
  apis/metal3.io/v1alpha1/bmceventsubscription_webhook.go
  apis/metal3.io/v1alpha1/firmwareschema_types.go
  apis/metal3.io/v1alpha1/groupversion_info.go
  apis/metal3.io/v1alpha1/hardwaredata_types.go
  apis/metal3.io/v1alpha1/hostfirmwarecomponents_types.go
  apis/metal3.io/v1alpha1/hostfirmwarecomponents_types_test.go
  apis/metal3.io/v1alpha1/hostfirmwaresettings_types.go
  apis/metal3.io/v1alpha1/hostfirmwaresettings_types_test.go
  apis/metal3.io/v1alpha1/preprovisioningimage_types.go
  apis/metal3.io/v1alpha1/profile/profile.go
  cmd/make-virt-host/main.go
  config/base/crds/bases/metal3.io_baremetalhosts.yaml
  config/base/crds/bases/metal3.io_firmwareschemas.yaml
  config/base/crds/bases/metal3.io_hardwaredata.yaml
  config/base/crds/bases/metal3.io_hostfirmwarecomponents.yaml
  config/base/crds/bases/metal3.io_hostfirmwaresettings.yaml
  config/base/crds/bases/metal3.io_preprovisioningimages.yaml
  config/render/capm3.yaml
  controllers/metal3.io/action_result.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/bmceventsubscription_controller.go
  controllers/metal3.io/host_config_data.go
  controllers/metal3.io/host_config_data_test.go
  pkg/hardwareutils/bmc/access.go
  pkg/hardwareutils/bmc/access_test.go
  pkg/hardwareutils/bmc/credentials.go
  pkg/hardwareutils/bmc/errors.go
  pkg/hardwareutils/bmc/ibmc.go
  pkg/hardwareutils/bmc/idrac.go
  pkg/hardwareutils/bmc/idrac_virtualmedia.go
  pkg/hardwareutils/bmc/ilo4.go
  pkg/hardwareutils/bmc/ilo5.go
  pkg/hardwareutils/bmc/ipmi.go
  pkg/hardwareutils/bmc/irmc.go
  pkg/hardwareutils/bmc/redfish.go
  pkg/hardwareutils/bmc/redfish_virtualmedia.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/clients/features.go
  pkg/provisioner/ironic/dependencies.go
  pkg/provisioner/ironic/devicehints/devicehints.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/testserver/ironic.go
  pkg/provisioner/ironic/testserver/server.go
  test/e2e/bmc.go
  test/e2e/common.go
  test/e2e/e2e_suite_test.go
  test/e2e/live_iso_test.go
  test/e2e/provisioning_and_annotation_test.go
Labels: size/XXL, lgtm, approved

#1535 🌱 Bump golang to v1.21.6
  .github/workflows/release.yaml
  .golangci.yaml
  Dockerfile
  Makefile
  Tiltfile
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/generate.sh
  hack/gofmt.sh
  hack/golint.sh
  hack/gomod.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/unit.sh
  pkg/hardwareutils/go.mod
  test/go.mod
  test/go.sum
Labels: size/M, lgtm, approved

#1551 🌱 Add 'wait-power-state' interval to fixture test for flake fix
  test/e2e/config/fixture.yaml
Labels: size/XS, lgtm, approved

#1543 :seedling: Reduce GH fixture test GINKGO_NODES to 1
  .github/workflows/e2e-fixture-test.yml
Labels: size/XS, lgtm, approved

#1556 🌱 E2E: Fix basic auth config
  hack/ci-e2e.sh
Labels: size/XS, lgtm, approved

#1553 🌱 Add ironic and bmo cleanup for upgrade BMO E2E tests
  test/e2e/common.go
  test/e2e/e2e_suite_test.go
  test/e2e/upgrade_test.go
Labels: size/M, lgtm, approved

#1549 🌱 Allow BMC address to be updated
  apis/metal3.io/v1alpha1/baremetalhost_validation.go
  apis/metal3.io/v1alpha1/baremetalhost_validation_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: lgtm, approved, size/L

#1562 🌱 release-0.5: harden stable branch against inspector removal
  config/default/ironic.env
  config/overlays/e2e/ironic.env
  config/render/capm3.yaml
  hack/ironic_ci.env
  ironic-deployment/base/ironic.yaml
  ironic-deployment/components/keepalived/ironic_bmo_configmap.env
  ironic-deployment/default/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e/ironic_bmo_configmap.env
  tools/run_local_ironic.sh
Labels: size/S, lgtm, approved

#1558 📖 Add alternative Tilt setup method to documentation
  docs/dev-setup.md
Labels: size/S, lgtm, approved

#1564 🌱 Bump golang to v1.21.7
  Dockerfile
  Makefile
Labels: size/XS, lgtm, approved

#1565 🌱 Bump golang to v1.20.14
  Dockerfile
  Makefile
  hack/e2e/ensure_go.sh
Labels: size/XS, lgtm, approved

#1568 🌱 Drop dependency on pkg/errors from hardwareutils
  apis/go.mod
  pkg/hardwareutils/bmc/access.go
  pkg/hardwareutils/go.mod
  pkg/hardwareutils/go.sum
Labels: size/S, lgtm, approved

#1566 🌱 Use real Context and make provisioners context-aware
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/bmceventsubscription_controller.go
  controllers/metal3.io/host_config_data_test.go
  controllers/metal3.io/host_state_machine_test.go
  controllers/metal3.io/hostfirmwaresettings_controller.go
  controllers/metal3.io/preprovisioningimage_controller.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/factory.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/ironic_test.go
  pkg/provisioner/provisioner.go
  pkg/secretutils/secret_manager.go
Labels: lgtm, approved, size/L

#1544 ⚠️ Remove Inspector from all deployments scripts
  config/README.md
  config/components/basic-auth/credentials_patch.yaml
  config/components/basic-auth/kustomization.yaml
  config/overlays/basic-auth_tls/kustomization.yaml
  config/overlays/e2e/kustomization.yaml
  docs/deploying.md
  docs/dev-setup.md
  docs/ironic-authentication.md
  hack/ci-e2e.sh
  ironic-deployment/base/ironic.yaml
  ironic-deployment/components/basic-auth/auth.yaml
  ironic-deployment/components/basic-auth/ironic-inspector-auth-config-tpl
  ironic-deployment/components/basic-auth/kustomization.yaml
  ironic-deployment/components/keepalived/ironic_bmo_configmap.env
  ironic-deployment/components/tls/certificate.yaml
  ironic-deployment/components/tls/tls.yaml
  ironic-deployment/default/ironic_bmo_configmap.env
  ironic-deployment/overlays/basic-auth_tls/basic-auth_tls.yaml
  ironic-deployment/overlays/basic-auth_tls/kustomization.yaml
  ironic-deployment/overlays/e2e/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e/kustomization.yaml
  tools/deploy.sh
  tools/run_local_ironic.sh
Labels: lgtm, approved, size/L

#1567 🌱 Drop dependency on x/exp/slices
  apis/go.mod
  apis/go.sum
  apis/metal3.io/v1alpha1/baremetalhost_validation.go
  go.mod
  hack/e2e/ensure_go.sh
  pkg/provisioner/ironic/ironic.go
Labels: size/S, lgtm, approved
