Repository metal3-io/baremetal-operator, pull requests merged in 2024-10, with the labels that each got.

#1980 :seedling: Revert "use ubuntu-latest rather than hosted 4-core runner"
  .github/workflows/e2e-test.yml
Labels: size/XS, lgtm, approved

#1982 :seedling: bump markdownlint-cli2 to v0.12.0
  hack/markdownlint.sh
Labels: size/XS, lgtm, approved

#1967 🌱 Bump controller runtime to v0.18.5 and CAPI to v1.8.3
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  test/e2e/cert_manager.go
  test/e2e/common.go
  test/go.mod
  test/go.sum
Labels: lgtm, approved, size/L

#1622 🌱 Improve deploy.sh to differentiate between build and run of kustomize
  tools/deploy.sh
Labels: size/XS, lgtm, approved, ok-to-test, lifecycle/stale

#1983 🌱 Fix minikube restart in e2e by trying in a loop
  hack/ci-e2e.sh
Labels: size/XS, lgtm, approved

#1988 🌱 bump golang to 1.22.8
  Dockerfile
  Makefile
  hack/e2e/ensure_go.sh
Labels: size/XS, lgtm, approved

#1991 🌱 make CAPI a pattern in dependabot config
  .github/dependabot.yml
Labels: size/XS, lgtm, approved

#2008 🌱 Add Riccardo and Adam as approvers
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#2007 🌱 Bump kustomize/kyaml v0.18.1 and kustomize/kustomize/v5 to v5.5.0
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, approved, size/L

#2010 🌱 Bump k8s.io/* to v0.31.1, controller-runtime to v0.19.0 and controller-tools to v0.16.3
  apis/go.mod
  apis/go.sum
  apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  config/base/crds/bases/metal3.io_baremetalhosts.yaml
  config/base/crds/bases/metal3.io_bmceventsubscriptions.yaml
  config/base/crds/bases/metal3.io_dataimages.yaml
  config/base/crds/bases/metal3.io_firmwareschemas.yaml
  config/base/crds/bases/metal3.io_hardwaredata.yaml
  config/base/crds/bases/metal3.io_hostfirmwarecomponents.yaml
  config/base/crds/bases/metal3.io_hostfirmwaresettings.yaml
  config/base/crds/bases/metal3.io_hostupdatepolicies.yaml
  config/base/crds/bases/metal3.io_preprovisioningimages.yaml
  config/base/rbac/role.yaml
  config/render/capm3.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/XXL, lgtm, approved

#1936 🌱 Fix minor issues in the API help strings
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  config/base/crds/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
Labels: size/M, lgtm, approved

#1968 🌱 Reuse PR verifier workflow from project-infra
  .github/workflows/pr-verifier.yaml
Labels: size/S, lgtm, approved

#1792 🌱 Added Error message when reconciling loop is triggered more than once
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/bmceventsubscription_controller.go
Labels: size/M, lgtm, approved, ok-to-test

#2014 🌱 Fix misspelling in function name
  controllers/metal3.io/baremetalhost_controller.go
Labels: size/XS, lgtm, approved, ok-to-test

#2026 🌱 Add manifest generation while generating code
  .github/workflows/dependabot.yml
Labels: size/XS, lgtm, approved

#2027 🌱 Move TLS 1.3 from hardcoded default value to a config flag
  config/base/manager.yaml
  main.go
Labels: size/XS, lgtm, approved
