Repository metal3-io/baremetal-operator, pull requests merged in 2024-04, with the labels that each got.

#1640 📖 update releasing docs
  docs/releasing.md
Labels: size/M, lgtm, approved

#1651 :seedling: Update ironic basic-auth-tls overlay
  ironic-deployment/overlays/basic-auth_tls/kustomization.yaml
Labels: size/XS, lgtm, approved

#1623 :sparkles: Add nonbootable iso api
  PROJECT
  apis/metal3.io/v1alpha1/dataimage_types.go
  apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  config/base/crds/bases/metal3.io_dataimages.yaml
  config/base/crds/kustomization.yaml
  config/base/crds/patches/cainjection_in_dataimages.yaml
  config/base/crds/patches/webhook_in_dataimages.yaml
  config/render/capm3.yaml
  config/samples/metal3.io_v1alpha1_dataimage.yaml
Labels: lgtm, approved, size/L

#1638 🌱 Enabled more golangci linters
  .golangci.yaml
  Makefile
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/baremetalhost_types_test.go
  apis/metal3.io/v1alpha1/baremetalhost_validation.go
  apis/metal3.io/v1alpha1/baremetalhost_webhook.go
  apis/metal3.io/v1alpha1/bmceventsubscription_types.go
  apis/metal3.io/v1alpha1/bmceventsubscription_validation.go
  apis/metal3.io/v1alpha1/bmceventsubscription_webhook.go
  apis/metal3.io/v1alpha1/firmwareschema_types.go
  apis/metal3.io/v1alpha1/groupversion_info.go
  apis/metal3.io/v1alpha1/hardwaredata_types.go
  apis/metal3.io/v1alpha1/hostfirmwaresettings_types.go
  apis/metal3.io/v1alpha1/hostfirmwaresettings_types_test.go
  apis/metal3.io/v1alpha1/preprovisioningimage_types.go
  apis/metal3.io/v1alpha1/profile/profile.go
  cmd/make-virt-host/main.go
  config/base/crds/bases/metal3.io_baremetalhosts.yaml
  config/base/crds/bases/metal3.io_firmwareschemas.yaml
  config/base/crds/bases/metal3.io_hardwaredata.yaml
  config/base/crds/bases/metal3.io_hostfirmwaresettings.yaml
  config/base/crds/bases/metal3.io_preprovisioningimages.yaml
  config/render/capm3.yaml
  controllers/metal3.io/action_result.go
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/bmceventsubscription_controller.go
  controllers/metal3.io/host_config_data.go
  controllers/metal3.io/host_config_data_test.go
  pkg/hardwareutils/bmc/access.go
  pkg/hardwareutils/bmc/access_test.go
  pkg/hardwareutils/bmc/credentials.go
  pkg/hardwareutils/bmc/errors.go
  pkg/hardwareutils/bmc/ibmc.go
  pkg/hardwareutils/bmc/idrac.go
  pkg/hardwareutils/bmc/idrac_virtualmedia.go
  pkg/hardwareutils/bmc/ilo4.go
  pkg/hardwareutils/bmc/ilo5.go
  pkg/hardwareutils/bmc/ipmi.go
  pkg/hardwareutils/bmc/irmc.go
  pkg/hardwareutils/bmc/redfish.go
  pkg/hardwareutils/bmc/redfish_virtualmedia.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/clients/features.go
  pkg/provisioner/ironic/dependencies.go
  pkg/provisioner/ironic/devicehints/devicehints.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/testserver/ironic.go
  pkg/provisioner/ironic/testserver/server.go
  test/e2e/common.go
  test/e2e/e2e_suite_test.go
  test/e2e/provisioning_and_annotation_test.go
Labels: size/XL, lgtm, approved

#1520 🌱 Test virtualmedia booting
  hack/ci-e2e.sh
  test/e2e/common.go
  test/e2e/config/bmcs-ipmi.yaml
  test/e2e/config/bmcs-redfish-virtualmedia.yaml
  test/e2e/config/bmcs-redfish.yaml
  test/e2e/config/fixture.yaml
  test/e2e/config/ironic.yaml
  test/e2e/live_iso_test.go
  test/go.mod
  tools/bmh_test/clean_local_bmh_test_setup.sh
Labels: lgtm, approved, size/L

#1652 :book: Remove redundant deploy instruction
  docs/configuration.md
  docs/deploying.md
Labels: lgtm, approved, size/L

#1641 🌱 check for skipCleanup before running cleanup of test resources
  test/e2e/basic_ops_test.go
  test/e2e/external_inspection_test.go
  test/e2e/inspection_test.go
  test/e2e/live_iso_test.go
  test/e2e/provisioning_and_annotation_test.go
  test/e2e/re_inspection_test.go
Labels: size/S, lgtm, approved, ok-to-test

#1559 ✨ HostFirmwareComponents CRD and Controller & Tests
  PROJECT
  apis/metal3.io/v1alpha1/hostfirmwarecomponents_types.go
  apis/metal3.io/v1alpha1/hostfirmwarecomponents_types_test.go
  config/base/crds/bases/metal3.io_hostfirmwarecomponents.yaml
  config/base/crds/kustomization.yaml
  config/base/crds/patches/cainjection_in_hostfirmwarecomponents.yaml
  config/base/crds/patches/webhook_in_hostfirmwarecomponents.yaml
  config/base/rbac/hostfirmwarecomponents_editor_role.yaml
  config/base/rbac/hostfirmwarecomponents_viewer_role.yaml
  config/base/rbac/role.yaml
  config/render/capm3.yaml
  config/samples/metal3.io_v1alpha1_hostfirmwarecomponents.yaml
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/host_state_machine_test.go
  controllers/metal3.io/hostfirmwarecomponents_controller.go
  controllers/metal3.io/hostfirmwarecomponents_test.go
  main.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/provisioner.go
Labels: size/XXL, lgtm, approved

#1654 🌱 add workflow to approve actions on PR change
  .github/workflows/pr-gh-workflow-approve.yaml
Labels: size/M, lgtm, approved

#1657 🌱 Make use of the new liveness/readiness probe scripts
  ironic-deployment/base/ironic.yaml
  ironic-deployment/components/tls/tls.yaml
Labels: size/S, lgtm, approved

#1658 🌱 Bump golang.org/x/net to v0.23.0 and golang to v1.21.9
  Dockerfile
  Makefile
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/e2e/ensure_go.sh
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/M, lgtm, approved

#1656 🌱 E2E: Prepare for emulator based on protocol
  hack/ci-e2e.sh
Labels: size/M, lgtm, approved

#1661 🌱 E2E: Cleanup emulator variable
  hack/ci-e2e.sh
Labels: size/M, lgtm, approved

#1561 🌱 E2E: Run multiple BMO upgrade tests in sequence
  hack/ci-e2e.sh
  ironic-deployment/overlays/e2e-with-inspector/ironic-patch.yaml
  ironic-deployment/overlays/e2e-with-inspector/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-with-inspector/kustomization.yaml
  test/e2e/config/fixture.yaml
  test/e2e/config/ironic.yaml
  test/e2e/e2e_config.go
  test/e2e/e2e_suite_test.go
  test/e2e/upgrade_test.go
Labels: size/XL, lgtm, approved

#1655 🐛 Fixes for HostFirmwareComponents
  controllers/metal3.io/baremetalhost_controller.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/provisioner.go
Labels: lgtm, approved, size/L

#1615 🌱Added unit tests for baremetalHostTypes and bmceventSubscriptionController
  apis/metal3.io/v1alpha1/baremetalhost_types_test.go
  controllers/metal3.io/bmceventsubscription_controller_test.go
Labels: lgtm, approved, size/L, ok-to-test

#1662 :seedling: Add e2e ironic upgrades
  hack/ci-e2e.sh
  ironic-deployment/overlays/e2e-release-24.0-with-inspector/ironic-patch.yaml
  ironic-deployment/overlays/e2e-release-24.0-with-inspector/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-24.0-with-inspector/kustomization.yaml
  test/e2e/config/ironic.yaml
  test/e2e/upgrade_test.go
Labels: lgtm, approved, size/L

#1676 🌱 bump gophercloud/v2 to beta.3 + some commits to fix go.mod
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#1678 🌱 Bump controller-runtime to v0.16.3 and CAPI to v1.6.4
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, lgtm, approved

#1679 🌱 Pinning ironic image release-24.1
  ironic-deployment/base/ironic.yaml
Labels: size/XS, lgtm, approved

#1681 :seedling: Remove capm3_e2e dependency from bmo E2E
  test/e2e/basic_ops_test.go
  test/e2e/common.go
  test/e2e/live_iso_test.go
  test/e2e/provisioning_and_annotation_test.go
  test/e2e/re_inspection_test.go
  test/go.mod
  test/go.sum
Labels: size/M, lgtm, approved

#1680 :seedling: Fix mismatched versions between imported and cli ginkgo
  Makefile
Labels: size/XS, lgtm, approved

#1684 🌱 Remove redundant Provisioner from HostFirmwareSettings tests
  controllers/metal3.io/hostfirmwaresettings_test.go
  pkg/provisioner/fixture/fixture.go
Labels: size/M, lgtm, approved

#1674 🌱 Update build status for release-0.4
  README.md
Labels: size/XS, lgtm, approved

#1688 🌱 Update CI triggers after migrating to prow jenkins operator
  README.md
Labels: size/M, lgtm, approved, ok-to-test

#1694 🌱 Update readme on test triggers on release-0.6
  README.md
Labels: size/S, lgtm, approved, ok-to-test

#1691 🌱 improve hack/verify-release.sh script
  hack/verify-release.sh
Labels: lgtm, approved, size/L, ok-to-test

#1594 :sparkles: Attach non-bootable iso to BareMetalHost
  PROJECT
  apis/metal3.io/v1alpha1/dataimage_types.go
  apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  config/base/rbac/dataimage_editor_role.yaml
  config/base/rbac/dataimage_viewer_role.yaml
  config/base/rbac/role.yaml
  config/render/capm3.yaml
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/dataimage_controller.go
  controllers/metal3.io/host_state_machine_test.go
  main.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/clients/features.go
  pkg/provisioner/ironic/clients/features_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/provisioner.go
Labels: size/XL, lgtm, approved

#1693 🌱 backported fixes for Makefile and release workflow
  .github/workflows/release.yaml
  Makefile
  hack/tools/release/notes.go
Labels: size/M, lgtm, approved, ok-to-test

#1687 🌱 Add Slack notification for image build workflow failure
  .github/workflows/build-images-action.yml
Labels: size/S, lgtm, approved, ok-to-test

#1696 🌱 Update to the Gophercloud beta.4+commits
  go.mod
  go.sum
  pkg/provisioner/ironic/delete_test.go
  pkg/provisioner/ironic/inspecthardware_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/power_test.go
  pkg/provisioner/ironic/updatehardwarestate_test.go
  pkg/provisioner/ironic/validatemanagementaccess_test.go
Labels: lgtm, approved, size/L, ok-to-test

#1695 🐛 Fix Status logic for HostFirmwareComponents
  apis/metal3.io/v1alpha1/hostfirmwarecomponents_types.go
  config/base/crds/bases/metal3.io_hostfirmwarecomponents.yaml
  config/render/capm3.yaml
  controllers/metal3.io/hostfirmwarecomponents_controller.go
  controllers/metal3.io/hostfirmwarecomponents_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/provisioner.go
Labels: size/M, lgtm, approved, ok-to-test

#1702 🐛 PreprovisioningImage should not be created on poweroff before delete
  controllers/metal3.io/baremetalhost_controller.go
Labels: size/XS, lgtm, approved, ok-to-test

#1700 🌱 bump golang to 1.21.9, and some modules
  Dockerfile
  Makefile
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, approved, size/L

#1703 🌱 bump minikube to v1.33.0
  hack/e2e/ensure_minikube.sh
Labels: size/XS, lgtm, approved, ok-to-test
