Repository metal3-io/baremetal-operator, pull requests merged in 2024-06, with the labels that each got.

#1671 🌱 Bump golang to v1.22
  .github/workflows/e2e-fixture-test.yml
  .github/workflows/release.yaml
  .golangci.yaml
  Dockerfile
  Makefile
  Tiltfile
  apis/go.mod
  go.mod
  hack/e2e/ensure_go.sh
  hack/generate.sh
  hack/golint.sh
  hack/gomod.sh
  hack/tools/go.mod
  hack/unit.sh
  pkg/hardwareutils/go.mod
  test/go.mod
Labels: size/M, lgtm, approved, ok-to-test

#1759 🌱 Bump CAPI to v1.6.5 and golang to 1.21.10
  Dockerfile
  Makefile
  hack/e2e/ensure_go.sh
  test/go.mod
  test/go.sum
Labels: size/S, lgtm, approved

#1728 🌱 E2E: Run as github workflow
  .github/workflows/e2e-test-periodic.yml
  .github/workflows/e2e-test-pull.yaml
  .github/workflows/e2e-test.yml
  hack/ci-e2e.sh
  hack/e2e/ensure_go.sh
Labels: lgtm, approved, size/L

#1760 :seedling: Uplift CAPI to v1.7.2
  test/go.mod
  test/go.sum
Labels: size/XL, lgtm, approved

#1765 🌱 Add periodic jobs for optional tests and release branches
  .github/workflows/e2e-test-optional-periodic-release-0.5.yml
  .github/workflows/e2e-test-optional-periodic-release-0.6.yml
  .github/workflows/e2e-test-optional-periodic.yml
  .github/workflows/e2e-test-periodic-main.yml
  .github/workflows/e2e-test-periodic-release-0.5.yml
  .github/workflows/e2e-test-periodic-release-0.6.yml
  .github/workflows/e2e-test.yml
Labels: lgtm, approved, size/L

#1771 🌱 E2E: Run as github workflow
  .github/workflows/e2e-test-periodic.yml
  .github/workflows/e2e-test-pull.yaml
  .github/workflows/e2e-test.yml
  hack/ci-e2e.sh
  hack/e2e/ensure_go.sh
Labels: lgtm, approved, size/L

#1772 🌱 [backport] Workflow pipeline with unit tests
  .github/workflows/e2e-fixture-test.yml
  .github/workflows/e2e-test-pull.yaml
  .github/workflows/e2e-test.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/pipeline.yml
  .github/workflows/unit.yml
Labels: lgtm, approved, size/L

#1773 🌱 [backport] workflow pipeline with unit tests
  .github/workflows/e2e-fixture-test.yml
  .github/workflows/e2e-test-periodic.yml
  .github/workflows/e2e-test-pull.yaml
  .github/workflows/e2e-test.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/pipeline.yml
  .github/workflows/unit.yml
Labels: lgtm, approved, size/L

#1774 🌱 Add unit test for LoadAuth funciton in auth.go
  pkg/provisioner/ironic/clients/auth_test.go
Labels: lgtm, approved, size/L, ok-to-test

#1778 🌱 bump golang to 1.21.11
  Dockerfile
  Makefile
  hack/e2e/ensure_go.sh
Labels: size/XS, lgtm, approved

#1777 🌱 bump golang to 1.21.11
  Dockerfile
  Makefile
  hack/e2e/ensure_go.sh
Labels: size/XS, lgtm, approved

#1780 🐛 fix htpasswd generation in run_local_ironic.sh
  tools/run_local_ironic.sh
Labels: size/XS, lgtm, approved

#1782 🌱 bump golang to 1.22.4
  Dockerfile
  Makefile
  hack/e2e/ensure_go.sh
Labels: size/XS, lgtm, approved

#1784 🌱 bump capi to 1.7.3
  test/go.mod
  test/go.sum
Labels: size/M, lgtm, approved

#1786 :bug: Fix incorrect htpasswd file generation
  tools/deploy.sh
Labels: size/XS, lgtm, approved

#1790 🌱 limit running BMO e2e periodics to metal3-io repo
  .github/workflows/e2e-test-optional-periodic-release-0.5.yml
  .github/workflows/e2e-test-optional-periodic-release-0.6.yml
  .github/workflows/e2e-test-optional-periodic.yml
  .github/workflows/e2e-test-periodic-main.yml
  .github/workflows/e2e-test-periodic-release-0.5.yml
  .github/workflows/e2e-test-periodic-release-0.6.yml
Labels: size/M, lgtm, approved

#1789 🐛 fix make install and make uninstall
  Makefile
Labels: size/XS, lgtm, approved, ok-to-test

#1791 :seedling: Always upload test artifacts, even if the tests fail
  .github/workflows/e2e-test.yml
Labels: size/XS, lgtm, approved

#1794 📖 add openssf best practices badge to README
  README.md
Labels: size/XS, lgtm, approved
