Repository metal3-io/baremetal-operator, pull requests merged in 2024-08, with the labels that each got.

#1838 🌱 fix dependabot config on api directory location
  .github/dependabot.yml
Labels: size/XS, lgtm, approved

#1837 :bug: Fix libvirt missing in dependabot build wf
  .github/workflows/dependabot.yml
Labels: size/XS, lgtm, approved

#1819 🌱 Do not mark hardwareProfile as required in the status
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  config/base/crds/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
Labels: size/XS, lgtm, approved

#1718 :seedling: Bump kustomize version from v4 to v5
  Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  ironic-deployment/components/keepalived/kustomization.yaml
  tools/deploy.sh
Labels: lgtm, approved, size/L, ok-to-test

#1861 :seedling: Move container build to gh runner
  .github/workflows/build-images-action.yml
Labels: size/M, lgtm, approved

#1868 :seedling: Make container build only run for metal3.io repo
  .github/workflows/build-images-action.yml
Labels: size/XS, lgtm, approved

#1824 🌱 Bump golang to 1.22 in release 0.6
  .github/workflows/release.yaml
  .golangci.yaml
  Dockerfile
  Makefile
  Tiltfile
  hack/e2e/ensure_go.sh
  hack/generate.sh
  hack/golint.sh
  hack/gomod.sh
  hack/unit.sh
Labels: size/S, lgtm, approved

#1866 :bug: Resolve BMC hostname, not address
  pkg/provisioner/ironic/ironic.go
Labels: size/XS, lgtm, approved

#1884 🌱 bump golang to 1.22.6
  Dockerfile
  hack/e2e/ensure_go.sh
Labels: size/XS, lgtm, approved

#1885 🌱 bump golang to 1.22.6
  Dockerfile
  Makefile
  hack/e2e/ensure_go.sh
Labels: size/XS, lgtm, approved

#1886 🌱 bump and sync go dependencies
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/M, lgtm, approved

#1883 🌱 bump golang to 1.22.6
  Dockerfile
  Makefile
  hack/e2e/ensure_go.sh
Labels: size/XS, lgtm, approved

#1882 🌱 bump and sync go dependencies
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/M, lgtm, approved

#1888 🌱 fix verify-release.sh to understand go directive better
  hack/verify-release.sh
Labels: size/XS, lgtm, approved

#1878 🌱 bump k8s.io/* deps to v0.27.16
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, approved, size/L

#1893 🌱 bump cert-manager to 1.10.2
  test/go.mod
  test/go.sum
Labels: size/XS, lgtm, approved

#1798 📖 Document backporting rules for Go lang minor versions for images
  CONTRIBUTING.md
Labels: size/M, lgtm, approved

#1911 🌱 add dependabot config for release-0.8 branch
  .github/dependabot.yml
Labels: size/M, lgtm, approved

#1924 🌱 fix dependabot ignore rules for 0.8 branch
  .github/dependabot.yml
Labels: size/S, lgtm, approved
