Repository metal3-io/baremetal-operator, pull requests merged in 2024-03, with the labels that each got.

#1572 🌱 E2E: Workaround issue with minikube image load
  hack/ci-e2e.sh
Labels: size/XS, lgtm, approved

#1570 🌱 Update OWNERS file
  OWNERS
Labels: size/S, lgtm, approved

#1580 🌱 add build image action to release-0.5
  .github/workflows/build-images-action.yml
Labels: size/M, lgtm, approved

#1581 🌱 add build images action to release-0.4
  .github/workflows/build-images-action.yml
Labels: size/M, lgtm, approved

#1585 🌱 Bump go to v1.21.7
  Dockerfile
  Makefile
Labels: size/XS, lgtm, approved

#1584 🌱 Bump go to v1.21.7
  Dockerfile
  Makefile
Labels: size/XS, lgtm, approved

#1587 🌱 Harden release-0.4 against ironic inspector removal
  config/default/ironic.env
  config/render/capm3.yaml
  hack/ironic_ci.env
  ironic-deployment/base/ironic.yaml
  ironic-deployment/components/keepalived/ironic_bmo_configmap.env
  ironic-deployment/default/ironic_bmo_configmap.env
  tools/run_local_ironic.sh
Labels: size/S, lgtm, approved

#1588 🌱 Bump golangci-lint to v1.56.2
  .github/workflows/golangci-lint.yml
  Makefile
Labels: size/XS, lgtm, approved

#1593 :seedling: Move e2e config functionality to a separate file
  test/e2e/common.go
  test/e2e/e2e_config.go
Labels: lgtm, approved, size/L

#1595 🌱 Bump CAPI to v1.5.6
  apis/go.mod
  apis/go.sum
  docs/dev-setup.md
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, lgtm, approved

#1579 :seedling: Add unit test on features.go
  pkg/provisioner/ironic/clients/features_test.go
Labels: size/M, lgtm, approved, ok-to-test

#1578 :seedling: E2E: Add labels on test coverage
  test/e2e/basic_ops_test.go
  test/e2e/external_inspection_test.go
  test/e2e/inspection_test.go
  test/e2e/live_iso_test.go
  test/e2e/provisioning_and_annotation_test.go
  test/e2e/re_inspection_test.go
  test/e2e/upgrade_test.go
Labels: lgtm, approved, size/L, ok-to-test

#1599 🌱 add release-* as branch trigger to e2e fixture workflow
  .github/workflows/e2e-fixture-test.yml
Labels: size/XS, lgtm, approved

#1598 🌱 fix e2e fixture workflow trigger
  .github/workflows/e2e-fixture-test.yml
Labels: size/XS, lgtm, approved

#1603 🌱 Stop setting IRONIC_FAST_TRACK by default
  config/default/ironic.env
  config/render/capm3.yaml
  hack/ironic_ci.env
  ironic-deployment/components/keepalived/ironic_bmo_configmap.env
  ironic-deployment/default/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e/ironic_bmo_configmap.env
Labels: size/XS, lgtm, approved

#1605 🌱 Remove last traces of auth-config
  docs/deploying.md
  hack/ci-e2e.sh
  ironic-deployment/components/basic-auth/auth.yaml
  ironic-deployment/components/basic-auth/kustomization.yaml
  ironic-deployment/overlays/basic-auth_tls/basic-auth_tls.yaml
  ironic-deployment/overlays/basic-auth_tls/kustomization.yaml
  ironic-deployment/overlays/e2e/kustomization.yaml
  tools/deploy.sh
  tools/run_local_ironic.sh
Labels: size/M, lgtm, approved

#1608 🐛 bump google.golang.org/protobuf to v1.33.0
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, lgtm, approved

#1610 🌱 bump shellcheck to v0.10.0
  hack/shellcheck.sh
Labels: size/S, lgtm, approved

#1611 🌱 bump shellcheck to v0.10.0
  hack/shellcheck.sh
Labels: size/S, lgtm, approved

#1609 🌱 bump shellcheck to v0.10.0
  hack/shellcheck.sh
Labels: size/S, lgtm, approved

#1613 🐛 bump google.golang.org/protobuf to v1.33.0
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/S, lgtm, approved

#1612 🐛 bump google.golang.org/protobuf to v1.33.0
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, lgtm, approved

#1614 🌱 add golang base image check to verify-release.sh
  hack/verify-release.sh
Labels: size/M, lgtm, approved

#1619 🌱 Bump CAPI to v1.6.3
  test/go.mod
  test/go.sum
Labels: size/M, lgtm, approved

#1621 🌱 Bump CAPI to v1.5.7
  test/go.mod
  test/go.sum
Labels: size/M, lgtm, approved

#1633 🌱 bump golang to 1.21.8
  Dockerfile
  Makefile
Labels: size/XS, lgtm, approved

#1624 ⚠️ Remove ibmc and idrac drivers
  apis/metal3.io/v1alpha1/baremetalhost_validation_test.go
  docs/api.md
  pkg/hardwareutils/bmc/access.go
  pkg/hardwareutils/bmc/access_test.go
  pkg/hardwareutils/bmc/ibmc.go
  pkg/hardwareutils/bmc/idrac.go
  pkg/hardwareutils/bmc/idrac_virtualmedia.go
Labels: size/XL, lgtm, approved

#1632 🌱 remove obsolete Makefile related gofmt, gosec scripts
  Makefile
  hack/gofmt.sh
  hack/gosec.sh
Labels: size/M, lgtm, approved, ok-to-test

#1636 🌱 add support for beta/rc releases in release notes
  .github/workflows/release.yaml
  Makefile
  hack/tools/release/notes.go
Labels: size/M, lgtm, approved
