Repository metal3-io/baremetal-operator, pull requests merged in 2025-04, with the labels that each got.

#2375 :seedling: bump golang to v1.23.8 and x/net to v0.38.0
  Dockerfile
  Makefile
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/e2e/ensure_go.sh
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/M, lgtm, approved

#2376 :seedling: bump golang to v1.23.8 and x/net to v0.38.0
  Dockerfile
  Makefile
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/e2e/ensure_go.sh
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/M, lgtm, approved

#2373 :seedling: do not bump major version of github actions
  .github/dependabot.yml
Labels: size/S, lgtm, approved

#2380 🌱 Enable usetesting linter in golangci-lint
  .golangci.yaml
  pkg/provisioner/ironic/clients/auth_test.go
Labels: size/XS, lgtm, approved, ok-to-test

#2381 :bug: Fix few errors when making beta release notes
  hack/tools/release/notes.go
Labels: size/S, lgtm, approved

#2383 🌱 Enable testifylint linter in golangci-lint
  .gitignore
  .golangci.yaml
  apis/metal3.io/v1alpha1/hostfirmwarecomponents_types_test.go
  controllers/metal3.io/baremetalhost_controller_test.go
  controllers/metal3.io/host_config_data_test.go
  controllers/metal3.io/host_state_machine_test.go
  controllers/metal3.io/hostfirmwarecomponents_test.go
  controllers/metal3.io/hostfirmwaresettings_test.go
  pkg/provisioner/ironic/adopt_test.go
  pkg/provisioner/ironic/bios_test.go
  pkg/provisioner/ironic/clients/client_test.go
  pkg/provisioner/ironic/clients/updateopts_test.go
  pkg/provisioner/ironic/configdrive_test.go
  pkg/provisioner/ironic/delete_test.go
  pkg/provisioner/ironic/factory_test.go
  pkg/provisioner/ironic/inspecthardware_test.go
  pkg/provisioner/ironic/ironic_test.go
  pkg/provisioner/ironic/power_test.go
  pkg/provisioner/ironic/prepare_test.go
  pkg/provisioner/ironic/provision_test.go
  pkg/provisioner/ironic/provisioncapacity_test.go
  pkg/provisioner/ironic/ready_test.go
  pkg/provisioner/ironic/register_test.go
  pkg/provisioner/ironic/servicing_test.go
  pkg/provisioner/ironic/updatehardwarestate_test.go
Labels: lgtm, approved, size/L, ok-to-test

#2384 :seedling: add labels to Dockerfile
  Dockerfile
Labels: size/S, lgtm, approved

#2389 :seedling: make osv-scanner scan run daily
  .github/workflows/osv-scanner-scan.yml
Labels: size/XS, lgtm, approved

#2391 :seedling: Bump CAPI 1.10.0-beta.0 and Kubernetes api 0.32.3 and controller-runtime 0.20.4
  apis/go.mod
  apis/go.sum
  apis/metal3.io/v1alpha1/baremetalhost_validation.go
  apis/metal3.io/v1alpha1/baremetalhost_validation_test.go
  apis/metal3.io/v1alpha1/baremetalhost_webhook.go
  apis/metal3.io/v1alpha1/baremetalhost_webhook_test.go
  apis/metal3.io/v1alpha1/bmceventsubscription_validation.go
  apis/metal3.io/v1alpha1/bmceventsubscription_validation_test.go
  apis/metal3.io/v1alpha1/bmceventsubscription_webhook.go
  apis/metal3.io/v1alpha1/bmceventsubscription_webhook_test.go
  go.mod
  go.sum
  main.go
  test/e2e/basic_ops_test.go
  test/e2e/common.go
  test/e2e/external_inspection_test.go
  test/e2e/inspection_test.go
  test/e2e/live_iso_test.go
  test/e2e/provisioning_and_annotation_test.go
  test/e2e/re_inspection_test.go
  test/go.mod
  test/go.sum
Labels: size/XL, lgtm, approved

#2397 :seedling: Bump CAPI to 1.10.0-rc.0
  test/go.mod
  test/go.sum
Labels: size/S, lgtm, approved

#2398 :rocket: Release v0.10.0-beta.0
  releasenotes/v0.10.0-beta.0.md
Labels: lgtm, approved, size/L

#2393 🌱Enable intrange linter in golangci-lint
  .golangci.yaml
  cmd/make-bm-worker/templates/templates_test.go
  test/e2e/common.go
Labels: size/XS, lgtm, approved, ok-to-test

#2336 :sparkles: Use standard GetVirtualMedia API for checking dataImage status
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/dataimage_controller.go
  controllers/metal3.io/host_state_machine_test.go
  go.mod
  go.sum
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/clients/features.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/provisioner.go
Labels: lgtm, approved, size/L

#2403 🌱 Minor fix release workflow
  .github/workflows/release.yaml
Labels: size/XS, lgtm, approved

#2407 🌱 Add Adil and Peppi-lotta as reviewers
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#2404 🌱 Makefile: do not explicit include ./internal/
  Makefile
Labels: size/XS, lgtm, approved

#2405 🌱 Refactoring: move ./controllers to ./internal/controller
  internal/controller/metal3.io/action_result.go
  internal/controller/metal3.io/action_result_test.go
  internal/controller/metal3.io/baremetalhost_controller.go
  internal/controller/metal3.io/baremetalhost_controller_test.go
  internal/controller/metal3.io/bmceventsubscription_controller.go
  internal/controller/metal3.io/bmceventsubscription_controller_test.go
  internal/controller/metal3.io/controller_test.go
  internal/controller/metal3.io/dataimage_controller.go
  internal/controller/metal3.io/demo_test.go
  internal/controller/metal3.io/errors.go
  internal/controller/metal3.io/host_config_data.go
  internal/controller/metal3.io/host_config_data_test.go
  internal/controller/metal3.io/host_state_machine.go
  internal/controller/metal3.io/host_state_machine_test.go
  internal/controller/metal3.io/hostfirmwarecomponents_controller.go
  internal/controller/metal3.io/hostfirmwarecomponents_test.go
  internal/controller/metal3.io/hostfirmwaresettings_controller.go
  internal/controller/metal3.io/hostfirmwaresettings_test.go
  internal/controller/metal3.io/metrics.go
  internal/controller/metal3.io/preprovisioningimage_controller.go
  internal/controller/metal3.io/preprovisioningimage_controller_test.go
  main.go
  tilt-provider.json
Labels: size/XS, lgtm, approved

#2406 🌱 Bump cluster-api/test module to v1.10.0-rc.0 in hack/tools
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/S, lgtm, approved

#2416 🌱 Bump CAPI to v1.10.0
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, lgtm, approved

#2417 🚀 Release v0.10.0
  releasenotes/v0.10.0.md
Labels: lgtm, approved, size/L

#2419 :seedling: Pin ironic to version 29.0
  ironic-deployment/base/ironic.yaml
Labels: size/XS, lgtm, approved

#2426 :rocket: Release v0.10.1
  releasenotes/v0.10.1.md
Labels: size/S, lgtm, approved
