Repository metal3-io/baremetal-operator, pull requests merged in 2025-03, with the labels that each got.

#2113 🌱 e2e: Revert temporary pinning of Ironic
  ironic-deployment/overlays/e2e/kustomization.yaml
Labels: size/XS, lgtm, approved

#2280 :bug: bump actions/cache to v4.2.2
  .github/workflows/dependabot.yml
Labels: size/XS, lgtm, approved

#2282 :seedling: bump golang to 1.23.7
  Dockerfile
  Makefile
  hack/e2e/ensure_go.sh
Labels: size/XS, lgtm, approved

#2276 🌱 E2E: Use kind instead of minikube
  .gitignore
  config/overlays/e2e-release-0.5/ironic.env
  config/overlays/e2e-release-0.6/ironic.env
  config/overlays/e2e/ironic.env
  hack/ci-e2e.sh
  hack/clean-e2e.sh
  hack/e2e/ensure_minikube.sh
  hack/e2e/net.xml
  ironic-deployment/components/tls/certificate.yaml
  ironic-deployment/overlays/e2e-release-24.0-with-inspector/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-24.1/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-24.1/kustomization.yaml
  ironic-deployment/overlays/e2e-with-inspector/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-with-inspector/kustomization.yaml
  ironic-deployment/overlays/e2e/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e/kustomization.yaml
  test/e2e/config/fixture.yaml
  test/e2e/config/ironic.yaml
  test/e2e/e2e_config.go
  test/e2e/e2e_suite_test.go
  test/e2e/upgrade_test.go
  test/go.mod
  tools/bmh_test/vm2vbmc.sh
Labels: lgtm, approved, size/L

#2277 🌱 E2E: Remove ensure_kind.sh script
  hack/ci-e2e.sh
  hack/clean-e2e.sh
  hack/e2e/ensure_kind.sh
Labels: size/M, lgtm, approved

#2281 :bug: bump actions/cache to v4.2.2
  .github/workflows/dependabot.yml
Labels: size/XS, lgtm, approved

#2229 ✨ Add support for Disablepoweroff
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/baremetalhost_validation.go
  apis/metal3.io/v1alpha1/baremetalhost_validation_test.go
  config/base/crds/bases/metal3.io_baremetalhosts.yaml
  config/render/capm3.yaml
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/baremetalhost_controller_test.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/clients/features.go
  pkg/provisioner/ironic/clients/features_test.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/register.go
  pkg/provisioner/ironic/register_test.go
  pkg/provisioner/ironic/testserver/ironic.go
  pkg/provisioner/provisioner.go
Labels: lgtm, approved, size/L

#2295 🌱 E2E: Fix ironic overlays for 25.0 and 26.0
  ironic-deployment/overlays/e2e-release-25.0/kustomization.yaml
  ironic-deployment/overlays/e2e-release-26.0/kustomization.yaml
Labels: size/S, lgtm, approved

#2296 :seedling: bump local hack scripts to basic-checks:golang-1.23
  hack/generate.sh
  hack/gomod.sh
Labels: size/XS, lgtm, approved

#2302 🌱 E2E: Fix kustomization for Ironic with inspector
  config/overlays/e2e-release-0.4/ironic.env
  ironic-deployment/overlays/e2e-release-24.0-with-inspector/kustomization.yaml
  ironic-deployment/overlays/e2e-with-inspector/kustomization.yaml
Labels: size/M, lgtm, approved

#2304 :seedling: fix dependabot testing issues by re-adding "edited"
  .github/workflows/lint-docs.yaml
  .github/workflows/pipeline.yml
  .github/workflows/pr-gh-workflow-approve.yaml
  .github/workflows/pr-verifier.yaml
  .github/workflows/unit.yml
Labels: size/XS, lgtm, approved

#2303 🌱 Replace deprecated pkg/errors with stdlib in provisioner/ironic
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/raid.go
  pkg/provisioner/ironic/register.go
Labels: size/M, lgtm, approved

#2315 :bug: update rescue iso used for e2e tests
  hack/ci-e2e.sh
Labels: size/XS, lgtm, approved

#2316 :bug: bump x/net, x/crypto and x/oauth2
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, approved, size/L

#2318 :bug: bump x/net, x/crypto and x/oauth2
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, approved, size/L

#2317 :bug: bump x/net, x/crypto and x/oauth2
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, approved, size/L

#2321 :warning: Only accept HTTPHeadersRef in same namespace
  apis/metal3.io/v1alpha1/bmceventsubscription_validation.go
  apis/metal3.io/v1alpha1/bmceventsubscription_validation_test.go
  controllers/metal3.io/bmceventsubscription_controller.go
  controllers/metal3.io/bmceventsubscription_controller_test.go
Labels: lgtm, approved, size/L

#2322 :warning: Only accept HTTPHeadersRef in same namespace
  apis/metal3.io/v1alpha1/bmceventsubscription_validation.go
  apis/metal3.io/v1alpha1/bmceventsubscription_validation_test.go
  controllers/metal3.io/bmceventsubscription_controller.go
  controllers/metal3.io/bmceventsubscription_controller_test.go
Labels: lgtm, approved, size/L

#2323 :rocket: Release v0.9.1
  releasenotes/v0.9.1.md
Labels: size/M, lgtm, approved

#2324 :rocket: Release v0.8.1
  releasenotes/v0.8.1.md
Labels: size/M, lgtm, approved

#2326 :seedling: group all github action bumps into single PR
  .github/dependabot.yml
Labels: size/S, lgtm, approved

#2329 🌱 Move @mquhuy to emeritus reviewers
  OWNERS
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#2264 :bug: Define some IPA (downloader) related variables
  tools/run_local_ironic.sh
Labels: size/XS, lgtm, approved

#2331 :seedling: bump tj-actions/changed-files to v46.0.1
  .github/workflows/release.yaml
Labels: size/XS, lgtm, approved

#2325 :bug: fix broken release process
  .github/workflows/release.yaml
  Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/release/notes.go
Labels: lgtm, approved, size/L

#2333 :bug: Handle dataImage before reboot annotation to prevent annotation removal before all actions are complete
  controllers/metal3.io/baremetalhost_controller.go
Labels: size/S, lgtm, approved

#2339 :seedling: update osv-scanner to v2.0.0
  .github/workflows/osv-scanner-scan.yml
  hack/verify-release.sh
Labels: size/M, lgtm, approved

#2335 🌱 Bump golangci-lint to v1.64.7
  .github/workflows/golangci-lint.yml
  .golangci.yaml
  Makefile
Labels: size/S, lgtm, approved

#2350 :seedling: update the used linters list
  .golangci.yaml
Labels: size/S, lgtm, approved

#2266 🌱 E2E: Avoid net-booting VMs unintentionally
  test/vbmctl/main.go
  test/vbmctl/templates/VM.xml.tpl
Labels: size/S, lgtm, approved

#2228 :seedling: Remove keepalived from BMO repository
  .github/workflows/build-images-action.yml
  .github/workflows/release.yaml
  .gitignore
  docs/releasing.md
  resources/keepalived-docker/Dockerfile
  resources/keepalived-docker/configure-nonroot.sh
  resources/keepalived-docker/manage-keepalived.sh
  resources/keepalived-docker/sample.keepalived.conf
Labels: lgtm, approved, size/L
