Repository metal3-io/baremetal-operator, pull requests merged in 2025-02, with the labels that each got.

#2222 🌱 Switch e2e to kind
  .github/workflows/e2e-fixture-test.yml
  .gitignore
  config/overlays/e2e-release-0.4/ironic.env
  config/overlays/e2e-release-0.4/kustomization.yaml
  config/overlays/e2e-release-0.5/ironic.env
  config/overlays/e2e-release-0.5/kustomization.yaml
  config/overlays/e2e-release-0.6/ironic.env
  config/overlays/e2e-release-0.8/ironic.env
  config/overlays/e2e/ironic.env
  config/overlays/fixture-release-0.4/kustomization.yaml
  config/overlays/fixture-release-0.5/kustomization.yaml
  hack/ci-e2e.sh
  hack/clean-e2e.sh
  hack/e2e/ensure_kind.sh
  hack/e2e/ensure_minikube.sh
  hack/e2e/net.xml
  ironic-deployment/components/tls/certificate.yaml
  ironic-deployment/overlays/e2e-release-24.0-with-inspector/ironic-patch.yaml
  ironic-deployment/overlays/e2e-release-24.0-with-inspector/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-24.0-with-inspector/kustomization.yaml
  ironic-deployment/overlays/e2e-release-24.1/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-24.1/kustomization.yaml
  ironic-deployment/overlays/e2e-release-25.0/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-25.0/kustomization.yaml
  ironic-deployment/overlays/e2e-release-26.0/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-26.0/kustomization.yaml
  ironic-deployment/overlays/e2e-with-inspector/ironic-patch.yaml
  ironic-deployment/overlays/e2e-with-inspector/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-with-inspector/kustomization.yaml
  ironic-deployment/overlays/e2e/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e/kustomization.yaml
  test/e2e/common.go
  test/e2e/config/fixture.yaml
  test/e2e/config/ironic.yaml
  test/e2e/e2e_config.go
  test/e2e/e2e_suite_test.go
  test/e2e/upgrade_test.go
  test/go.mod
  tools/bmh_test/vm2vbmc.sh
Labels: size/XL, lgtm, approved

#2238 :bug: Set ownerReference for dataImage during BMH Reconcile
  controllers/metal3.io/baremetalhost_controller.go
Labels: size/S, lgtm, approved

#2242 :seedling: workflows: sync pull_request trigger types
  .github/workflows/lint-docs.yaml
  .github/workflows/pipeline.yml
  .github/workflows/pr-gh-workflow-approve.yaml
  .github/workflows/pr-verifier.yaml
Labels: size/S, lgtm, approved

#2244 :seedling: pin osv-scanner image in verify-release.sh
  hack/verify-release.sh
Labels: size/XS, lgtm, approved

#2249 :bug: Add BMH OwnerReference for DataImage right after its creation
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/dataimage_controller.go
Labels: size/M, lgtm, approved

#2267 :seedling: Bump CAPI to 1.9.5
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, lgtm, approved
