Repository metal3-io/baremetal-operator, pull requests merged in 2025-01, with the labels that each got.

#2161 🌱 Add intervals while checking metrics service
  test/e2e/e2e_suite_test.go
Labels: size/S, lgtm, approved

#2165 🐛 Fix metrics service validation
  test/e2e/e2e_suite_test.go
Labels: size/XS, lgtm, approved

#2167 :sparkles: add support for locally built ironic in e2e test
  hack/ci-e2e.sh
  ironic-deployment/overlays/e2e-local-ironic/ironic-patch.yaml
  ironic-deployment/overlays/e2e-local-ironic/kustomization.yaml
Labels: size/M, lgtm, approved

#2166 :seedling: increase 1 timeout in external-inspection test
  test/e2e/config/fixture.yaml
Labels: size/XS, lgtm, approved

#2170 🐛 Fix BMO optional test by not checking metrics service
  test/e2e/e2e_suite_test.go
Labels: lgtm, approved, size/L

#2176 :seedling: bump kubeconform to v0.6.7
  hack/manifestlint.sh
Labels: size/XS, lgtm, approved

#2187 :seedling: bump x/net to v0.34.0
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, approved, size/L

#2186 :seedling: bump x/net to v0.34.0
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/M, lgtm, approved

#2185 :seedling: bump x/net to v0.34.0
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/M, lgtm, approved

#2175 :seedling: Update README badges and e2e triggers
  README.md
Labels: size/S, lgtm, approved

#2188 🐛 Fix metrics service validation
  test/e2e/e2e_suite_test.go
Labels: lgtm, approved, size/L

#2145 ✨ Add RBAC files for metrics authentication and authorization
  .golangci.yaml
  config/base/manager.yaml
  config/base/rbac/kustomization.yaml
  config/base/rbac/metrics_auth_role.yaml
  config/base/rbac/metrics_auth_role_binding.yaml
  config/base/rbac/metrics_reader_role.yaml
  config/base/rbac/metrics_service.yaml
  config/overlays/e2e/kustomization.yaml
  config/render/capm3.yaml
  main.go
  test/e2e/e2e_suite_test.go
Labels: lgtm, approved, size/L

#2174 :bug: Adding empty checksumType checks on BMH to automatically detect hashing algorithm
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/baremetalhost_types_test.go
Labels: size/S, lgtm, approved, ok-to-test

#2190 :bug: Add validation against cross-namespace secret references
  apis/metal3.io/v1alpha1/baremetalhost_validation.go
  apis/metal3.io/v1alpha1/baremetalhost_validation_test.go
Labels: lgtm, approved, size/L

#2191 🐛 Set e2e timeout to 1.5h
  .github/workflows/e2e-test.yml
Labels: size/XS, lgtm, approved

#2209 🌱 Switch e2e to kind
  .github/workflows/e2e-fixture-test.yml
  .gitignore
  config/overlays/e2e-release-0.4/ironic.env
  config/overlays/e2e-release-0.4/kustomization.yaml
  config/overlays/e2e-release-0.5/ironic.env
  config/overlays/e2e-release-0.5/kustomization.yaml
  config/overlays/e2e-release-0.6/ironic.env
  config/overlays/e2e-release-0.8/ironic.env
  config/overlays/e2e-release-0.9/ironic.env
  config/overlays/e2e/ironic.env
  config/overlays/fixture-release-0.4/kustomization.yaml
  config/overlays/fixture-release-0.5/kustomization.yaml
  hack/ci-e2e.sh
  hack/clean-e2e.sh
  hack/e2e/ensure_kind.sh
  hack/e2e/ensure_minikube.sh
  hack/e2e/net.xml
  ironic-deployment/components/tls/certificate.yaml
  ironic-deployment/overlays/e2e-release-24.0-with-inspector/ironic-patch.yaml
  ironic-deployment/overlays/e2e-release-24.0-with-inspector/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-24.0-with-inspector/kustomization.yaml
  ironic-deployment/overlays/e2e-release-24.1/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-24.1/kustomization.yaml
  ironic-deployment/overlays/e2e-release-25.0/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-25.0/kustomization.yaml
  ironic-deployment/overlays/e2e-release-26.0/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-26.0/kustomization.yaml
  ironic-deployment/overlays/e2e-with-inspector/ironic-patch.yaml
  ironic-deployment/overlays/e2e-with-inspector/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-with-inspector/kustomization.yaml
  ironic-deployment/overlays/e2e/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e/kustomization.yaml
  test/e2e/common.go
  test/e2e/config/fixture.yaml
  test/e2e/config/ironic.yaml
  test/e2e/e2e_config.go
  test/e2e/e2e_suite_test.go
  test/e2e/upgrade_test.go
  test/go.mod
  tools/bmh_test/vm2vbmc.sh
Labels: size/XL, lgtm, approved

#2154 🌱 Refactor and rename ValidateManagementAccess
  controllers/metal3.io/baremetalhost_controller.go
  controllers/metal3.io/host_state_machine_test.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/register.go
  pkg/provisioner/ironic/register_test.go
  pkg/provisioner/provisioner.go
Labels: size/XL, lgtm, approved

#2221 :seedling: Fix ensure_kind.sh filename
  hack/e2e/ensure_kind.sh
Labels: size/XS, lgtm, approved

#2224 :bug: bump golang to 1.23.5
  Dockerfile
  Makefile
  hack/e2e/ensure_go.sh
Labels: size/XS, lgtm, approved

#2226 :bug: bump golang to 1.23.5
  Dockerfile
  Makefile
  hack/e2e/ensure_go.sh
Labels: size/XS, lgtm, approved

#2225 :bug: bump golang to 1.23.5
  Dockerfile
  Makefile
  hack/e2e/ensure_go.sh
Labels: size/XS, lgtm, approved

#2227 🐛 Do not create HFC for non-redfish BMH
  controllers/metal3.io/baremetalhost_controller.go
Labels: size/S, lgtm, approved
