Repository metal3-io/baremetal-operator, pull requests merged in 2025-07, with the labels that each got.

#2552 :seedling: bump 6 k8s libraries and controller-runtime
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
Labels: lgtm, approved, size/L

#2554 :seedling: bump k8s.io/utils library
  go.mod
  go.sum
Labels: size/XS, lgtm, approved

#2559 ✨ Stop requiring DEPLOY_KERNEL/RAMDISK
  config/default/ironic.env
  config/overlays/e2e/ironic.env
  config/render/capm3.yaml
  pkg/provisioner/ironic/factory.go
  pkg/provisioner/ironic/factory_test.go
  pkg/provisioner/ironic/ironic.go
Labels: size/M, lgtm, approved

#2577 :bug: Add IPv6 address check to run local
  tools/run_local_ironic.sh
Labels: size/S, lgtm, approved
