Repository metal3-io/baremetal-operator, pull requests merged in 2025-05, with the labels that each got.

#2427 :seedling: add dependabot config for release-0.10
  .github/dependabot.yml
Labels: size/S, lgtm, approved

#2418 🐛 Redfish: correctly handle missing system ID
  pkg/hardwareutils/bmc/access_test.go
  pkg/hardwareutils/bmc/idrac_virtualmedia.go
  pkg/hardwareutils/bmc/redfish.go
  pkg/hardwareutils/bmc/redfish_virtualmedia.go
Labels: lgtm, approved, size/L

#2438 🌱 enable mnd linter
  .golangci.yaml
  cmd/get-hardware-details/main.go
  hack/tools/deploy-cli/deploy-cli.go
  internal/controller/metal3.io/action_result.go
  internal/controller/metal3.io/host_state_machine.go
  main.go
  pkg/provisioner/demo/demo.go
  pkg/provisioner/fixture/fixture.go
  pkg/provisioner/ironic/clients/features.go
  pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go
  pkg/provisioner/ironic/inspecthardware.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/register.go
  test/e2e/common.go
  test/e2e/e2e_config.go
  test/vbmctl/main.go
Labels: lgtm, approved, size/L, ok-to-test

#2450 🌱 Update periodic workflows for release-0.10
  .github/workflows/e2e-test-periodic-release-0.10.yml
Labels: size/XS, lgtm, approved

#2415 :bug: Make firmware update handle only a subset of `Spec.Updates`
  internal/controller/metal3.io/baremetalhost_controller.go
  internal/controller/metal3.io/baremetalhost_controller_test.go
Labels: size/M, lgtm, approved, ok-to-test

#2459 :book: update CII badge
  README.md
Labels: size/XS, lgtm, approved

#2454 🌱 E2E: Temporary workaround for connection issues
  .github/workflows/pipeline.yml
  hack/ci-e2e.sh
  ironic-deployment/overlays/e2e/ironic_bmo_configmap.env
Labels: size/S, lgtm, approved

#2471 🌱 Add a simple e2e test on externallyProvisioned
  test/e2e/config/fixture.yaml
  test/e2e/config/ironic.yaml
  test/e2e/externally_provisioned_test.go
Labels: lgtm, approved, size/L

#2466 :book: remove optional e2e badge link
  README.md
Labels: size/XS, lgtm, approved

#2446 :book: Add release-0.10 triggers to README.md
  CONTRIBUTING.md
  README.md
Labels: size/S, lgtm, approved

#2472 ⚠️ Prevent changing ExternallyProvisioned in the webhook
  internal/webhooks/metal3.io/v1alpha1/baremetalhost_validation.go
  internal/webhooks/metal3.io/v1alpha1/baremetalhost_validation_test.go
Labels: size/S, lgtm, approved

#2436 :seedling: Enable tagliatelle linter
  .golangci.yaml
  apis/metal3.io/v1alpha1/baremetalhost_types.go
  apis/metal3.io/v1alpha1/firmwareschema_types.go
  apis/metal3.io/v1alpha1/preprovisioningimage_types.go
  cmd/make-virt-host/main.go
  pkg/provisioner/ironic/ironic.go
Labels: size/S, lgtm, approved

#2445 :book: Update badges and e2e triggers in README.md
  README.md
Labels: size/S, lgtm, approved

#2476 🌱 E2E: Override IRONIC_HTTP_URL
  .github/workflows/pipeline.yml
  ironic-deployment/overlays/e2e-release-24.1/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-25.0/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-26.0/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e/ironic_bmo_configmap.env
  test/e2e/README.md
Labels: size/S, lgtm, approved

#2488 :seedling: make BMO periodics manually triggerable
  .github/workflows/e2e-test-optional-periodic.yml
  .github/workflows/e2e-test-periodic-main.yml
  .github/workflows/e2e-test-periodic-release-0.10.yml
  .github/workflows/e2e-test-periodic-release-0.8.yml
  .github/workflows/e2e-test-periodic-release-0.9.yml
Labels: size/XS, lgtm, approved

#2477 ✨ Allow disabling drivers that require a provisioning network
  docs/configuration.md
  pkg/provisioner/ironic/factory.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/ironic/register.go
  pkg/provisioner/ironic/register_test.go
Labels: size/M, lgtm, approved

#2448 :seedling: Add e2e tests for release 0.10
  config/overlays/e2e-release-0.10/ironic.env
  config/overlays/e2e-release-0.10/kustomization.yaml
  config/overlays/fixture-release-0.10/kustomization.yaml
  hack/ci-e2e.sh
  ironic-deployment/overlays/e2e-release-27.0/ironic-patch.yaml
  ironic-deployment/overlays/e2e-release-27.0/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-27.0/kustomization.yaml
  ironic-deployment/overlays/e2e-release-28.0/ironic-patch.yaml
  ironic-deployment/overlays/e2e-release-28.0/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-28.0/kustomization.yaml
  ironic-deployment/overlays/e2e-release-29.0/ironic-patch.yaml
  ironic-deployment/overlays/e2e-release-29.0/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-29.0/kustomization.yaml
  test/e2e/config/fixture.yaml
  test/e2e/config/ironic.yaml
Labels: lgtm, approved, size/L

#2492 🌱 Bump golang to v1.24
  .golangci.yaml
  Dockerfile
  Makefile
  Tiltfile
  hack/e2e/ensure_go.sh
  hack/generate.sh
  hack/gomod.sh
Labels: size/S, lgtm, approved
