Repository metal3-io/baremetal-operator, pull requests merged in 2025-06, with the labels that each got.

#2504 🌱 Bump golang to 1.24.3
  .golangci.yaml
  Dockerfile
  Makefile
  Tiltfile
  hack/e2e/ensure_go.sh
  hack/generate.sh
  hack/gomod.sh
Labels: size/S, lgtm, approved

#2519 :seedling: bump cloudflare/circl to v1.6.1 in /test
  test/go.mod
  test/go.sum
Labels: size/XS, lgtm, approved

#2522 :seedling: bump golang to 1.24.4
  Dockerfile
  Makefile
  hack/e2e/ensure_go.sh
Labels: size/XS, lgtm, approved

#2514 :seedling: Enable nilnil linter, fix warnings
  .gitignore
  .golangci.yaml
  internal/controller/metal3.io/baremetalhost_controller.go
  pkg/provisioner/ironic/ironic.go
Labels: size/S, lgtm, approved

#2527 :sparkles: Bump CAPI to v1.11.0-alpha.0 and do CAPI v1beta2 related changes
  .golangci.yaml
  apis/go.mod
  go.mod
  hack/tools/go.mod
  hack/tools/go.sum
  internal/controller/metal3.io/baremetalhost_controller_test.go
  internal/controller/metal3.io/bmceventsubscription_controller_test.go
  internal/controller/metal3.io/demo_test.go
  internal/controller/metal3.io/host_config_data_test.go
  internal/controller/metal3.io/host_state_machine_test.go
  internal/controller/metal3.io/hostfirmwarecomponents_test.go
  internal/controller/metal3.io/hostfirmwaresettings_test.go
  internal/webhooks/metal3.io/v1alpha1/baremetalhost_webhook_test.go
  internal/webhooks/metal3.io/v1alpha1/bmceventsubscription_webhook_test.go
  pkg/hardwareutils/go.mod
  pkg/provisioner/ironic/ironic_test.go
  test/e2e/common.go
  test/e2e/live_iso_test.go
  test/e2e/provisioning_and_annotation_test.go
  test/e2e/upgrade_test.go
  test/go.mod
  test/go.sum
Labels: lgtm, approved, size/L
