Repository metal3-io/baremetal-operator, pull requests merged in 2025-09, with the labels that each got.

#2590 🌱 E2E: Set static IPs through user-data
  hack/e2e/net.xml
  test/e2e/automated_cleaning_test.go
  test/e2e/bmc.go
  test/e2e/common.go
  test/e2e/external_inspection_test.go
  test/e2e/live_iso_test.go
  test/e2e/provisioning_and_annotation_test.go
  test/e2e/re_inspection_test.go
  test/vbmctl/main.go
Labels: size/M, lgtm, approved

#2650 :rocket: Release v0.10.3
  releasenotes/v0.10.3.md
Labels: size/S, lgtm, approved

#2623 :seedling: update github runners to oci gh arc runners
  .github/workflows/e2e-test.yml
Labels: size/XS, lgtm, approved

#2642 :book: Update info on running e2e locally
  test/e2e/README.md
Labels: size/M, lgtm, approved

#2655 📖 Add alpha release in release documentation
  docs/releasing.md
Labels: size/XS, lgtm, approved

#2674 :seedling: Add e2e tests for release 0.11
  config/overlays/e2e-release-0.11/ironic.env
  config/overlays/e2e-release-0.11/kustomization.yaml
  config/overlays/fixture-release-0.11/kustomization.yaml
  hack/ci-e2e.sh
  ironic-deployment/overlays/e2e-release-30.0/ironic-patch.yaml
  ironic-deployment/overlays/e2e-release-30.0/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-30.0/kustomization.yaml
  ironic-deployment/overlays/e2e-release-31.0/ironic-patch.yaml
  ironic-deployment/overlays/e2e-release-31.0/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-31.0/kustomization.yaml
  test/e2e/config/fixture.yaml
  test/e2e/config/ironic.yaml
Labels: lgtm, approved, size/L

#2679 :rocket: Release v0.11.0
  releasenotes/v0.11.0.md
Labels: size/M, lgtm, approved

#2678 :seedling: Add periodic release-0.11 test
  .github/workflows/e2e-test-periodic-release-0.11.yml
Labels: size/S, lgtm, approved

#2680 🌱 Add IPA_BASEURI to download ipa image from Nordix
  ironic-deployment/overlays/e2e-release-26.0/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-27.0/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-28.0/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-29.0/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-30.0/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e-release-31.0/ironic_bmo_configmap.env
  ironic-deployment/overlays/e2e/ironic_bmo_configmap.env
Labels: size/XS, lgtm, approved

#2686 🌱 E2E: Make timeout configurable and increase it for optional periodics
  .github/workflows/e2e-test-optional-periodic.yml
  .github/workflows/e2e-test.yml
Labels: size/S, lgtm, approved

#2690 🐛 Create a PreprovisioningImage for servicing if needed
  internal/controller/metal3.io/baremetalhost_controller.go
  pkg/provisioner/ironic/ironic.go
  pkg/provisioner/provisioner.go
Labels: size/S, lgtm, approved

#2698 :warning: Change architecture default to match controller
  internal/controller/metal3.io/baremetalhost_controller.go
Labels: size/S, lgtm, approved

#2677 :seedling: Fix OSV-Scanner
  .github/workflows/osv-scanner-scan.yml
  .github/workflows/scheduled-osv-scan.yml
Labels: size/M, lgtm, approved

#2703 :seedling: add specific time to dependabot config
  .github/dependabot.yml
Labels: size/S, lgtm, approved
